### ISSUE TITLE
Introduce source catalog class for simulated catalogs

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1016]
Now that there's a `CatalogImageEstimator` and and a nice `SourceCatalog` base class we should introduce something like a `SourceCatalogMC` class, which handles simulated catalogs in well defined formats.

**Comment by cdeil** [comment]
Do we really need this? What's your use case?

Ideally there would be a catalog format that works for real and simulated catalogs, no?

Currently the most complex sky model we have is 1DC, part of it is here:
https://github.com/gammasky/cta-dc/tree/master/sky_model
It's a bunch of XML sky model files, in some cases (like image and cube templates or pulsars) pointing to FITS files.

The other complex use case I'm aware of is gamma-cat. There we don't have a good format, but we could implement what Matthew uses, see https://github.com/gammapy/gamma-cat/issues/101#issuecomment-295918515 and see if that covers our use cases.

I'm not a huge fan of XML, but it is being used by many gamma-ray astronomers already and is extensible and can be hierarchical.
So my wish would be that we focus on `gammapy.utils.modeling` and the spatial and spectral models first to support that for us and others, and then maybe on top of that build a smart catalog class that can store such things in FITS tables (for convenience, to have the whole model in a single file).

@adonath - Thoughts?

**Comment by adonath** [comment]
@cdeil The main use case I have in mind is computing simulated sky images, plotting simulated spectra and flux points etc. just the same way we already do for real catalogs.

I agree this would be solved best with a uniform catalog format. I was still in the habit of introducing a new catalog class for any format we have...but long-term we might give up on this and just use a common format.

**Comment by cdeil** [comment]
OK, let's keep this issue open as a reminder.
A class implementing the format that Matthew uses (see his explanation and example file at https://github.com/gammapy/gamma-cat/issues/101#issuecomment-295918515) would be very welcome in Gammapy (as would any similar format that works).

**Comment by cdeil** [comment]
@adonath - I'm closing this issue.

The `CatalogImageEstimator` is gone, and we now have the sky model classes and `MapEvaluator` and `MapFit` instead. I feel like work should now focus on model serialisation: first with the existing XML format (see https://github.com/gammapy/gammapy/issues/1402#issuecomment-408186996) and then with a better YAML format.

With that way forward, the suggestion above to add a `SourceCatalogMC` isn't really needed. Or the suggestion is replaced by the new model classes, but then I think we should open a new issue more clearly describing what should be done, so that someone can pick up the task soon.
