### ISSUE TITLE
Improve 3D PSF kernel computation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1047]
In a3c9bff38d17504d07cb4f9a5b871194430609cc @robertazanin and added a hack to make the 3D PSF kernel computation work for the CTA example. This is a reminder issue assigned to myself to put in a proper fix and add a test.

The problem is in [EnergyDependentTablePSF.table_psf_in_energy_band](http://docs.gammapy.org/en/latest/_modules/gammapy/irf/psf_table.html#EnergyDependentTablePSF.table_psf_in_energy_band). There, currently the PSF energy binning is used, and for CTA that energy binning is coarse, so not a single energy bin was fully falling into `energy_range` and thus no PSF was computed.

My suggestion is to change the API and implementation of this method like this: add an `n_points` method, and use that in combination with `energy_range` to set up an energy grid, and then to evaluate (i.e. interpolate) the PSF on that energy grid. This would make the computation / result independent of the intrinsic PSF energy grid, and work for any case (very fine or very coarse intrinsic PSF energy binning). Usually the caller decides on the energy grid and should pick energy bins so that the PSF doesn't change drastically.
@adonath - OK or do you  have a different suggestion?
Preference for default `n_points` of 1, 2, 3, 5, 10?

**Comment by adonath** [comment]
Sounds good to me. Maybe it's possible to make the API consistent with [integrate_spectrum](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.integrate_spectrum.html#gammapy.spectrum.integrate_spectrum), where we used `xmin`, `xmax` and `ndecade`. I don't really care which parametrization to use. I slightly prefer the latter, because `ndecade` allows to set the precision of the integration independent of the energy range...

Reading the code in `EnergyDependentTablePSF.tabel_psf_in_energy_band()` I think there's another problem involved: currently there's only nearest neighbour interpolation in energy (see [EnergyDependentTablePSF._energy_index()](https://github.com/gammapy/gammapy/blob/master/gammapy/irf/psf_table.py#L761)). So the problem is related to https://github.com/gammapy/gammapy/issues/570...

**Comment by cdeil** [comment]
I'm also not sure what is the best option to offer callers concerning precision. There are use cases where `n_decade` works better and where `n_points` works better (e.g. for cube analysis, where users chose their energy binning so that it's appropriate and exposure, PSF and EDISP don't vary strongly within energy bins).

Some callers will probably need the full power of choosing the energy grid points, so computing the energy grid could be a separate first step, and always also exposed to users via a 
`energy_grid=None` option, and if given `energy_bins` and `n_points` are ignored?

It's a bit tricky how to expose this in a flexible, yet simple way.

> Reading the code in EnergyDependentTablePSF.tabel_psf_in_energy_band() I think there's another problem involved: currently there's only nearest neighbour interpolation in energy (see EnergyDependentTablePSF._energy_index()). So the problem is related to #570...

If we just call `table_psf_at_energy` and that does interpolation in energy (any kind) from `table_psf_in_energy_band`, it's fine, no?

**Comment by cdeil** [comment]
@registerrier - I'm deferring this issue to the v0.9 milestone.

I think the new way to make PSF kernels is mostly [PSFKernel.from_table_psf](http://docs.gammapy.org/dev/api/gammapy.cube.PSFKernel.html#gammapy.cube.PSFKernel.from_table_psf)? Probably what should be done is to add options for spectrum weighting or better integration in energy there?

Note that in Fermi-LAT the PSF (represented by `EnergyDependentTablePSF` in Gammapy) has a 1D exposure array attached. Maybe we should do the same for our reduced IRFs to allow for easy exposure weighting?
