### ISSUE TITLE
Add light curve estimation tutorial

### ISSUE THREAD

**Issue by paquique** [gammapy/gammapy#1095]
Dear all,

Together with @Armengol-JM, @TarekHC and @moralejo, we have been playing with MAGIC DL3 data. We tried to create a light-curve. We found some trouble and we were not able to make it work. In https://github.com/gammapy/gammapy/issues/982 it is stated that the LightCurveEstimator is indeed working.

A notebook on the topic would be very useful for people starting to use gammapy. I believe there was a first attempt started here:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/time_analysis.ipynb

I guess this is low priority, but maybe it is useful to have an issue pointing this out (and probably does not require a lot of effort to fix).

Thanks!

**Comment by cdeil** [comment]
Agreed, an example of how to make a lightcurve should be added to that notebook.

We don't have a nice example dataset at the moment of a variable source, but for now just one of the steady sources we use in other notebooks can be used to compute a few LC points, and then it's easy to change to a more interesting variable source once such a dataset becomes available.

@jjlk added the LC estimator, and also a working example (in the form of a test, not visible in the docs or notebooks) here:
https://github.com/gammapy/gammapy/blob/b305e8fcf822da65a66f4e3f8a4a2dc4f49ea06b/gammapy/time/tests/test_lightcurve.py#L88

@jjlk or one of the people in CC here: a PR to update that notebook, adding an example how to make a LC would be welcome any time! (probably start by copy & pasting the example from the test).

**Comment by cdeil** [comment]
@paquique - There were recently some fixes in the `LightCurveEstimator` in Gammapy, and a tutorial notebook how to make a lightcurve was added here: http://docs.gammapy.org/en/latest/notebooks/light_curve.html

@paquique - If you have time, could you please have a look and try again making the lightcurve for your application? If you find any issues or have suggestions for improving the LC code or docs, please comment here!

**Comment by labsaha** [comment]
Is there any effort going on to get folded light curve?

**Comment by cdeil** [comment]
@labsaha - Probably no.

But what do you mean by folded light curve? Do you mean pulsar analysis? What computation specifically?

**Comment by labsaha** [comment]
@cdeil 
Currently, I am analyzing LS I 61 + 303  using DC-1 data using gammapy. The orbital period of the system is ~ 26 days. I see that data is distributed in 2 different orbital cycles. So, I want to have a phase-folded light curve.

**Comment by cdeil** [comment]
@labsaha - Can you please open an issue in https://github.com/gammasky/cta-analyses and start a new folder there for this? It's possible, but since you are the first to do this kind of analysis with Gammapy, it will probably take some effort to get it done and there might be bugs or missing features in Gammapy.

Just briefly, I would suggest to start with this: compute a "phase" for each observation you have (e.g. using run start or run mid time). Then bin the phase somehow - this is up to you how to create the phase bins. Then run a normal spectral analysis for each phase bin, and from the fitted spectrum compute an integral flux for any energy range you like -> out comes the phase-folded light curve.

In Gammapy we do have the `LightCurveEstimator` and we might want to modify it or create a new class to automate what I just described. But maybe it's already pretty nice and even more flexible to let the user do the phasing and phase binning themselves as a first step?

**Comment by labsaha** [comment]
@cdeil Ok. I'll create an issue in  https://github.com/gammasky/cta-analyses and create a new folder for this. I'll follow the procedure as you suggested to perform that analysis.

**Comment by cdeil** [comment]
Now there is a nice example dataset available for lightcurve, the PKS 2155 flare from HESS:
https://github.com/cdeil/HESS-DL3-DR1-preview

I'd suggest to change the existing tutorial notebook (http://docs.gammapy.org/dev/notebooks/light_curve.html) to use that.

**Comment by cdeil** [comment]
I updated to light curve tutorial in https://github.com/gammapy/gammapy-extra/commit/947187d595e6dcfc7fd7177d1484fa247ccbd4d1

The current version is here: https://github.com/gammapy/gammapy-extra/blob/master/notebooks/light_curve.ipynb
