### ISSUE TITLE
gammapy-extra package and resource management

### ISSUE THREAD

**Issue by kosack** [gammapy/gammapy#1131]
It would be nice to have at least the datasets part of gammapy-extra in its own pip or conda-installable package. If that was the case, it would be possible to get files from it without forcing the user to set `$GAMMAPY_EXTRA` using the `pkg_resources` module.  It could get installed automatically as a dependency of gammapy, or optionally.  Let's say the module inside the gammapy-extra pacakge is called `gammapy_datasets`, you could do the following to load the 3FGL catalog for example:

```python
import pkg_resources

filename = pkg_resources.resource_filename('gammapy_datasets', 'catalogs/fermi/gll_psc_v16.fit.gz')
```
This would load the file without the user having to worry about where it is installed. 

The implementation would require restructuring gammapy-extras a bit, and making the modules that should be package-able  real python packages (with __init__.py inside), or making it one global package with all inside (in which case it has to be renamed to remove the hyphen)

Something like this would work for setup.py:

```python
setup(
    name='gammapy-extra',
    packages=find_packages(),   # finds all sub-packages (or just list ['gammapy_datasets',] to get only that one)
    package_data={'gammapy_datasets': '*'},
)


```

**Comment by cdeil** [comment]
I agree 100% that the current setup for data files is bad. Having to download the full gammapy-extra repo to load and use a Fermi catalog is no good.

The problem is that it's not easy to do this well. This has been discussed quite a bit before (there are other issues open in the Gammapy issue tracker). It needs some more discussion, but mostly a volunteer to implement a better solution.

@kosack - Concerning your suggestion to distribute the data via a Python package: I don't think that's a great solution, the way to go. Note that PyPI has a limit of 50 MB, so it doesn't scale to even mid-sized data like HESS or Fermi or CTA example datasets that we do want to use at least for docs.
Also distributing data like a software package (i.e. PyPI and eventually conda and possibly other distributions) is quite some work.

So I think a separate solution should be implemented, where data is versioned and we have simple functions or a command line tool to download files locally. The hard things about this are where to put it by default and how to version it. Maybe it's possible to never update the same files, i.e. only add new ones, and the versioning issue mostly goes away. We could start simple, and just implement something that works for the files directly accessed from Gammapy (~ 5 catalogs), and provide something like `python -m gammapy download cats` and put it somewhere where then the catalog read looks by default (or even use the Astropy download / file cache, although when I used it last, I didn't like how they put hashes as filenames and it never was clear what files one has and where they are).

**Comment by kosack** [comment]
Yes, it's not an easy thing to do... Having them downloadable with a cache seems best in the end.  

This also relates to some things that are apparently hard-coded into gammapy, like the location of the gammacat files (which are inexplicably in a directory called *docs* and not in `$GAMMAPY_EXTRA/datasets`).  Having one way to access required catalog files would be ideal.

**Comment by cdeil** [comment]
@Bultako has resolved this in the past weeks.
See https://github.com/gammapy/gammapy/pull/1419

The implementation is almost finished, we will try it with users in the next days.
http://docs.gammapy.org/dev/getting-started.html#download-tutorials

Closing this old issue.

@kosack - New issues or comments here welcome any time.
