### ISSUE TITLE
After the PR #1145: ring artefacts and new improvements

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1148]
Hi all,
In this PR process, it was mentionned that some artefacts at high offset angles seen during the coding sprint could be still here. With a basic test case, I did not see anymore this artefact after this PR patch. Is there still a case for which is happened? 
The second point is very important. It seems that the radial acceptance is not used at all during the ring computation, which is the core of the ring algorithm. When we will run this class at high energy, it will never work. Can we implement it, in addition to the fft_convolve method?
Cheers,
Bruno

**Comment by adonath** [comment]
I would be surprised if #1145 resolved the issue, because I still saw the artefacts in the CTA GPS image I computed with the code that already included the changes introduced in #1145. My first guess is that there is a bug in the implementation of the `RingBackgroundEstimator`. Because I implemented ~2 years ago, without knowing all the details of the algorithm. Maybe someone who knows the details of the e.g. HAP implementation can have a look and check that the method.

**Comment by cdeil** [comment]
Moving to v0.8. @adonath - What is the status of ring background estimation in Gammapy? Are there known serious issues or is it mostly OK by now?

I see that there's still 13 "TODO", and some that sound like bugs, here:
https://github.com/gammapy/gammapy/blob/c421ba9694d443088f49a9b122b55b71f0cde159/gammapy/image/basic.py

I'm moving this issue to v0.8. @adonath or @bkhelifi - if either of you has time to make a PR to make it better (resolve the TODOs / bugs and maybe add good test cases), please go ahead. Although for the long-term solution, I would suggest to rewrite more from the ground up (and from the start have good tests that prove that things are working properly), as I commented in https://github.com/gammapy/gammapy/issues/948#issuecomment-342000272 .

**Comment by cdeil** [comment]
@registerrier - Assigning to you and moving milestone to v0.9.
Close this issue or is it useful for you to develop the new function that does ring bg estimation?

**Comment by cdeil** [comment]
Closing this old issue. Note that #1198 is still open.
