### ISSUE TITLE
BasicImageEstimator of image/basic.py: spectral index

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1152]
Dear all,
In this class, the spectral index is used to compute the average PSF in the FoV, to compute the weighted exposure, and indirectly the background (for a reason that I have not understood at all!).
By default, a spectral model is used. When adding a spectral model to the constructor, do we change the spectral index for all the computation of exposure, bkg, PSF? Can we add an example in a notebook?

**Comment by adonath** [comment]
@bkhelifi Yes, the given spectral model is used as weights to compute the mean PSF and mean exposure in the given energy range. It is not used to compute the background model, only indirectly via the exposure. I agree it would make sense to add an example at least to the docstring. Because of flexibility I thought it was better the user can pass an arbitrary spectral model, instead of only the power law index. In some cases, e.g. if a source has a steep cut off this might be relevant. What is missing right now is that re-normalization step of the spectral model, which has to be done by the user right now. This should added to the class along with a few examples, as you suggested.

**Comment by cdeil** [comment]
Agree with @adonath - Let's keep the general solution of taking a spectral model, all that's needed for this aspect is to improve the documentation how it works, minimally to show this:
```python
from gammapy.spectrum.models import PowerLaw
spectral_model = PowerLaw(index=2.6)
```
which is all that Yves wanted to do / know.
@adonath - I don't understand the needed spectrum re-normalisation. If this is really needed, then yes, it shouldn't be left up to the user, or they will get it wrong in a large fraction of cases.

**Comment by adonath** [comment]
@cdeil The way the spectral weighting is implemented right now requires a spectral model the integrates to unity in the range between `emin` and `emax`. This "renomalization" should be done internally using `SpectralModel.integral()` instead.

**Comment by cdeil** [comment]
Moving to v0.9 milestone, keeping this issue open for now as a reminder to make the spectrum weighting nice and clear in the new code. Existing code like `BasicImageEstimator` will be removed anyways, doesn't make sense to work on that now.

**Comment by cdeil** [comment]
@registerrier - Assigning this old issue to you and moving it to the v0.8 milestone.

It's discussing spectral weighting of the PSF with the old code.
I think that's not available yet in the new code you are adding for PSF evaluation?
So maybe worth keeping open as a reminder, and something to work on next week?

**Comment by cdeil** [comment]
Closing this old issue, let's continue the discussion in #1571.
