### ISSUE TITLE
Add units to gammapy.maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1206]
@woodmd and I previously discussed and I think it's already agreed that we should add a unit to maps. I'm opening this issue to discuss some specifics, and then plan to make a pull request next week.

The idea is to store a unit string, and to not introduce Quantity objects in gammapy.maps. This has been discussed / considered already, and I think it is agreed, but if it's not clear I can motivate the choice.

Off the top of my head, I have these questions (when I start adding it probably more detailed questions will come up):

Should the unit be stored on the geometry or map object?

I'm roughly 50:50 on this. I mean - in a way the geometry object was introduced to group wcs and shape, so it's not a bad idea to put all "metadata", i.e. everything apart from the main data array there. On the other hand, the data unit isn't really part of the "geometry", and in http://astropy.readthedocs.io/en/stable/api/astropy.nddata.NDData.html it's also a separate attribute.

A related question is whether we want or even need to have a "meta" attribute. How is map "meta" info currently handled? On FITS read, there is no way to read all the FITS header keys, like `Table.read` puts it in a `meta` dict, right? Or is this stored somewhere?

The second question I have is concerning FITS I/O: I guess we want to read / write unit automatically on FITS I/O, no?

My last question would be if we want to expose a `quantity` property that does this or not?
```
from astropy.units import Unit
def quantity(self):
    return self.data * Unit(self.unit)
```
I think it's a nice convenience for code that wants to use maps and do quantity-based computations, no? Or is there a problem with encouraging that?

@woodmd, but also  @adonath @joleroi anyone -- thoughts?

**Comment by woodmd** [comment]
> Should the unit be stored on the geometry or map object?

My vote would be for storing it in the map object since it's a property of the map data member.  I could envision wanting to use the geometry of map quantity X (e.g. exposure) to instantiate an empty map quantity Y (e.g. counts).  If you have the unit as a property of the geometry you would need to take an extra step to strip it when doing this kind of operation.

> A related question is whether we want or even need to have a "meta" attribute

A meta attribute sounds like it could be useful -- especially if this is a pattern that's used elsewhere.  My suggestion would be to create a single keyword for meta data and then fill that with a json or yaml string.  I use this approach currently in fermipy to serialize the analysis configuration dictionary to FITS.

> The second question I have is concerning FITS I/O: I guess we want to read / write unit automatically on FITS I/O, no?

Yes I think the unit should be written to the file somehow.  Whatever convention we decide on should be added as an optional keyword to the format spec.

> My last question would be if we want to expose a quantity property that does this or not?

I don't have strong feeling about this but it doesn't seem like there would be any harm in adding a method like this.  Does converting to a quantity return a view or a copy?  In the latter case you might want to warn users about the potential performance overhead.

**Comment by adonath** [comment]
I agree with @woodmd  that the unit should be on the map object, because it is a property of the data. I also support to add a `.quantity ` attribute as suggested by @cdeil, I think this convenient for many use cases. Note that e.g. the `astropy.table.Column` object also has this kind of convenience method. 

I also agree we should support FITS I/O for units. I guess the only question is if we can use the already existing FITS unit conventions and formats (which could be handled with  `astropy.units` and `astropy.io.fits`) or  whether we have to introduce and document our own formats with special keywords.

**Comment by registerrier** [comment]
If ``.data``is not a quantity, I would also encourage  adding a ``.quantity`` attribute for operations on the data themselves.  
Note though that for methods such as ``coadd``from #1281, there should be a test of dimensionality performed. Can it be done simply without having a ``.data`` being a ``Quantity``?

**Comment by cdeil** [comment]
Yes, we should have `.quantity`. That's also how the astropy table column object works. It stores `.data` and `.unit` and has a `.quantity` property that returns `self.data * Unit(self.unit)`.

**Comment by registerrier** [comment]
I am implementing the unit attribute at the moment.
Note that the `.quantity` property cannot work as is for sparse matrices because  `self.data * Unit(self.unit)`is not a licit operation.

**Comment by registerrier** [comment]
Also one can define a quantity setter which will deal with proper unit conversion: e.g.
```
    @quantity.setter
    def quantity(self, val):
        if val.shape != self.data.shape:
            raise ValueError('Wrong shape.')

        # TODO: add decorator for unit consistency?
        if isinstance(val, Quantity):
            if not Unit(self.unit).is_equivalent(val.unit):
                raise ValueError('Incorrect unit')
            else:
                self._data = val.to(self.unit).value
        else:
            if not Unit(self.unit).is_equivalent(''):
                raise ValueError('Incorrect unit')
            else:
                self._data = val
```

**Comment by cdeil** [comment]
Just to summarise what we discussed just now by phone. @joleroi suggested to do the same as here:
```
    @quantity.setter
    def quantity(self, par):
        par = u.Quantity(par)
        self.value = par.value
        self.unit = str(par.unit)
```
https://github.com/gammapy/gammapy/blob/ef65cb4622e8893f55c18fa584aec47ee178c423/gammapy/utils/modeling.py#L104

and if that doesn't work for `+=` or `fill_by_*`, then OK to leave that for a second PR for later.
Having unit preserved on FITS read / write would be great.

Finally, for the sparse maps, I think it's also OK to leave that for the future (see #1332).
I don't think any of the analysis code we're starting to develop works with sparse or even multi-resolution maps for now. I think it's fair to get 3D analysis just with an energy axis working now, and then generalise to work with other maps; we still have the warning at the top of
http://docs.gammapy.org/dev/maps/index.html
> The code in gammapy.maps is currently in an experimental/development state. Method and class names may change in the future.

**Comment by registerrier** [comment]
The PR #1374 provides a first input.

**Comment by cdeil** [comment]
Done by @registerrier in #1374 .

For now, we put `_unit` as string and empty string for no unit, and also as default.
But access to unit is only via the `unit` property, which does `Unit(self._unit)`.

The two things that could have been done is to use `None` for no unit, and to store `Unit` objects as data members. I think this is what is done more frequently in Astropy (e.g. NDData) and might have been the better choice. If anyone has an insight or opinion on this point, please comment here or open a new issue.

But for now, what we have seems to work OK. Closing this issue.
