### ISSUE TITLE
Problem in SpectrumEnergyGrouper

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#1209]
Hi @cdeil , @joleroi ,

Apparently we didn't totally fix the `gammapy.spectrum.SpectrumEnergyGrouper`. I 've got a simple example showing that I do not have what I expect, using a simulation from `gammapy.scripts.CTAObservationSimulation`. The script is here: https://gist.github.com/jjlk/ce04bfd9d1ccdbf4ea8f947968b424da (sorry for the notebook Christoph, i couldn't make it).

It's not easy for me to read the `SpectrumEnergyGrouper` code so if I could get any help it would be ultra nice.

Thanks

Julien

**Comment by cdeil** [comment]
@jjlk - Thanks for the bug report.

I've started to write code for better energy grouping tests, that don't simulate or load data, but just set up a test case one can tailor to what one wants to test, and then later on read and understand here:
https://gist.github.com/cdeil/cab8c4e089ccd442170e3d7b5ace1cb4

@jjlk - Could you please try to edit it to show the bug you're seeing there?

This would then be the start for a pull request, where the first step is to add that better test to
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_energy_group.py
(and ideally exchange the existing test case to that -- the current one has the same problem as your example that reading `test_energy_group.py` is difficult because the test case isn't clearly visible / chosen.

I'm not sure when I'll have time for this, so @jjlk or @joleroi or anyone -- help would be appreciated!

**Comment by jjlk** [comment]
Hi @cdeil,
Here is a gist reproducing the bug: https://gist.github.com/jjlk/7e523dde212fde34daff269e29c37790

I remember now. We never really fixed the issue with @joleroi .

If I want to use the simulation's energy bounds to group the bins, it works because we added a trick to do nothing in `SpectrumEnergyGroupMaker.compute_groups_fixed`.

Now, if I want to start above the first bin, at an energy corresponding to one of the bin edges, we do not fulfill the condition and pass through the factory and it kills the lower bin.

It should be not too difficult to fix once I understand (one more time) how it works

**Comment by cdeil** [comment]
@jjlk - I'd like to release v0.7 this week. What's the status here? OK to move to v0.8 as a reminder to add further tests / cleanup to energy grouping? Or is there still a bug that prevents you from doing CTA simulations that's high priority to fix?

**Comment by cdeil** [comment]
Should be fixed in gammapy master now, since last week (see #1493).
If there's still any issue with energy grouping, please re-open or file a new issue!
