### ISSUE TITLE
WcsMap.read() does not work

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1242]
Running:
` res=WcsMap.read("test/Vela_ADA/Vela_3_12TeV.fits",hdu='counts')`
yields the following error:
```    119         
    120         with fits.open(filename) as hdulist:
--> 121             map_out = cls.from_hdulist(hdulist, **kwargs)
    122         return map_out
    123 

/Users/terrier/Code/gammapy/gammapy/build/lib.macosx-10.5-x86_64-2.7/gammapy/maps/wcsmap.py in from_hdulist(cls, hdulist, hdu, hdu_bands)
    119             hdu_bands = hdulist[hdu_bands]
    120 
--> 121         return cls.from_hdu(hdu, hdu_bands)
    122 
    123     def to_hdulist(self, extname=None, extname_bands=None, sparse=False,

AttributeError: type object 'WcsMap' has no attribute 'from_hdu'
```

On the other hand `WcsMapND.read()` works fine. Is it an expected behavior @cdeil @woodmd ?

**Comment by cdeil** [comment]
@registerrier - The `MapBase` and `WcsMap` classes are abstract base classes, it's not possible to create an instance of those. So here you should use `WcsMapND.read` as you already mention.

```
>>> from gammapy.maps import MapBase, WcsMap, WcsMapND
>>> MapBase()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class MapBase with abstract methods crop, downsample, fill_by_idx, get_by_idx, interp_by_coords, iter_by_coords, iter_by_image, iter_by_pix, pad, set_by_idx, sum_over_axes, upsample
>>> WcsMap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class WcsMap with abstract methods crop, downsample, fill_by_idx, get_by_idx, interp_by_coords, iter_by_coords, iter_by_image, iter_by_pix, pad, set_by_idx, sum_over_axes, upsample
>>> WcsMapND()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'geom'
```

I'm not sure what exactly to change about the implementation and / or docs to make this simpler / clearer. This is the docs that we currently have:
* http://docs.gammapy.org/en/latest/maps/index.html#fits-i-o
* http://docs.gammapy.org/en/latest/maps/index.html#constructing-with-factory-methods

Would it be a good idea to try and make `read` work on one of the base classes, and have it try to auto-detect the format and create an appropriate class (to mirror what `MapBase.create` does)?

Or we could remove [MapBase.read](http://docs.gammapy.org/en/latest/_modules/gammapy/maps/base.html#MapBase.read) on the base class, and only add it to the classes that do support a `read` call?

Or we could do small improvements to make the error message and docs a little clearer?

@woodmd or anyone interested in this - Thoughts?

**Comment by woodmd** [comment]
Yes this is the expected behavior.  On the other hand I suspect this will be a frequent occurrence so I agree that we should either improve the error message or define some fallback behavior when the base class is called.  Note that there is nothing in the file itself which dictates which format is appropriate (a non-sparse map can be instantiated from a sparse map file and vice versa).  

One approach would be to default to instantiating a non-sparse map (either with `WcsMapND.read` or `HpxMapND.read`) when the base class read method is called.  It's likely that most users will be working with the non-sparse classes at least initially.  For `MapBase.read` one would additionally need to determine if the file is in HPX or WCS format but I think this should be fairly straightforward to implement by peeking in the FITS header.  If this approach sounds acceptable I can put together a PR with these changes.

**Comment by cdeil** [comment]
I think changing `MapBase.read` to be a factory function that makes it convenient to read most maps is a good idea.

There's the question about location of this function, it could of course also be a standalone factory function `read_map`. I'm about 50:50 on this, either way is fine with me. For users maybe a standalone `read_map` would be more natural. But since we already have the `MapBase.create` factory function on the base class, and the [docs](http://docs.gammapy.org/dev/maps/index.html#constructing-with-factory-methods) import `MapBase` to use `MapBase.create` already a lot, adding `MapBase.read` makes sense.

To me, it's not clear yet how all the other map read functions should be structured, i.e. whether e.g. `WcsMap` or `WcsMapND` or the other map classes get a `read` function and what exactly they do. But @woodmd - I think you have an idea here already and can just show us via a pull request?

One more point about `MapBase.read` is whether it should do auto-discovery of format from FITS headers or convenient user-selection of format via arguments (similar to what you put in `MapBase.create`? Or both, and by default to auto-discovery of format, and if the user passes arguments they take precedence and the function errors out if the format doesn't match? So in detail I'm not sure about the logic and arguments that function should have, but again: probably easiest if @woodmd , you make a proposal via a pull request and then we do some review there, and then put it in to get some real-work user feedback.

**Comment by registerrier** [comment]
Thanks for the feedback. I have been confused by the naming scheme. 
Intuitively, it is not so clear that WcsMapND is the default class for WCS based maps.  It is clear that MapBase is an abstract base class but not WcsMap. What is the point of having both WcsMap and WcsMapND? No other class inherit from WcsMap, no?
 
I don't know what is the good method here. A global read_map function is indeed nice. A minima an exception could be raised if someone is trying to use a constructor function from a base class.

**Comment by cdeil** [comment]
@woodmd - I also remember that I was confused about which maps class I should import and use to create or read a given map when I first used it. You gave a very nice overview in [this presentation](https://github.com/gammapy/gammapy-meetings/blob/master/2017-09-21/gammapy_maps_overview.pdf), maybe some of that overview info can be added do http://docs.gammapy.org/dev/maps/index.html .

Concretely, I think showing the class hierarchy to users might help, and then a few sentences with info when to import and use which class. It is possible to auto-generate a class inheritance diagram by removing the `:no-inheritance-diagram:` option on the `automodapi` directive at the end of `docs/maps/index.rst`:
```
.. automodapi:: gammapy.maps
    :no-inheritance-diagram:
```
It would look like this:

![screen shot 2018-01-10 at 11 45 38](https://user-images.githubusercontent.com/852409/34769101-29d2ef46-f5fd-11e7-8b59-ae9913e18fc2.png)

I added the `no-inheritance-diagram` everywhere in Gammapy since we don't use inheritance much and the diagrams weren't useful. In `gammapy.maps` it might be useful. I would suggest to either add that and link to it from the introduction, or to just summarise the existing classes manually in the introduction or somewhere near the top of the page.

@registerrier - As you can see in that presentation, the idea is to add a sparse WCS map class, and I think it's still the case, that's something we want to add later to improve efficiency for some use cases. Looking at the intermediate `HpxMap` class where already two sub-classes exist, it does contain some stuff, but not much. @woodmd  - Do you see any need to re-discuss the class hierarchy, or are you happy with the one that is in place?

Also, @woodmd - FYI: @registerrier and I start work on new high-level analysis code now to make maps and cubes (counts, exposure, background) for IACTs and to use them for modeling / fitting, based on `gammapy.maps`. More info on that soon elsewhere. So we might have a few more questions or comments on `gammapy.maps` in the coming weeks.

**Comment by cdeil** [comment]
> It is clear that MapBase is an abstract base class but not WcsMap

@woodmd - should users ever import `WcsMap` and e.g. call `WcsMap.create` directly? Or is this intermediate class only for code re-use, but users would never type `WcsMap` directly to work with maps, and instead only have to know about `MapBase` and `WcsMapND`? If so, then the name of this intermediate class doesn't matter so much.

Still, it might be worth considering a rename to `WcsMapBase` to make it clearer that it's an ABC.
Or even a larger rename, like from the current
```
MapBase -> WcsMap -> WcsMapND
```
e.g. to this to achieve a little bit more consistency (favouring brevity over trying to show what is an abstract base class or normal class via the name):
```
Map -> WcsMap -> WcsNDMap
```
I think that would be my favourite, but I don't feel strongly, what we have now is fine with me also. After this discussion and the v0.7 release we will keep the names forever, so if anyone has opinions on this, speak up now. Eventually @woodmd should just decide, as it's a matter of taste, and probably tastes will differ.

**Comment by woodmd** [comment]
> I think you have an idea here already and can just show us via a pull request?

Done (see #1246).  As you suggested the new version does auto-discovery by default but allows the user to override that with the `map_type` argument.

> I think showing the class hierarchy to users might help, and then a few sentences with info when to import and use which class

Fine with me.  I propose we leave this to a follow-up PR that we can combine with your suggested class name changes.

> Do you see any need to re-discuss the class hierarchy, or are you happy with the one that is in place?

I think the present hierarchy is fine as is.  Note that one motivation for having the intermediate base classes is to provide a place to stick code that's common to both sparse and non-sparse maps.

> should users ever import WcsMap and e.g. call WcsMap.create directly?

There's nothing wrong with calling this persay but perhaps we should encourage users to use the `MapBase` interface instead.  One option might be to make WcsMap.create and HpxMap.create into private methods.

> Eventually @woodmd should just decide, as it's a matter of taste, and probably tastes will differ.

I like your proposed names so I'd move that we go ahead and open a new PR to change these once we close #1246.

**Comment by cdeil** [comment]
@registerrier and maybe @woodmd - Can we close this old issue? Or is there any action item left here?

**Comment by registerrier** [comment]
OK Let's close.
