### ISSUE TITLE
meta information in gammapy.maps

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1250]
In order to keep track of a number of information regarding maps produced in the various analysis steps, we would need to add a number of informations to maps that should be written (or read) from a fits file (map type and related informations, ontime, etc ). Some history could be useful too. 

 Using meta data with a dictionary is a simple approach (e.g. in `~gammapy.spectrum.PHACountSpectrum`). 

Could a similar approach be applied to `~gammapy.maps`? Is it possible/desirable to add the possibility to read/write the meta dict from/to a fits file @cdeil @woodmd ?

**Comment by cdeil** [comment]
Short answer: I don't know. Hoping @woodmd or @adonath or you will propose something good.

FYI: The Fermi ST have this "data sub-space (DSS)" system (see https://confluence.slac.stanford.edu/display/ST/Data+SubSpace+keywords) that they use to store information and communicate between analysis steps. My understanding is that ctools inherited that, I don't know if they expanded it for IACT analysis or how well it really fits for IACT analysis.  My guess is that it covers the Fermi-LAT style analysis well, but then if you need complex background modeling with per-run background model parameters or 1-dim region-based spectral analysis or something like this you hit a wall and it becomes messy? Or maybe DSS can be a good starting point and then grow naturally to allow meta-data handling for other types of IACT analysis?
There was even a proposal once to use it in DL3 and to link HDUs (see https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/24). If that was used, we should use it in Gammapy as well, but for now there is no proposal really what to do for DL3, so we could prototype it in Gammapy or do something else.

In Astropy many classes have a `meta` attribute that's an OrderedDict, e.g. `NDData` (see http://docs.astropy.org/en/stable/nddata/nddata.html#meta-data) or `Table`. The previous Gammapy classes of `SkyImage` and `SkyCube` also had a `meta` dict, and it was used for FITS I/O. With the new maps classes, it's not quite as obvious what to do because there's already [MapGeom](http://docs.gammapy.org/dev/api/gammapy.maps.MapGeom.html) that stores the map geometry information (including the WCS which is a large part of the FITS header, but also energy axis or potentially time axis or other axis info).

In #1206 we already discussed where to store data unit and discussion leaned towards making this a separate data member on the map class. That is reasonable, that's e.g. what the `NDData` in astropy does as well. But unit could also be stored in `map.meta['unit']` or on `map.geometry` or `map.geometry.meta` if one wants to have all meta-data in `map.geometry`, instead of having it partially on `map` and partially on `map.geometry`.

This question of metadata handling from analysis code and in serialisation is very important, and unfortunately also very complex. I think any scheme we adopt will unfortunately not be very simple and obvious especially concerning FITS I/O (because of the split in some metadata, like WCS, probably also energy info, being special).

Maybe adding `map.meta` and extending MAP FITS I/O to handle this in addition to the current code that we already have would be reasonable? As far as I can see, whether `map.unit` is split out or in `map.meta['unit']` doesn't matter much concerning overall scheme / complexity.

**Comment by woodmd** [comment]
Adding a `meta` attribute to both map and geometry objects seems reasonable to me but the real work would be developing schema for those dictionaries.  Maybe that's something that someone could start sketching out in gamma-astro-data-formats.  As I suggested in #1206 my approach for serializing meta data would be to dump it to a json string and write that to a single FITS header keyword.  This avoids any issues with keyword collision and also removes the limitation on key length and case sensitivity.

Personally I'm not a big fan of the DSS system so I'm not sure if it's something we necessarily want to copy -- the DSS parsing and validation is quite complex and maintaining it on the STs side of things has been a pain.  The main difficulty arises in implementing the logic that evaluates whether cuts are "nested" -- if I apply cuts X and Y is it valid to apply cut Z?  For simple box cuts on energy and time this is fairly straightforward but once you start doing more complex selections or considering event classes and types the logic becomes much more complex.  Note that I think the STs only use the DSS for validation (although I'm not completely certain of this) so strictly they shouldn't be needed to generate files compatible with the STs.

**Comment by cdeil** [comment]
> Adding a meta attribute to both map and geometry objects seems reasonable to me 

It also seems reasonable to me. But I'm still not clear on what metadata goes where (map, geometry, or higher-level objects or code, e.g. some data structure that combines the data and response information for a given dataset), i.e. I wouldn't be surprised if we later realise it was a mistake.

> but the real work would be developing schema for those dictionaries.

> Personally I'm not a big fan of the DSS system so I'm not sure if it's something we necessarily want to copy

@registerrier - So should we start to develop our own metadata system? Or can / should we avoid that for now?

I guess in the proposal you are preparing for new code to make cubes and maps and compute effective PSF and EDISP, there is no reliance on metadata on the map (like e.g. energy range or bounds, or maximum FOV cut) yet, and instead higher-level code keeps that info and passes it repeatedly to calls that do computations on maps (e.g. fill counts, compute exposure, estimate background, ...)?

**Comment by cdeil** [comment]
Just a note, that we need to watch out and have some tests concerning what happens with `wcs` and `meta` and how they interact on read / write. This is a bit tricky and needs to be thought through. See #1274.

**Comment by cdeil** [comment]
@registerrier - Close issue? Or do you the discussion above or having the issue open is useful as a reminder for how to use `map.meta`?

**Comment by cdeil** [comment]
Closing this old issue now. Of course, metadata handling will remain a topic for the coming months, but I don't see any concrete task or action item here.
