### ISSUE TITLE
Eventlist energy plots are broken

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1258]
When doing 

```
events_from_file = EventList.read('/Users/mackaiver/gps/gps_baseline_112984.fits')
events_from_file.plot_energy_hist()
```

I get 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-15-89a8ab6c16b3> in <module>()
----> 1 events_from_file.plot_energy_hist()

~/Development/gammapy/gammapy/data/event_list.py in plot_energy_hist(self, ax, ebounds, **kwargs)
    536 
    537         if ebounds is None:
--> 538             emin = np.min(self['ENERGY'].quantity)
    539             emax = np.max(self['ENERGY'].quantity)
    540             ebounds = EnergyBounds.equal_log_spacing(emin, emax, 100)

TypeError: 'EventList' object is not subscriptable

```

**Comment by mackaiver** [comment]
BTW why is a thing called `SomethingList` not subscriptable. That seems like a design error.

**Comment by cdeil** [comment]
> TypeError: 'EventList' object is not subscriptable

This issue has been fixed in Gammapy master a while ago.

> BTW why is a thing called SomethingList not subscriptable. That seems like a design error.

What we have now is not so bad: an `EventList` is a thin wrapper around `Table`. It used to be a sub-class, but this was causing problems. Of course other designs are possible and renames of the class can be considered, but if we do it at all we should only do it once to avoid breaking many user scripts. A PR or issue or PIG with a suggestion for new event and GTI classes is welcome, but it really deserves a new thread.
