### ISSUE TITLE
Do we want things to plot themselves?

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1285]
My intuition would be to separate the display logic from the rest. 
One example would be the reading and displaying of effective areas using the `CTAPerf` object. 

Maybe we could even go as far as to say that displaying these things is not gammapys task at all.

In any case we should practice something  along the lines of Uncle Bobs 
[separation of concerns](https://8thlight.com/blog/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html) 

This kind of leads to a larger problem though doesn't it? An object called `CTAPerf` does not really model a real entity.  A 'dumb' class (called `IRF` or similar) which only contains the different tables and maybe some meta data makes more sense from an architectural standpoint. The class should not be able to calculate anything. If you want to calculate sensitivities you could have a sensitivity module and use it like this `sensitivity.calculate_from_irf(irf, required_sigma=5, observation_time=50*u.h)` . This makes it easier to adhere to the single responsibility principle as well as following the [liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

**Comment by cdeil** [comment]
For me there's two questions here that are separate:

1. whether to attach `plot` as methods to objects, or to separate it.
2. what to do with CTAPerf and some other [classes gammapy.scripts](http://docs.gammapy.org/dev/scripts/index.html#classes)

I'm +1 to keep `plot` methods attached to data classes in many cases. We mostly use that as a quick-look convenience, to plot a map, IRF, ... This is mostly useful if you explore some new data or look for issues with your data. Having separate plotting functions or classes makes it more cumbersome to use, many users will not even find the plotting functions then. Given that the plotting functions are just a convenience that's not called from other parts of the package, i.e. not really important overall, I don't think we have to be concerned in this case much with the things you mention like separation of concerns.

For CTAPerf and some of the other classes in gammapy.scripts, they are just small conveniences to load and plot something, that don't do much. They don't have great names and with `gammapy.scripts` aren't in a good location, so I think sooner or later we'll have to make a change there anyways. We should discuss on a case by case basis what to simply remove or move to docs examples, and what to refactor in some better way and if we can find a good place for this in Gammapy.

@jjlk - Assigning to you for now, since you wrote and I think are the main user of CTAPerf. Let's discuss this one and try to decide what to do later this week.

**Comment by cdeil** [comment]
I'm making a decision here.

In Gammapy, we keep the `plot` or `peek` methods on some objects, e.g. map or IRFs.

These are "peek" or "quick look" methods, just like `print(something)` should give a small text summary what the object contains.

The proposed alternative of separate plotter functions or classes is not as nice for users: it's much harder to discover than typing `something.<TAB>` in ipython / Jupyter,  and it actually gives more weight to these little plot helpers in our API, which I don't think is appropriate. Gammapy is mostly about analysis, and just a little bit for plotting.

I realise the quality and test coverage of the plot methods in Gammapy isn't great. Any pull request to improve or even a description of this policy in the dev docs is welcome.
