### ISSUE TITLE
Improve HGPS catalog spatial model

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1351]
I improved the HESS HGPS catalog code and tests in #1231 .

The main remaining thing I'm not happy with yet is the spatial model. This is a reminder issue to improve that.

- [ ] give access to source morphology from catalog table for all sources (i.e. the moment-based measures for multi-gauss). Probably via a choice string argument to the existing spatial_model method
- [x] once we have better source model classes, spatial and spectral should be separated, so that it is no longer necessary to give an energy band when asking for a spatial model.

**Comment by adonath** [comment]
The 2nd item has been implemented in  https://github.com/gammapy/gammapy/commit/99740667fa3cdbdf3d6b55d45cd26d0720414cae.

Concerning the first item: I'm not sure I would give access to the moment-based measures as a morphology model (a as single Gaussian), because it's misleading and unclear what to do with it.
It is not really an alternative morphology model for the source, because it hasn't been fit to the data.

Apart from these items, there are 2 remaining TODOs in the source code:

https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/hess.py#L522
https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/hess.py#L556

Both are easy to implement, I could do it for v0.10...
