### ISSUE TITLE
Tests fail in master locally

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1366]
[This](https://gist.github.com/joleroi/4eaaa91729cc0888f94ab121f71cb186) is the output of my local testing session in ``master``. There are several failures in ``gammapy.maps``. Should I expected them or can anyone point me to the problem @woodmd @adonath @registerrier ?

**Comment by cdeil** [comment]
There's really only one issue, and that's that we use
https://docs.scipy.org/doc/numpy/reference/generated/numpy.isin.html
which was only added in Numpy 1.13, and you have 1.12 locally.

This should have been caught by this build with Numpy 1.10:
https://github.com/gammapy/gammapy/blob/3f1441ac1488e53ecb2edbcca7bf135847eebdf2/.travis.yml#L132

We are even claiming to support Numpy 1.8+, but apparently don't have a CI build for that:
https://github.com/gammapy/gammapy/blob/3f1441ac1488e53ecb2edbcca7bf135847eebdf2/setup.py#L107

Fermipy says Numpy 1.6+ here:
https://github.com/fermiPy/fermipy/blob/1a8e726fbc5195224fa3b62ddad1678fae514dbe/setup.py#L81

@woodmd or @dimauromattia - What Numpy version do you need to support in Fermipy? Would bumping to `numpy >= 1.10` in the Gammapy `setup.py` be acceptable or a problem for you?

Concerning this specific issue: probably we should just rewrite those lines to avoid calling `numpy.isin`, no?

I'll wait for a reply here and then could do a PR tomorrow with whatever changes we decide to make.

**Comment by joleroi** [comment]
@cdeil Thanks for clarifying, I can obvioulsy just update numpy but others might run into the same issue

> There's really only one issue,

There's also this 
``` 
ImportError: No module named 'skimage'
```

**Comment by cdeil** [comment]
> ImportError: No module named 'skimage'

That must be because we have a missing `requires_dependency('skimage')` on those tests, I'll add that as well in the PR tomorrow.
We do have a CI build that runs tests if only numpy and astropy are available. But because of this all tests in that file are skipped in that CI build, so the missing `requires_dependency('skimage')` wasn't noticed.
https://github.com/gammapy/gammapy/blob/e5acaf5b1c31a3dac61b5603c5ced8426083f6f4/gammapy/maps/tests/test_wcsnd.py#L15

For you locally, you might want to install `scikit-image`, or really most / all of the optional dependencies for Gammapy, see printout in `gammapy info`.

**Comment by cdeil** [comment]
I added the missing `@requires_dependency('skimage')` in  748ebc06 in master.

**Comment by cdeil** [comment]
The reason this didn't show up in CI is that the build with Numpy 1.10 (https://travis-ci.org/gammapy/gammapy/jobs/364966089#L3434) skips the tests
```
gammapy/maps/tests/test_hpxmap.py::test_hpxmap_pad
gammapy/maps/tests/test_hpxmap.py::test_hpxmap_crop
```
due to
https://github.com/gammapy/gammapy/blob/748ebc067ebea3a60b603eea77d576c1e2edfeb3/gammapy/maps/tests/test_hpxmap.py#L18

So that part is understood and OK, no change needed.

**Comment by cdeil** [comment]
The only thing remaining here is the question whether to require Numpy >= 1.10 in `setup.py`.
I've opened #1404 for this; closing this issue now.

**Comment by joleroi** [comment]
FYI: locally I still see [this failure](https://gist.github.com/joleroi/a2d0db5284700e464aa3a4ab4ddb2ad0)

**Comment by cdeil** [comment]
@joleroi - This is a healpy bug that was fixed last year: 
https://github.com/healpy/healpy/issues/398

Can you update healpy for now?

Note that I plan to change to `astropy-healpix` (#1167) as soon, the two remaining blockers there are https://github.com/astropy/astropy-healpix/pull/71 and https://github.com/astropy/astropy-healpix/pull/77
