### ISSUE TITLE
Change Binder and tutorial docs to JupyterLab?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1409]
In February 2018 [JupyterLab](http://jupyterlab.readthedocs.io/) was announced to by ready for users (see [blog post](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906)). I think it'll be another half year or more until they release 1.0, but that's only because work on the API and extension system is ongoing, for end users JupyterLab is in a good state, and conda and pip install works fine.

@Bultako - Do you think we can / should change the Gammapy binder and `environment.yaml` from `jupyter notebook` to `jupyter lab` now? Or should we wait some more?

I'm +1 to change now already, but up to you.

**Comment by Bultako** [comment]
@cdeil 
I agree JupyterLab is the way to go.

I'll play with`environment.yml` file in `gammapy-extra` repo and fix the jupyter-links in the doc building in case of success.

**Comment by Bultako** [comment]
@cdeil 

We have a building a JupyterLab-Binder platform for the tutorials.
https://mybinder.org/v2/gh/gammapy/gammapy-extra/master?urlpath=lab

But... I do not have succeeded in associating a link to a specific notebook, so to open it directly from the static docs in JupyterLab-Binder. Fortunately, links to Standard-Binder notebooks from the static docs continue to work. 

With JupyterLab-Binder we have also the possibility to work in a Terminal inside this binder virtual env, as well as creating new files, etc. JupyterLab-Binder is more a virtual working space than a single executable notebook inside a browser (Standard-Binder).

Because with JupyterLab-Binder we can navigate in the terminal, we could access to all the content of the `gammapy-extra` GitHub repo. Good news is that we are free to decide the content of the binder virtual working space. 

My suggestion would be to change the links in the doc tutorials pointing to the JupyterLab-Binder working space, and also change the sentence. For example:

Try online [launch|binder] and the double-click on **first_steps.ipynb**

Thoughts?

**Comment by Bultako** [comment]
>> Is it possible to have a markdown file open on lab launch?

It would be nice, but I don't know how to do it :(
I make the PR then.

**Comment by cdeil** [comment]
How about adding a very small `notebooks/README.md`
with the link to http://docs.gammapy.org/dev/tutorials.html#notebooks for now?
Then it will appear in the file view on the left and many users will first click there.

**Comment by Bultako** [comment]
I think it's better a README.md file with links to the most important notebooks, maybe the same list as http://docs.gammapy.org/dev/tutorials.html#notebooks to start.
I'll check if it's possible.

The downside is that we will have to keep it up to date :(

**Comment by cdeil** [comment]
Yes, it's hard to maintain if duplicated. Linking to http://docs.gammapy.org/dev/tutorials.html#notebooks and maybe pointing out the getting started again is OK for now, no?

**Comment by cdeil** [comment]
I think what we have now is just fine. Closing this old issue.
@Bultako - Thanks for switching Binder to JupyterLab and in general taking care of this!
