### ISSUE TITLE
FluxPointEstimator is not documented

### ISSUE THREAD

**Issue by MaxNoe** [gammapy/gammapy#1427]
There are many different ways to compute Flux Points. Mostly different kinds of unfolding.

What is used in `FluxPointEstimator`?

**Comment by cdeil** [comment]
Currently there is only one method: "npred equals excess".

* First reco energy bins are chosen, and the data in those bins contribute to a given spectral point.
* A spectral model shape is assumed, all parameters except the norm are fixed
* A 1D amplitude fit is done, to find the amplitude so that npred equals excess.

This is a pretty common method, what Fermi-LAT and HESS are doing.
The nice thing is that flux points can be computed independently and are statistically independent.
But of course, the method has also drawbacks and other other common methods should be available in Gammapy.

**Comment by mackaiver** [comment]
Is there a reference we can put in the docs? Otherwise I can just copy and paste what you wrote up there to the docs?

> The nice thing is that flux points can be computed independently and are statistically independent.

Only as long as e_reco bins are uncorrelated no?

**Comment by cdeil** [comment]
I'm not aware of a good reference. Suggest to put a description in the docs.

Or maybe you could mention `4.11.4 Flux points` in
https://ui.adsabs.harvard.edu/#abs/2018A%26A...612A...1H
and say like it's what's used in Fermi-LAT and maybe refer to one of the Fermi-LAT catalog papers (e.g. https://ui.adsabs.harvard.edu/#abs/2015ApJS..218...23A) or to Fermipy (http://fermipy.readthedocs.io/en/latest/advanced/sed.html).

**Comment by mackaiver** [comment]
fixed in #1460
