### ISSUE TITLE
Unclear usage for MapMaker

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1459]
Hi,

The documentation for the MapMaker class is a bit sparse. Also maybe this functionality can go into a `from_obersvations` method on the Maps class.

**Comment by cdeil** [comment]
> The documentation for the MapMaker class is a bit sparse.

As a first step, I'd suggest to link from [here](http://docs.gammapy.org/dev/api/gammapy.cube.MapMaker.html) to [here](http://docs.gammapy.org/dev/notebooks/analysis_3d.html) in both directions.

> Also maybe this functionality can go into a from_obersvations method on the Maps class.

So far the idea was to keep `Maps` a simple container, and have algorithms on it in other code. This isn't true for event list fill, and now we're discussing if PSF apply should be moved on Maps.
My initial reaction is that we shouldn't couple the obs to maps via something like `maps.from_observations`, but leave that in higher-level code, i.e. the current separate MapMaker was a good idea IMO.

**Comment by mackaiver** [comment]
> but leave that in higher-level code, i.e. the current separate MapMaker was a good idea IMO.

I think the name is misleading. A `maker` which doesn't return anything is surprising to me. In fact the 'maker' object keeps some state. The name 'maker' implies that it's creating an object. Usually this is the task reserved for constructors or initializers.  I expected this to work like a builder or even like a factory. 

So I talked to @registerrier about this for a bit. So I think we could either rename/refactor it to work in a similar fashion to the 'stackers' we already have in the code. Because that's whats its acutally doing right? Or we can use a proper GoF [Builder Pattern](https://en.wikipedia.org/wiki/Builder_pattern)

**Comment by cdeil** [comment]
I think the pattern we use is this:
```
maker = Maker(...)
maker.run() . # a multi-step process, that's why it's not a function
# Maker doesn't return results, but has them available
maker.result1
maker.result2
```
I see simple alternatives like using many functions instead of grouping them on a maker class.
And also grouping the results in a dict and not storing it on the maker, but always letting the caller hang on to it.
Looking at the builder pattern link in your last comment, I don't really get it: three classes and the builder just dispatches set / get to another class.

Seems nonsense. I don't get it yet, sorry.

@mackaiver - Could you (or anyone else that was involved in the discussions) make a small code example like I did just now, or sent a PR refactoring the `MapMaker` to use a better pattern?

**Comment by mackaiver** [comment]
The point is this: A maker class (or builder or whatever) should have a 'make',  'build' or 'create' method which actually returns the object (objects) created. 

That's how some of the other 'maker classes' in gammapy also behave.  

The maker should not encourage access to the mutable intermediate objects.

**Comment by cdeil** [comment]
My suggestion would be to add `MapMaker.run` and put the equivalent of [IACTBasicImageEstimator.run](http://docs.gammapy.org/dev/api/gammapy.image.IACTBasicImageEstimator.html#gammapy.image.IACTBasicImageEstimator.run).
I would not suggest a complete restructure of `MapMaker` now, i.e. keep the current structure with the mutable data members.
This will be nice for users, and also provide an API that takes `ObservationList`, i.e. one step to decouple high-level code form the `DataStore`.

@AtreyeeS or @mackaiver - Interested to send a PR for this today?
If no, I can do it tonight or tomorrow morning.

Then after v0.8, in the coming months, we can review and improve all the "maker" classes in Gammapy. We can have a Gammapy dev call focused on that.

**Comment by AtreyeeS** [comment]
Hello @cdeil, @mackaiver  : Are you working on `MapMaker.run` ? If not, I can do it now.

**Comment by cdeil** [comment]
@AtreyeeS - Please go ahead. Assigning this issue to you.

**Comment by cdeil** [comment]
@AtreyeeS - Another thing I noticed is that the `MapMaker` has a `count_map` (without s), but in most other places in Gammapy I think we have it with s, e.g. here:
http://docs.gammapy.org/dev/api/gammapy.cube.make_map_counts.html
Could you please change the map name to `counts_map` on the MapMaker?

**Comment by AtreyeeS** [comment]
Sure!
I am adding a MapList class similar to the `SkyImageList` (http://docs.gammapy.org/dev/api/gammapy.image.SkyImageList.html#gammapy.image.SkyImageList).

**Comment by cdeil** [comment]
@AtreyeeS - Please don't add a `MapList` class.

Let's just use dicts for now to hold multiple objects.

If you or @adonath or others feel that we should re-introduce such convenience classes as `MapList`, it can be discussed in the future. But for now, I want us to keep it simple.
Note that I myself added such classes to Gammapy in the past, e.g. a SkyCubeImageList that translates back and forth between cube and lists of images.
Turned out it's not needed, and using it in few places makes things inconsistent with the rest of Gammapy.

Examples:
- https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/analysis_3d.ipynb#Save-maps
- http://docs.gammapy.org/dev/_modules/gammapy/detect/lima.html#compute_lima_image

**Comment by AtreyeeS** [comment]
Thanks for this input!
This opinion is exactly what I wanted!

Will write accordingly!

**Comment by cdeil** [comment]
Improved in #1459 .
Closing this issue now.

Of course, more PRs to improve the maps code and MapMaker are welcome any time!
