### ISSUE TITLE
Deprecate SkyImage

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1485]
Add deprecated flag to this. 

https://github.com/gammapy/gammapy/blob/26df297191166ad1efc779bda3b9a97881f77db9/gammapy/image/core.py#L66

**Comment by mackaiver** [comment]
Also this is deprecated if I understood correctly

https://github.com/gammapy/gammapy/blob/a861a63af8f56cb3732e88b81c961a25716b4b74/gammapy/image/basic.py#L25

**Comment by cdeil** [comment]
We did a "soft deprecation" for this already a few months ago:

https://github.com/gammapy/gammapy/blob/11ec6f308a34435bfa7379bc71c7cb6d9d8e616e/gammapy/image/core.py#L41-L46

Also explained in the v0.7 release notes:
https://github.com/gammapy/gammapy/blame/master/CHANGES.rst#L108-L119

I would like everyone to replace use of SkyImage with Map (e.g. in gammapy.detect).
But I would prefer not to spend more time on adding warnings or other ways to deprecate to the exiting code. IMO emitting deprecation warnings at this time where it's still used is just annoying users.
So I'm closing this issue now, nothing further to do to deprecate for now IMO.

**Comment by mackaiver** [comment]
> I would like everyone to replace use of SkyImage with Map (e.g. in gammapy.detect).

And how are user supposed to know that? 
Add a FutureWarning printing that statement.

**Comment by MaxNoe** [comment]
GammaPy is still in early development, it is not that widely used and it has a < 1.0 version number.

If there is stuff you want people to not use anymore, remove it.

**Comment by cdeil** [comment]
> And how are users supposed to know that?
> Add a FutureWarning printing that statement.

@mackaiver - We had the v0.7 release and did the soft deprecation via docs and changes to mention that users should transition to Maps. My preference would be that the transition is very far along for v0.8 and e.g. the BasicImageEstimator is removed next week. That's why I don't want to spend time adding lines that emit FutureWarnings in all the right places.

Also please note our development status:

https://github.com/gammapy/gammapy/blob/a45527c7abbb96fdaa63166044e61996813803a1/setup.py#L148

**Comment by mackaiver** [comment]
👍 for simply removing deprecated things.

**Comment by MaxNoe** [comment]
> 'Development Status :: 3 - Alpha', 

Exactly. That means that just breaking stuff is ok.

**Comment by cdeil** [comment]
> 👍 for simply removing deprecated things.

What I'm doing is to remove as soon as the same functionality is available in a better way.
Since we made good progress on maps analysis this week, e.g. the IACTBasicImageEstimator can go next week.
Since I know (and have authored) a lot of the old code, that cleanup is best done by me and other people like Axel that have been around for the past years.
