### ISSUE TITLE
scikit-image dependency 

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gammapy#1494]
In the downsample method in maps>wcsnd.py import skyimage from the scikit-image. 
Do we really want this dependency? If so, it should be included in the installation instructions

**Comment by registerrier** [comment]
A priori, scikit-image is one of our dependencies. It appears the environment.yml file.  So it should be OK as is. Do you have an issue with this dependency?

There is apparently also a a block_reduce function in astropy. I don't know if they can be substituted  one with the other. Opinion @cdeil ?

**Comment by adonath** [comment]
@registerrier The `block_reduce` in Astropy requires `scikit-image` as well ([see here](https://github.com/astropy/astropy/blob/4cc41d398d85a7cb9610dec0736f011349c75c87/astropy/nddata/utils.py#L389)). So this does not make a difference. The policiy in Gammapy is that `sscikit-image` is an optional dependency.  If user want to use the functionality they have to install the package. I guess this should be better documented.

**Comment by cdeil** [comment]
Given that number of dependencies is a factor in the CTA ST selection, and that we only use one relatively simple function from scikit-image in one place, I would suggest that we just re-write that utility function ourselves to completely get rid of the scikit-image dependency.

The argument that Gammapy is interoperable with the scientific Python stack and scikit-image, scikit-learn, ... because we use Numpy arrays remains.

The function is [skimage.measure.block_reduce](http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.block_reduce) and it's used here:
https://github.com/gammapy/gammapy/blob/10834539391fd7e13d72b570b3369e7ed5413dd6/gammapy/maps/wcsnd.py#L461

It should be possible to rewrite this with ~ 10 lines of Numpy ourselves (just what we need), or to copy the `block_reduce` function over and if needed also [skimage.util.view_as_blocks](http://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.view_as_blocks).

I'm putting this on the v0.9 milestone, let's focus on getting 3D analysis to run and v0.8 this week first.

**Comment by cdeil** [comment]
I plan to replace the call to scikit-image with a bundled utility function next week, moving this to the v0.8 milestone.

**Comment by cdeil** [comment]
I'm doing this in #1658 . Closing.
