### ISSUE TITLE
Livetime correction using GTI ? 

### ISSUE THREAD

**Issue by tony32lin** [gammapy/gammapy#1504]
We have been testing VERITAS DL3 files with GTI table with gaps ( due to weather, hardware ... etc) and found that the livetime isn't based on GTI in gammapy at the moment. Is there any plan to change this ?

**Comment by cdeil** [comment]
@tony32lin - Yes, we do plan to change Gammapy to use GTIs and use that for livetime computation.
Currently it's read from the EVENTS header keyword and GTI isn't used in Gammapy, because in HESS we only had one contiguous GTI per OBS_ID (and just throw away the few runs where a part in the middle is bad).

There is some thoughts in #1451 and this week we discussed this with @dcfidalgo and @joleroi . It'll take a bit, but this is coming in Gammapy. Keeping this issue open as a reminder for now.

**Comment by cdeil** [comment]
Resolved by @dcfidalgo in #1908 .
