### ISSUE TITLE
Possibility of having "extra" functionalities for gammapy

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1548]
It seems to me that we are often having cases which would be nice for users to have, but painful for developers to maintain (eg: the profile plot in #1543 or options to simulate date with real background #1330)
These can be worth 10-15 lines of code I guess, so I was wondering if we can have an "extra" repository with a few functionalities, which doesn't go into the main gammapy repo? I am thinking along the fermi user contributed tools feature, but just that its both developers and users who put in some usefuls functions here...

I am not sure if this is a good idea at all, so @cdeil  @adonath  @registerrier @joleroi @facero ... Thoughts?

**Comment by registerrier** [comment]
We definitely need a place for specific but non core functionalities if we want to keep gammapy lean. Maybe contributed is a good choice.

**Comment by cdeil** [comment]
@AtreyeeS - Good point.

I agree that we basically want this, but how to set it up needs a lot of thought and discussion.

This will need a PIG. If someone wants to start writing it, great, and then we can discuss it at the fall Gammapy meeting. For now my preference would be that everyone with time helps to build the Gammapy core functionality, there's still so much to do.

Even a `contrib` needs maintenance to be useful, or it will become a messy pool of low-quality, often broken code over the years. Then the question is whether to have `gammapy.contrib` in the main repo or a second repo. One issue / PR or two? ...

Note that we have the [examples](https://github.com/gammapy/gammapy/tree/master/examples) folder and the `gammapy-extra` repo, so there are places where people can share stuff already.

**Comment by adonath** [comment]
@AtreyeeS I also think this a very good suggestion!

I'm not sure if it should even be a separate repository or sub-module of Gammapy, because then we somehow commit to maintain the code. In it's simplest realisation it could be just a docs page, where people can link to their projects, interesting analyses or useful code snippets using Gammapy.

**Comment by joleroi** [comment]
A good example for this are the ``CTAPerf`` and CTAIrf`` classes we currently have in gammapy.scripts. When updating the ``cta_simulation`` notebook I also felt that it might be usefull to somehow keep these classes to avoid that everyone has to write the same 10 lines of wrapper code again. 

Spontaneously I would think that notebooks are a good way to share this, but I agree that this is quite a large maintainance effort.

**Comment by cdeil** [comment]
> A good example for this are the CTAPerf and CTAIrfclasses we currently have in gammapy.scripts. 

I think the new data / obs classes will contain a convenience to load the four IRFs for an obs, see the `Observation` class here: #1546

The other classes there are really useless, just a remnant of preliminary formats / discussion / checks concerning IRF formats.

We should support all CTA IRFs moving forward directly in Gammapy.

> notebooks are a good way to share this

Notebooks are nice for docs examples and to copy & paste from.
But they have huge drawbacks: can't import from there, very hard to test and maintain.
From that perspective, as soon as you write functions or classes that have some re-usability, they should be in `.py` files IMO.

**Comment by cdeil** [comment]
Thinking about this some more: I think it will be very hard to decide this already in the coming months.
We are proposing Gammapy as CTA ST to CTAO, and basically should set up Gammapy in a way to make this possible. That requires extensive discussion with CTAO and ctapipe about what goes where, and how things are reviewed and maintained. These discussions will only start in the fall.

So @AtreyeeS - if you want to try and make progress on this, OK. But I'd suggest you don't spend much time on it, i.e. just write a PIG with an abstract, a few lines what you propose. (e.g. `gammapy.contrib` or put stuff in `gammapy/examples` or put it in `gammapy-extra` or just add docs examples and add links to other repos with useful code using Gammapy from the docs)

**Comment by cdeil** [comment]
We have 153 open issues and our issue tracker isn't useful any more, I'm closing this old issue and will try to close out ~ 30 others as well that I've been involved in in the next days.

Concerning extra functionality: anyone can share code on Github or anywhere. Pull requests linking to other relevant projects from the Gammapy docs to advertise them and make them discovarable are welcome any time!  (we already have [this](https://docs.gammapy.org/0.14/references.html#other-gamma-ray-packages).) A PIG to propose a bitter solution like a new repo or solution for user-contributed code is also welcome any time in the future.

My strong recommendation is to focus for another few years on the core Gammapy package (and other maintained packages like PINT for pulsars, ...), and to only maintain a link collection to other codes, since Gammapy isn't stable yet and we don't have the manpower to maintain user-contributed code, and a collection of broken scripts is not a service to users.
