### ISSUE TITLE
Support different map energy binnings in MapMaker

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1583]
This is a follow-up issue for #1579 and #1580 by @AtreyeeS that weren't merged.

The question is whether to support different energy binnings for different maps in `MapMaker`. 

Currently all maps (counts, exposure, background) have the same energy binning. The counts and exposure have a reco energy axis, and the exposure has a true energy axis, exposure combined with EDISP is not supported yet. Since #1558 we integrate background in the power-law approximation, using nodes at the energy bin boundaries (this number of nodes option not re-exposed on the Mapmaker, which I think is OK); for exposure we just evaluate at the energy bin centers, the user has no way to control precision except to choose not too large energy bins.

I'm not sure if it will be commonly used, but I'm +1 to add a `energy_true=None` config argument to MapMaker. By default, `energy_true = energy_reco` is used and `energy_reco` is taken from the geom (which defines the counts geom, with a reco energy axis). If the user wants a different `energy_true`, they can pass a quantity. That's pretty similar to how the user can choose any `energy_true` and `energy_reco` binning they like in [gammapy.spectrum.SpectrumExtraction](http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumExtraction.html).

@AtreyeeS @registerrier @leajouvin @adonath - Thoughts?

**Comment by JouvinLea** [comment]
I agree that clearly MapMaker should handle the maps computation on different energy binning. Background and counts are in reco energy and exposure, PSF and edisp in true energy. Since for the moment the energy resolution is not taken into account in the 3d analysis, it was not necessary but it will be important. Maybe we can add this etrue=none by default or we just have one axis name energy and in the docstring you precise if it's reco or true energy. 

Or we call it etrue whatever the case and by default etrue=ereco? I will be in favour of this one!

**Comment by registerrier** [comment]
An energy_true vector/axis is clearly needed to create the relevant maps. 

Note BTW that a different `MapGeom` for energy_true could be a valid possibility too. Because of ROI sizes and contamination, one might be forced to model the true sky on a larger space region than the observed one. 

Also, for computation efficiency, it is obvious we don't need to compute reprojected IRFs on a very fine binning (e.g. 0.01°) when the IRF are sampled on a grid 10-50 times less precise. It would be MUCH more efficient to compute exposure and background maps on maps 10 times less precise than the counts maps and at the end of the process interpolate the average map to sample it on the final binning. We might therefore also pass an oversample argument to the `MapMaker` to compute the reduced IRFs.

**Comment by registerrier** [comment]
Yes, this definitely should go to v0.9. It is a nice to have feature for efficient memory and computing time usage but this is not required now. And I agree that it will take time to find the best way to deal with multiple `MapGeom`.

I would have expected the reprojection/interpolation to be best at the `MapFit` level, so that the users do not need to store large maps. Having the possibility to store them at full resolution might be important though if the users want to do the modeling/fitting with other tools.

**Comment by AtreyeeS** [comment]
Done in #1846
