### ISSUE TITLE
Exporting maps produced by MapMaker to disk 

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1596]
We need to be able to export the counts, exposure, background maps before the fitting step. Running the map extraction each time we play with the fit is obviously not the way to proceed.

Rather than reintroducing the equivalent of the `SkyImageList`, I would suggest to agree on an internal (at least for the moment) naming scheme for the HDUs to define the maps required for basic cube-style analysis, e.g. counts, exposure, background and add a `MapMaker.write()` or `export`method to save the results on disk.

A convenience function could then be added to read the results back to disk and feed them to the `MapFit`. 

Opinions @cdeil, @adonath ?

**Comment by adonath** [comment]
I think the I/O functionality should not be coupled to the `Maker` or `Estimator` class because then we implement the same functionality in many places and it gets hard to remove as soon as we have another solution. As we have mostly replaced the `SkyImageList` by `dict` or `OrderedDict`, I think the short term solution is to introduce two little helper functions `write_maps_dict()` and `read_maps_dict()` in `gammapy.maps.utils` to write and read a dict of `Map` objects to a fits file. This can be used in many places e.g. for the `TSMapEstimator` and `ASmooth` as well. Later we can introduce an equivalent to the `SkyImageList` again.

**Comment by cdeil** [comment]
@registerrier - Is **is** of course possible to save the maps after producing them and read them back before likelihood fitting. I added this to the docs example last week:
http://docs.gammapy.org/dev/notebooks/analysis_3d.html#Save-maps
```
# Write
path = Path('analysis_3d')
path.mkdir(exist_ok=True)
maps['counts'].write(str(path / 'counts.fits'), overwrite=True)
maps['background'].write(str(path / 'background.fits'), overwrite=True)
maps['exposure'].write(str(path / 'exposure.fits'), overwrite=True)
psf_kernel.write(str(path / 'psf.fits'), overwrite=True)
edisp.write(str(path / 'edisp.fits'), overwrite=True)
```
and 
```
# Read
maps = {
    'counts': Map.read(str(path / 'counts.fits')),
    'background': Map.read(str(path / 'background.fits')),
    'exposure': Map.read(str(path / 'exposure.fits')),
}
psf_kernel = PSFKernel.read(str(path / 'psf.fits'))
edisp = EnergyDispersion.read(str(path / 'edisp.fits'))
```

Writing to a single file and reading from there is possible, but it's a bit hairy because our maps sometimes have two HDUs. Fermi-LAT ST also don't do that. So for now I'd suggest sub-folders with files and the names shown here. This also has the advantage that one can compute different maps separately and update them in a given folder more easily.

I'm not sure introducing helper functions or classes to do this I/O will help much. 
If you do add something, my suggestion would be a `MapMaker.write(path)` method which does what the lines above do.
Note that for reading into dicts, you can even do one-liner dict comprehensions if the names are simple:
```
maps = {name: Map.read(str(path / f'{name}.fits')) for name in ['counts', 'background', 'exposure']}
```

**Comment by cdeil** [comment]
I'll make a PR for this today.

**Comment by cdeil** [comment]
I presume `gammapy.maps.utils.write_maps_dict` would do this?
```
def write_maps_dict(maps, path, overwrite=False):
    Path(path).mkdir(exist_ok=True, parents=True)
    for name, map in maps.items():
        map.write(Path(path) / f'{name}.fits'), overwrite=overwrite)
```
I'm -1 to introduce that. Note that it's just 3 lines, and already the mkdir options on the first one aren't re-exposed to the user, because it would get too complex.

Suggest to just close this issue and just refer people that ask about this to an example like http://docs.gammapy.org/dev/notebooks/analysis_3d.html#Save-maps .

@adonath @registerrier - OK?

If you really want a convenience for this, please send a PR tomorrow.

**Comment by adonath** [comment]
I'm :-1 to introduce a `MapMAker.write()` method, so I guess the compromise is what you suggest, to leave it up to the user and show an example how to do it with three lines of code. So I'm fine to resolve this issue with a docs example.
