### ISSUE TITLE
How to select energy and spatial range for 3D map fit?

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1633]
The user can wish to test different fitting Region of Interest and different energy range during the 3D analysis fit, and this without re-making the cubes.
A nice user interface could be added (to MapFit??) to set the RoI and Erange to all cubes and IRFs used for the fit.
Thanks in advance!

**Comment by registerrier** [comment]
I think that generally the philosophy we need to follow is that data reduction and modeling/fitting are distinct steps. So we should not rely on a modification of the data products such as maps.

Instead, we should use masks to compute n_pred on a limited set of 3D points in the cube. This can be done typically with a mask and this offers the maximal flexibility (e.g. if you want to remove a source from the fit).

The issue is that there are 2 distinct spaces, true and reco. Restricting the fit to a region in _reco_ space does not mean the model has to be evaluated on the same _true_ space. 

As a general rule, I would tend to consider that in terms of energy _true_ we probably have to keep everything. For the spatial dimensions, we can probably safely assume that _reco_ and _true_ are the same.

So we should have at least a way to not compute n_pred on some reco_energy range (or to discard those values), and we should be able to pass a spatial mask (possibly energy dependent), to limit model evaluation on the relevant points only.

**Comment by cdeil** [comment]
@registerrier - OK.  But what you describe is for v0.9, those are deep changes in the model evaluation.

For v0.8, we only have a few days left, and need to fix bugs and make things possible in the first place.

This morning I showed how one can do a spatial cutout before fitting:
http://docs.gammapy.org/dev/notebooks/analysis_3d.html#Cutout
That reduced the fit from 20 min to 20 seconds.

I will add an example there showing also how once can slice out only some energy bins today.
I can also show how to multiply with a mask to select only pixels you want to model.

After that, I'll move this to the v0.9 milestone. Adding this to the MapFit and MapEvaluator interface should not be done in a haste, it needs some thought and discussion, and then a few days of work.

**Comment by cdeil** [comment]
Done by @adonath in #1702 .
