### ISSUE TITLE
Declare version numbers in environment YAML file?

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1725]
I have the feeling that from time to time we must face backwards incompatibility issues related with `gammapy` dependencies. i.e. https://github.com/gammapy/gammapy/issues/1714 https://github.com/gammapy/gammapy/issues/139 https://github.com/gammapy/gammapy/issues/1555. I still remember the nightmare when `matplotlib` upgraded to v2.

We could greatly improve reproducibility if we fix in `gammapy/environment-dev.yml`and  `gammapy-extra/environment.yml` the version numbers of the dependency packages used. - at least for stable version tags. As I see it, these YAML files may be used to set-up a specific environments when recovering a stable version of `gammapy` and avoid backwards incompatibility issues related with `gammapy` dependencies.  

Recovering the snapshot of the environment used at a very specific moment will provide the same behavior of `gammapy` functionalities i.e. in the notebooks.  But... at the same time this will also prevent using (outside `gammapy`) recent functionalities of some of the dependency packages i.e. astropy, numpy, matplotlib..

Moreover, if we move the `notebooks` folder from `gammapy-extra` to `gammapy` repo (as it proposed in PIG https://github.com/gammapy/gammapy/pull/1419), we will need this YAML file to create virtual environments in Binder. Those virtual envs, also tagged with version numbers, have to be very clearly determined so that we can exactly reproduce the behavior of the tutorials published for each stable release. 

I think what we gain is more that what we lose, but maybe I am missing something..

**Comment by cdeil** [comment]
@Bultako - Do you have time Friday morning to discuss a bit? (see https://github.com/gammapy/gammapy-meetings/tree/master/2018-08-24)

Briefly: for users, yes, we want envs with a known good set of package versions. We should make one for every release, e.g. for Gammapy v0.8 the default should be Python 3.6, Numpy 1.15, Astropy 3.0, basically a recent stable and good version of the dependencies (but not very recent, like Python 3.7).
I'm not sure when / where we would create that and advertise it to users. It might be better to have this in a separate repo (e.g. the existing `gammapy-docs`), so that we can edit it after cutting a Gammapy release, or in case an issue is discovered.

For devs, I'd leave as-is. We actually want devs to notice and be bothered by such issues, and aim to write code in Gammapy that works across a wide range of versions. Overall this will get better over time as Gammapy matures, it's only now that we have such rapid development speed and some of our dependencies are still changing (like astropy-regions or iminuit). I think in a year or two things will have settled down a lot. For devs that find this annoying and distracting, they could just use the env from the last stable release, and there make one change to update Gammapy to the latest dev version.

@adonath and @Bultako - Thoughts?

**Comment by Bultako** [comment]
>Do you have time Friday morning to discuss a bit? 

not this Friday, but next one 👍

**Comment by Bultako** [comment]
I have realized that dependencies are also declared in *install_requires* section of `setup.py`

https://github.com/gammapy/gammapy/blob/96707079e30451b2a453a5ac3f65b176bf72aaf6/setup.py#L106

For the moment, and as agreed, I will only declare the exact versions of dependencies in an `environment.yml` file, though I leave this comment here for discussion.

**Comment by cdeil** [comment]
I'm closing this in favour of #1828 which already has a lot of discussion.

Concerning version pinning in setup.py, as discussed in our last call, I would prefer not to, because Gammapy is really compatible with a large range of versions, and at least devs need to install and test those.

As discussed, I made one small change, requiring `regions >= 0.3` in `setup.py`: 07dc130f
