### ISSUE TITLE
Add execute and black for notebooks

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1756]
@Bultako - It would be great if it were simple to "refresh" and "format" our notebooks in a simple way.

We have
```
make docs
```
to build the docs and
```
make black
```
to format the Gammapy code.

It would be nice to have something like
```
make notebooks-execute
```
and
```
make notebooks-black
```
or a Python script to do it.

We already have `make test-notebooks` and `test_notebooks.py`, maybe that could be changed a little bit to support those extra use cases of executing in-place (I think it does that already?) and running black code formatting on the code cells.

For black I've asked here if that exists already:
https://github.com/ambv/black/issues/298#issuecomment-417215668
but maybe it's just a few lines to loop over code input cells and maybe black has a function you can call to format text directly, i.e. string in and string out?

At the moment I usually go through notebooks one by one and re-execute them, and that's becoming annoying / time-consuming.

**Comment by Bultako** [comment]
@cdeil 

I have made a first version of a `black_notebooks.py`script, we can iterate during the PR revision to achieve a final version of the script if you wish.

Because you mention `test_notebooks.py`, I agree we could integrate both functionalities in the same script. But I have preferred to do it in a separate script, since we still have a not resolved PR regarding `test_notebooks.py` https://github.com/gammapy/gammapy/pull/1365#issuecomment-411123738

**Comment by cdeil** [comment]
Done in https://github.com/gammapy/gammapy-extra/pull/118 .
