### ISSUE TITLE
Notebook astropy_introduction broken

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1774]
<pre>
INFO:gammapy.scripts.jupyter:   ... TESTING /Users/jer/git/gammapy-extra/notebooks/astropy_introduction.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.16 mn
INFO:gammapy.scripts.jupyter:   ... FAILED /Users/jer/git/gammapy-extra/notebooks/astropy_introduction.ipynb
INFO:gammapy.scripts.jupyter:

TypeError in cell [35]

--SOURCE CODE: 
in_region = circle_region.contains(coord)

--TRACEBACK: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-9e9b9190ae23> in <module>()
----> 1 in_region = circle_region.contains(coord)

TypeError: contains() missing 1 required positional argument: 'wcs'
</pre>

**Comment by cdeil** [comment]
Sky regions no longer have a contains, because in general (e.g. for rectangles) it's not well-defined what that is. So a meaningful example for using regions would have to involve a Gammapy Map object.

My suggestion would be to for now just delete the "using regions" section from the astropy introduction: http://docs.gammapy.org/dev/notebooks/astropy_introduction.html#Using-regions
And then later we can add more maps docs that includes examples with regions.

@adonath - Thoughts?

**Comment by adonath** [comment]
As suggested by @cdeil I removed the section, because there was no `WCS` object involved in the example, so it became useless. Done in https://github.com/gammapy/gammapy-extra/commit/9a5555ef116bd72a52330e658489551c80e3a294.
