### ISSUE TITLE
Unify API of Gammapy Fit objects

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1783]
We have three fit objects in Gammapy `MapFit`, `SpectrumFit` and `FluxPointFitter`. Currently all of the three behave in a different way and have very inconsistent APIs: 

- `MapFit` modifies the input model. The `.fit()` method does not return anything but modifies the state of the fit object. The `Minuit` object is accessible via `MapFit.minuit` after the`.fit()` method has been called.  

- `SpectrumFit`modifies the input model, but returns a copy of the best fit model stored in a `SpectrumFitResult` object. The result object can be accessed by `SpectrumFit.result` after the `.fit()`
method has been called. The `Minuit` object is accessible via `SpectrumFit._iminuit_fit` after the `.fit()` has been called.

- `FluxPointFitter` does not modify the input model and makes a copy, returns an `OrderedDict` result object in the `.run()` method. It returns the best fit model only in the`.fit()` method. The `Minuit` object is accessible via `FluxPointFitter._minuit` after the `.fit()` method has been called.

In an offline discussion @cdeil and I agreed to make the following changes to make the API more consistent:

- `FluxPointFitter` should be renamed to `FluxPointFit` and take the `data` and `model` on init.
- All fitter objects should make a copy of the model input model to create a model, that is owned by the fitter and can be modified by the `Minuit` object.
- All fitter objects should have a `.run()` as well as `.fit()` method, that return a result object. A dict `opts_minuit` is passed to the methods optionally. For `MapFit` and `FluxPointFit` it will be `dict` for `SpectrumFit` a `SpectrumFitResult` object (or a list of those...). The result object also contains a copy of the best fit model.
- The `Minuit` object will be accessible as a private `_minuit` object only on all fitter objects.
- For efficiency the `SkyDiffuseCube` get's a custom `.copy()` method to avoid the copy of the diffuse model data.

**Comment by cdeil** [comment]
+1 to this change, even if it comes late before v0.8 and still will not yield the final solution, it's a big step and I think in the right direction. Overall the code changes aren't huge, so I think it's doable in a day.

Just to note where this is coming from: besides the issue that the API of each Fit class is currently different and this creates confusion, there's also the following problem that @labsaha ran into today: when running SpectrumFit and calling `fit`, everything is fine. The input model has updated parameters, and there is also `fit.results[0].model` as another version to get the fit result besides checking the input model parameters after the fit. But then when calling `fit._iminuit_fit.draw_mncontour`, the input model parameters change, and that is very confusing. The reason is that the fit class and also minuit still holds a reference to the input model and parameters object, and `draw_mncontour` will evaluate the likelihood, which will update parameter values in-place.

So making a copy of the model on input is a way to create a model instance that is owned by the "fit" object (and if using the iminuit backend also linked to the "minuit" object), decoupling from the input model.

And making another copy of the best-fit model is a way to have the fit result object decoupled from the fit object, so that if someone does `fit._iminuit_fit.draw_mncontour` later, the best-fit result model will remain unchanged.

Of course, having three copies of the model also has potential for confusion and problems. But overall @adonath and I felt that making these copies would give an overall easier to understand and less error-prone experience for users, and also allow us to make more changes in the way the Fit objects work without affecting the inputs or results outputs in the coming months.

The other major potential issue with making the copies is of course performance. But making a model copy not fully deep, i.e. not copying Numpy arrays of diffuse maps on diffuse model copy, making model copies should always be fast and also cheap memory-wise. I also see little room for user error here, basically one would have to modify `diffuse_model.map.data` in-place on one of the copies and expect the `diffuse_model.map.data` on other copies to remain unchanged.

@registerrier @joleroi @facero   - thoughts?

(probably @adonath will just go ahead and make this change tomorrow even without your feedback, but this will be an open discussion point for Gammapy modeling for the coming weeks for sure, so even after this change feedback is welcome)

**Comment by registerrier** [comment]
This sounds very reasonable to me.
 I am not sure that `FluxPointFit` has to follow the same logic though. There is no use case for a user to access the `Minuit` object in that case, is there?

**Comment by cdeil** [comment]
I think the desire or need to access `Minuit` is the same for any fit, whether flux points or map or whatever no? E.g. one would call minos to compute asymmetric errors, something we don't expose yet; or one would compute 2D profile likelihood contours.

Long-term, we would aim to re-build everything in `gammapy.utils.fitting` (or split that part out from Gammapy to collaborate with others if there is interest for a "scikit-fitting" that does something like this and only keep a copy bundled), and `iminuit` would become a real backend the users never access.

Just to note: "scikit-fitting" doesn't exist yet, but I think someone will make it. And also `iminuit` with this heavy Minuit2 C++ dependency is pretty rediculous. It could be rewritten in a few 100 lines of pure Python / Numpy and even better optimisers and error estimators could be written in Python. This is happening in Julia, and I'm pretty sure that it'll happen in Python soon and then probably we'll just use that (and probably bundle a copy to avoid the discussions about having dependencies).

**Comment by cdeil** [comment]
@adonath - Close or OK to move to v0.9?

**Comment by adonath** [comment]
Resolved by #1937.
