### ISSUE TITLE
DataStore.from_files: look for files in base_dir?

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#1790]
`DataStore.from_files` has three arguments: `base_dir`, `hdu_table_filename`, `obs_table_filename`. Based on the naming of these, my naive assumption would be that the function looks for the files `hdu_table_filename` and `obs_table_filename` in `base_dir`. However, currently, `hdu_table_filename` and `obs_table_filename` really need to specify the full _paths_ to the files, and `base_dir` is simply written into the metadata of the created HDU table.

I suggest to have the function at least look for the files in `base_dir` if they are not given as full paths. If this is not desired, I'd vote for renaming (and possibly reordering) the arguments.

I can make a PR, but would like to hear some opinions before I implement something.

**Comment by adonath** [comment]
@lmohrmann I agree the `base_dir` argument in the `from_files()` method is not very intuitive and in the current implementation does not provide much useful convenience to the user. My suggestion here would even be to rename the current `.from_files()` method to `.from_dir()` and deprecate (or remove) the old `.from_dir()` method. If no filenames are provided in the new `.from_dir()` method, then the default filenames are used. This change is backwards compatible, but allows the user to specify different hdu and obs table filenames.

**Comment by cdeil** [comment]
I'm not sure what to do here.

One aspect is that this DataStore and index files will likely be replaced by something better within the next year. So that's one argument for leaving everything as-is, and to just add a sentence and example to the docstring to clarify what is currently done:
http://docs.gammapy.org/dev/api/gammapy.data.DataStore.html#gammapy.data.DataStore.from_files

On the other hand, this is the first time I hear someone is calling `from_files`, I think almost everyone is using currently `from_dir`, or some experts `__init__` directly. Since the `from_files` API isn't great (e.g. it doesn't use the recommended HDU names like `HDU_INDEX` or offer an option to specify the HDU), we could also just delete it. And while we're at it, delete `from_config` as well, which also probably has zero or almost zero users.

Instead of modifying `from_dir`, we could also add a new `read` method which does the best job of taking one `path`, and then auto-finding the index files. I.e. `Path.is_dir` and if so look for recommended file and HDU names etc. Realistically I think the two main ways people want to use index files is to either:

a) Have them in separate FITS files in a given folder (-> current from_dir perfectly fine)
b) Have the index files with all data in a single FITS file (-> currently not supported well at all by a single DataStore.from_something call, requires extra imports)

@lmohrmann @adonath and anyone interested - what's your final recommendation here?

Personally I'm not sure what is best here. Maybe remove the current `from_files` and `from_config`, leave `from_dir` as-is, and add one new method `read` that supports use case b) well, by looking for the recommended HDU names?

We could then briefly discuss this in the gammapy call tomorrow and make the decision together.

**Comment by lmohrmann** [comment]
I happen to have several different index files in the same directory (with different linked background models), so I'd appreciate a solution that allows me to init the DataStore by specifying non-standard filenames for the index files. I think @adonath's solution is a good one which can be implemented very quickly.

**Comment by adonath** [comment]
@lmohrmann In the Gammapy call today we decided to extend `from_dir()` as I suggested and just remove `.from_files()`. Note that both `hdu_table_filename` and `obs_table_filename` should take an relative as well as absolute path, implementing the logic of looking in the `base_bath` first, that you suggested.  So feel free to go ahead and open a PR.

**Comment by lmohrmann** [comment]
See here: #1793

**Comment by lmohrmann** [comment]
Fixed with #1793. Closing.
