### ISSUE TITLE
Minimum value of `angle_increment` in `ReflectedRegionsFinder`

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#1798]
I don't like that passing values smaller than 1deg for `angle_increment` in the constructor of the `ReflectedRegionsFinder` raises an error. I assume this has been added to avoid long computation times? In any case, I'd suggest to rather print a warning and allow the user to use smaller values if desired.

@registerrier: I think you added this check. What do you think?

**Comment by registerrier** [comment]
Adding a minimal value is necessary to avoid introducing an infinite loop when `angle_increment=0`.
It seemed to me that a minimal value of 1 degree was already a very small value for the algorithm.
Do you have in mind a case where one would need lower values?

**Comment by lmohrmann** [comment]
I happen to have run the algorithm with a smaller value and am now unable to reproduce the results ;-) While that may not be a very good reason, it seems weird to me to set this arbitrary limit at 1 deg. Why not check for `angle_increment=0` directly?

**Comment by adonath** [comment]
Just a general comment. When reading the issue I was first surprised by the minimal value of 1 deg, but then I realized it is **not** the angular separation between two off regions on the circle, but really the rotation angle with respect to the observation position. I think it is correctly documented but still it did not seem like natural parametrization to me, especially because there is the `min_distance` which refers to the angular distance between two subsequent off regions. Without knowing the details of the algorithm this could be maybe improved...

**Comment by registerrier** [comment]
Issue solved with #1896 . Closing.
