### ISSUE TITLE
Fit background in MapFit

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#1804]
As far as I can tell, it's not possible to fit e.g. the normalization of the background model in `gammapy.cube.MapFit`. Is this correct?

If yes, I guess this is one of the things that we might want to add soon. For this, the background would somehow need to be added to the model, right? Are there plans to do this already? Any timescale?

**Comment by cdeil** [comment]
Right, it's not possible yet without hacks, but it is high one of the high priority things to add next.

There is no timescale yet. This week we have to get v0.8 out, next is CTA meeting and then it's Gammapy coding sprint: https://github.com/gammapy/gammapy-meetings/tree/master/2018-10-01

So while this could be developed in a day or two, I think a realistic timescale for this and other new features is "in a few weeks".

**Comment by registerrier** [comment]
We checked, with @AtreyeeS , the possibility to define background models as `SkyModel`.

It does not work. Because you cannot add a model defined on the sky which returns a differential quantity at any position with a model that is bound to a given geometry and returns an integrated quantity. The only way to make it work is to make the background map a differential quantity by dividing by bin volume and exposure. But this is a not very good hack.

In reality, a `BackgroundModel` should be more or less the same thing as a `MapEvaluator` which returns an integrated map. This pleads for having a list of `MapEvaluator` (or we call them differently) in `MapFit`. Then `MapFit` will have to collect the individual parameters for this list.
Note that this is also a pre-requisite if one has to fit the map with two distinct set of IRFs (e.g. one source with a given PSF and edisp and another with distinct PSF and edisp).

**Comment by lmohrmann** [comment]
@registerrier @AtreyeeS 
Thanks for the notice! So what is the plan to move forward here? Is someone working on this? As you know, it will be very important for us to have this feature available a.s.a.p.
If I can help with anything, let me know.

**Comment by adonath** [comment]
@lmohrmann I've written up a proposal for improving the model framework of Gammapy, which includes implementing the background models as a first step (#1971). The modeling and fitting code design, will be reworked completely in early 2019. This means that the API for interacting with the background models will change again, but we can provide you with a preliminary solution, so that you can continue with your work.

**Comment by lmohrmann** [comment]
@adonath If it's not too much of an effort, a preliminary solution might actually be helpful. We could then start checking if everything comes out as expected. 

On the other hand, a complete rework of the modeling and fitting code sounds like a fairly large project. In case we would like to submit our paper before this is finished: any chance of including this "preliminary solution" into a release, so that we can properly refer to it?

**Comment by AtreyeeS** [comment]
@lmohrmann I am implementing a preliminary solution now, should be working by the end of this week. This will go into the v0.10 release (planned in the 3rd week of this month I believe). Does that sound good for you?

**Comment by lmohrmann** [comment]
@AtreyeeS Yes, very much so! I'm looking forward to trying this out :-)

**Comment by lmohrmann** [comment]
@AtreyeeS Any news on this item? I'm sorry for asking so much, but we'd really like to give this a try ;-)

**Comment by AtreyeeS** [comment]
Hello @lmohrmann ! I have filed a PR regarding this. Will let you know when this is merged.

**Comment by adonath** [comment]
@lmohrmann I just merged #1990, which implements the preliminary solution to fitting the background model. You can now basically do:

```
from gammapy.cube.models import BackgroundModel 
background_model = BackgroundModel(background_map, norm=1.1, tilt=0)

fit = MapFit(background_model=background_model)
result = fit.run()

# to print the best-fit parameters
print(background_model)

# to get the covariances

print(fit.evaluator.parameters.covariance)
```
Instead of:
```
fit = MapFit(background=background_map)
```



Preliminary means, that it will probably only stay in for `v0.10` and be replaced  by a more general solution (along with larger API changes and the ability to do join-likelihood analyses) in `v0.11`.
Feel free to try it out now, we're happy to receive any comments and reports on issues. I'll keep this issue open for this purpose, but set the `v0.11` milestone.

**Comment by lmohrmann** [comment]
Hi @adonath, @AtreyeeS, many thanks!

I've started testing this and it seems to work well, at least technically. I cannot say whether the results make sense yet, but I'll start investigating that now.

Let me try to summarize my understanding of what's possible and what is yet to be implemented:
Possible:
- "stacked" 3D likelihood fit
- fitting normalization + spectral tilt of the background model
Not yet possible:
- "joint" 3D likelihood fit (i.e. fit each observation individually and combine the likelihoods)
- specifying observation-wise energy thresholds for the fit
- using a 3D background model
The last point has been discussed in #1987 and will be addressed soon I think. From what you wrote, the joint fit (and observation-wise energy thresholds?) will be implemented in `v0.11`?

I think these would be the most important things we'd like to be able to use in the HESS FITS validation paper.

**Comment by adonath** [comment]
@lmohrmann Thanks for the feedback!

Your summary is completely correct. The joint-likelihood fit as well as non-radially symmetric background models are planned for the v0.11 release (~2 months from now, March 2019). I haven't thought about the  details of the energy threshold, but there will surely be a fitting mask per "Dataset" (or observation), that can be defined by the user. So technically it will be possibly, but maybe not with a super nice API yet. Details are discussed and described in #854.

**Comment by lmohrmann** [comment]
Here's a little more feedback: I'm trying to fit the six (non-flare) PKS 2155 runs from the HESS public data release with a `SkyPointSource` + `PowerLaw` and a `BackgroundModel`. This has worked well for the Crab runs, but in this case the fit just runs forever. I looked at the output (specifying `print_level=1`) and it looks like the fit actually found the correct minimum (the parameter values look reasonable and do not change between iterations), but the `edm` value is propably too large (around `1e-4`) for Minuit to stop the fit.

This could probably be avoided by passing appropriate values for `ncall` or `precision` to the `migrad` call here:
https://github.com/gammapy/gammapy/blob/888409c6b07ebe7266f890e77591192fb0b3caab/gammapy/utils/fitting/iminuit.py#L48

Can we make it possible for the user to change these values? If not, at the very least, I think we should set `ncall` to something smaller than the default value of 10000, since it takes a very long time to reach this number of calls and it's not obvious to the user why the fit never stops.

What do you think?

**Comment by adonath** [comment]
@lmohrmann I added a `migrad_opts` option in https://github.com/gammapy/gammapy/commit/c0ed928a096d57cc32a5d0dde24e7c342e764f36.

You can now pass options to migrad like so:

```python3
optimize_opts = {}
optimize_opts["migrad_opts"] = {"ncall": 100}
fit.run(backend="minuit", optimise_opts=optimize_opts)
```

**Comment by lmohrmann** [comment]
Many thanks!
