### ISSUE TITLE
MapMaker background norm is too high 

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#1842]
The background maps obtained with MapMaker produces a background cube which normalization is too high compared to the counts cube (~10%).
This is a major issue when fitting sources in DC1 as the bkg is not free in MapFit therefore other sources have to compensate for this effect affecting the entire region. Note that a similar issue was found (now fixed) in ctools (bkg is too high by ~13% in my RXJ study case) and was due to some interpolation issues. 
Could this be related to issue #1830 ?

To test this issue, I sub-selected only bkg events in DC1 with MC_ID==1. Attached is a zip file with a notebook and the DC1 subselection for 3 runs.
[BKGnorm_runs_notebook.zip](https://github.com/gammapy/gammapy/files/2435463/BKGnorm_runs_notebook.zip)
The issue is seen even for a single source with a map centered on the run position.
So it is not related to large offset or averaging multiple observations with different zeniths.

Below is the counts, predicted bkg with IRFs and residuals (counts-bkg)/sqrt(bkg)
<img width="847" alt="counts_bkg_resid" src="https://user-images.githubusercontent.com/8652898/46312914-c723aa80-c5c6-11e8-9d1c-22c304c4a4e5.png">

This is the associated histogram:
<img width="326" alt="histogram_resid" src="https://user-images.githubusercontent.com/8652898/46304715-bc115000-c5af-11e8-9630-d77528a9f814.png">

and the spectrum:
<img width="783" alt="spec_resid" src="https://user-images.githubusercontent.com/8652898/46304731-c3385e00-c5af-11e8-9b12-0bfcf222f81b.png">

@registerrier @JouvinLea @adonath @cdeil  any suggestions ?

**Comment by cdeil** [comment]
@registerrier and @adonath are looking into this issue this week.

**Comment by adonath** [comment]
In #1855 I implemented a new interpolation method for the background model. @facero Could you check whether this resolves the issue?

**Comment by facero** [comment]
ok. I'll check it out asap.

**Comment by cdeil** [comment]
@facero - Thanks for the updated check.

I think there might be two remaining issues that lead to the remaining small difference that you see:

A. Your energy binning is "only" 10 bins / decade -- if you change to 20 or even 30 bins / decade you will get even closer agreement. (note that for background you don't need many spatial bins to check, that can be coarse like 0.1 deg or 0.2 deg if you want faster execution).

B. There is a small bug or misunderstanding in run time that is multiplied with background rate IRF to get the background model between ctobssim and Gammapy. I'm not sure about this yet, so as a start I've opened #1866 where this can be discussed.

Note that issue B should lead to an absolutely constant shift in the residuals, not an energy-dependent one. Your residual curve has a peak around 100 GeV, which I think could be due to issue A. It might be better to plot "data / model" for this study, and maybe "sqrt(data) / model" as error bar to see how large Poisson fluctuations are expected to be.

@facero - Overall the insight you mention that %-level differences in background will affect source spectra for CTA because of the high event statistics it will collect is a very important one, this will be the limiting factor of many CTA measurements. Is it reflected in the close-out document somewhere? If no, @facero or @robertazanin - can you please add it somewhere?

**Comment by facero** [comment]
Agreed. I think I say something about this in my RXJ chapter. But this would maybe be important to highlight this in a summary section.
With real data we will never be able to produce a bkg with <1% accuracy (5% accuracy will be already hard to reach). 
So maybe it is important to be able to let the normalization of the bkg free in the fit (as ctools and as Fermi).

**Comment by lmohrmann** [comment]
@cdeil So far, I think we've used livetime, but that can be changed of course. It's good to know that Gammapy and ctools handle this differently.

**Comment by cdeil** [comment]
@lmohrmann - I've stated my recommendation here: https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/97#issuecomment-428214663

That's to CTA, but for HESS I'd suggest the same.

We get rid of the complexity with DEADC and different times and AEFF and BKG if we correct AEFF for DEADC in the HESS exporter and always put DEADC=1. @lmohrmann - Would you be willing to go that way and put this in the HESS exporter and do that for FITS productions from now on?
(Waiting for decisions for CTA is never a good strategy. It might come a year for now or in two. We should go ahead and put / prototype better solutions whenever we can without waiting for decisions / approval.)

**Comment by lmohrmann** [comment]
@cdeil This sounds like a reasonable way to go - I've made the changes to our exporters and verified that I still get the same results.

**Comment by cdeil** [comment]
@lmohrmann - Thank you!

**Comment by facero** [comment]
#1855  fixed most of the bkg norm issue.
A remaining 1-2% is still observed. This could be due to how we define live-time.
For faint extended sources this 2% effect can have some impact and in future the bkg norm will be a free parameter.
