### ISSUE TITLE
Error of matplotlib 3.0.0 in a tutorial notebook

### ISSUE THREAD

**Issue by peroju** [gammapy/gammapy#1843]
I've been following the tutorial notebook "first_steps" in the documentation and I've found an error when running cell number 9. I also get the same error in every cell that tries to plot a .fits file. The error states: "TypeError: get_tightbbox() takes 2 positional arguments but 3 were given".

I'm using the gammapy-0.8 conda environment, installed on 01/10/2018 following the instructions from the documentation. The problem maybe is in the matplotlib version, I'm using 3.0.0, and I ran this notebook before with 2.2.3 and it worked.

Here I leave you a link to the notebook with the error I got:
- http://nbviewer.jupyter.org/gist/peroju/b6a76da313459e0c6eb60a66a5b986c8

Thanks!

**Comment by cdeil** [comment]
@peroju - Thanks for reporting the issue.

As a fix for v0.8, I've changed the spec to `matplotlib>=2,<3` (recommended way to handle this case from the conda docs, works for me locally, gives an install with a MPL from the 2.x series).
See  https://github.com/gammapy/gammapy-webpage/commit/93e079df8636aa9ae66bc8c26db649abf9e704a2

@adonath - assigned to you and v0.9, still needs a real fix, i.e. change our code / notebooks to work with MPL v3.0.

**Comment by cdeil** [comment]
Since @adonath is on vacation for the next weeks, @Bultako - maybe you could have a look and make a suggestion?

This issue also shows up in CI
https://travis-ci.org/gammapy/gammapy/jobs/439702877#L1356
and I think will for all users that have MPL 3.0 for some reason.

I remember last week @adonath suggested to just remove the `%matplotlib inline` from all notebooks and that fixes the issue. But I'm not sure if this is the best fix, and whether this works with MPL 2.1 or even 2.0  which I guess is still pretty widely used? Or is this Jupyter version dependent?

**Comment by Bultako** [comment]
I think most of the errors (if not all) come from `astropy.wcs` issue with `%matplotlib inline` command. The plot methods broken use the `projection` parameter inherited from  `astropy.wcs`

There's a recent PR to fix this in `astropy` master branch:
https://github.com/astropy/astropy/pull/7839

See also changes in file `astropy/visualization/wcsaxes/core.py` https://github.com/astropy/astropy/pull/7839/files#diff-5631d4723a5f483d531d8918dd79bdabR454 

>  MATPLOTLIB_LT_30: The ``kwargs.pop('label', None)`` is to ensure
     compatibility with Matplotlib 2.x (which has label) and 3.x (which has
    xlabel). While these are meant to be a single positional argument,
    Matplotlib internally sometimes specifies e.g. set_xlabel(xlabel=...).

I don't think we can fix this with modifs in the `gammapy` base-code, I guess the error will be thrown anyway when calling the `astropy.wcs` classes.

If we find other errors coming from our notebooks or base-code, we can easily fix them replacing the `label` param by `xlabel`

@cdeil 
better wait for a next version of `astropy`?
should we force an `astropy` install from their master branch for our dev version?

**Comment by cdeil** [comment]
@astrofrog - This incompatibility of MPL 3.0 and WCSAxes with `get_tightbbox` (see https://github.com/astropy/astropy/pull/7839) is showing up in Gammapy CI and for Gammapy users.

See e.g. https://travis-ci.org/gammapy/gammapy/jobs/439702877#L1356

What is the best way to handle that?

I'm thinking use `matplotlib>=2,<3` at least until Astropy releases are out to resolve the issue?
Or is there anything we can / should do?
The error seems to go away when removing `%matplotlib inline` in our tutorial notebooks, not sure if that is something we should remove or not.

**Comment by cdeil** [comment]
@adonath - What do you suggest we do here?

Make some change now for v0.9, or defer to v0.10, or just document somehow as a known issue for certain Astropy & MPL version combinations?

**Comment by adonath** [comment]
I've looked a bit into the issue and a temporary workaround is to re-configure the notebooks inline backend to not use the `tight` layout for showing the plot inline. This can be achieved using:
```
%config InlineBackend.print_figure_kwargs = {'bbox_inches': None}
```
(see ["Matplotlib and Ipython notebook displaying exactly the figure that will be saved"](https://stackoverflow.com/questions/37864735/matplotlib-and-ipython-notebook-displaying-exactly-the-figure-that-will-be-save?answertab=active#tab-top) on stackoverflow) 

I guess we don't want to add this line to all of our notebooks, so it's probably best to list this a know issue and refer users to this GH issue with the workaround?

**Comment by cdeil** [comment]
> I guess we don't want to add this line to all of our notebooks, so it's probably best to list this a know issue and refer users to this GH issue with the workaround?

I think yes, that might be best.

Maybe put a section at the bottom of https://docs.gammapy.org/0.8/install/check.html or make a new sub-page?

Another action item here is that we should probably start creating the recommended `environment-0.9.yaml` and bump the Astropy and MPL version there.

Is `%matplotlib inline` still needed or recommended with modern JupyterLab? Should we remove it?

@adonath - if you want to do these edits, go ahead. Otherwise just assign to me and I'll do it as part of the preparations for v0.9 next week.

**Comment by adonath** [comment]
When shall we close this issue? When the next release of Astropy with the fix is out? Or close it now, as there is nothing more to do here...

**Comment by cdeil** [comment]
Suggest to always close issues when there is no action item left.

**Comment by Bultako** [comment]
This issue has been solved in version 3.0.5 the astropy.

**Comment by cdeil** [comment]
Can one of you make an edit to update the info here?
https://github.com/gammapy/gammapy/blob/master/docs/install/check.rst#known-issues
(could be done just with the web interface)

**Comment by adonath** [comment]
Done in https://github.com/gammapy/gammapy/commit/f1d290fba6d5d0d5ecadc443302970791d64de24

**Comment by cdeil** [comment]
I noticed that we were still using MPL 2 in the stable version conda envs:
https://github.com/gammapy/gammapy-webpage/blob/0931883cc34ce6adecfef942fa657cfefa31ca7a/download/install/gammapy-0.12-environment.yml#L23

In the dev env we were already using MPL 3 since a while (probably half a year or so) without issues:
https://github.com/gammapy/gammapy/blob/master/environment-dev.yml

I would suggest that we move on to MPL 3 for the stable versions also. To help with that, I've already made an env file here:
https://github.com/gammapy/gammapy-webpage/blob/e794acffdcb4d8b73b541def24e3ecacc2e8edaf/download/install/gammapy-0.13-environment.yml#L23

The updates are:
- MPL 2 -> 3
- Python 3.6 -> 3.7
- ipython 7.3 -> 7.5
- healpy 0.11 -> 0.12
- scipy 1.2 -> 1.3

Install and running tests works locally. 

We can still do further updates before the release, and already have the env for testing in the meantime ...


I did not do any tests with notebooks (but we have been using those in the dev env for months). Probably adding a few automated tests that would catch issues with MPL and notebooks in CI like this one would be good.

**Comment by Bultako** [comment]
> healpy 0.11 -> 0.12

small typo in the message above, it's ok in the env file
healpy 1.11 -> 1.12

> I did not do any tests with notebooks (but we have been using those in the dev env for months). Probably adding a few automated tests that would catch issues with MPL and notebooks in CI like this one would be good.

do you mean always having an env file for the next release, and fetching it and checking all tests pass in `azure-pipelines.yml`?
+1

**Comment by cdeil** [comment]
> do you mean always having an env file for the next release, and fetching it and checking all tests pass in azure-pipelines.yml?
+1

I meant use it locally for testing.
Generally we can and probably should add a few more CI build, PRs welcome.
In this case specifically I'm not sure we gain much compared to the ones we already have (many builds using the gammapy-dev env).
Adjusting the release env is already something we can do after the release, so we don't have to get it 100% right before the release.
