### ISSUE TITLE
Optional filed ONTIME in the observation index table

### ISSUE THREAD

**Issue by tony32lin** [gammapy/gammapy#1844]
According to the current version of DL3 spec(https://github.com/open-gamma-ray-astro/gamma-astro-data-formats), the ONTIME filed in observation index table is listed as optional yet it's been used by gammapy.  More details can be seen at open-gamma-ray-astro/gamma-astro-data-formats/issues/131.

Is this something that is planned to be changed in gammapy in the future?

**Comment by cdeil** [comment]
@tony32lin - Thanks for reporting the issue!

Maybe short-term we should change this line to use the required columns `TSTOP` and `TSTART` instead of the optional column `ONTIME` to avoid the issue?
https://github.com/gammapy/gammapy/blob/5a9027d99f814dafcd8239cb65add438528c803b/gammapy/data/observations.py#L253

Although this doesn't help much, because `DEADC` and `LIVETIME` are also optional in the obs index table, so a similar issue would likely appear here:
https://github.com/gammapy/gammapy/blob/5a9027d99f814dafcd8239cb65add438528c803b/gammapy/data/observations.py#L264

Really the solution is probably not to rely on info from the obs index table at all, but to read the info from the "data" files directly, i.e. mostly from the EVENTS header at the moment, and possibly a TECH3 HDU in the future.

@dcfidalgo @cboisson @registerrier - let's discuss tomorrow, to have a clear picture how the observation classes should work for now (irrespective of the fact that we'll proably have to change them again in a year once things become clear in CTA).

**Comment by dcfidalgo** [comment]
Just a small update on this:
`ONTIME` and `LIVETIME` are not longer needed in Gammapy (PR #1908), both quantities are computed via the GTI table now, or via the `TSTART` and `TSTOP` from the obs-index file if no GTI table is available.
However, to compute the live time we still make use of the `DEADC` parameter. I think it is still not clear how the dead time will be handled in CTA (see the [discussion here](https://github.com/open-gamma-ray-astro/gamma-astro-data-formats)).

**Comment by cdeil** [comment]
I don't think there's a concrete action item left here, deciding how dead-time is handled will be discussed in CTA next year and then Gammapy will follow. I'm closing this issue now. The corresponding issue in the spec is still open: https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/62
