### ISSUE TITLE
Mapfit yields NaN values in simulate_3d notebook

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1868]
When fitting with Mapfit in the `simulate_3d` notebook the fit does not produce values, while previous versions of the Mapfit yielded values.

Maybe this is due to last devels in PR https://github.com/gammapy/gammapy/pull/1846?

Some screenshots to illustrate.

Now:
![captura de pantalla 2018-10-09 a las 9 20 28](https://user-images.githubusercontent.com/328261/46652873-a6e68380-cba4-11e8-81bb-cde8324bef0f.png)

Before:
![captura de pantalla 2018-10-09 a las 9 20 34](https://user-images.githubusercontent.com/328261/46652884-b1a11880-cba4-11e8-8e81-f95fb572d361.png)

**Comment by cdeil** [comment]
@AtreyeeS - Can you please have a look?

**Comment by AtreyeeS** [comment]
The notebook runs properly on my branch after implementation of PR #1846, but fails after commits from #1855
I think as @registerrier pointed out, this is related to the GridInterpolation being used now.

**Comment by cdeil** [comment]
Axel is on vacation for the next weeks. @registerrier or @AtreyeeS - Can you have a look and make it better? If no - assign to me and I'll do it in the next days.

**Comment by registerrier** [comment]
The issue here can be solved by putting proper limits to parameters. The optimizer ends up in an incorrect solution yielding `NaNs` and `Infs` and gets stuck there. By using reasonable min and max values for the parameters the fit converges smoothly.

This means that there should be some protection in model evaluation to avoid nans. And maybe some default range should be given for the parameters.

**Comment by registerrier** [comment]
Looking into that deeper, we have noted with @AtreyeeS that even analysis_3d notebook fails if you change initial parameters to something slightly different. Things are a bit better (i.e. converge but not where it should) if you impose `amplitude>0`. Parameter bounding is  a necessary step all the time.

Note that parameter bounds are not scaled with the parameter value. This should be changed to avoid unexpected results. Note that some models should come with default meaningful limits: e.g. `amplitude` should not become negative.

A debug output in `Fit` is also necessary to track this kind of issues.

**Comment by registerrier** [comment]
PR #1881 should solve the issue of nans. Then the fit can converge if one puts reasonable min and max values on the spectral index. We can simply put them in the the notebook for now, or we should define default min and max values for spectral indices e.g. between 0 and 10.

**Comment by Bultako** [comment]
Maybe related with this closed issue.

I've found that in cell[40] of [3D analysis notebook](https://docs.gammapy.org/0.9/notebooks/analysis_3d.html) Mapfit provides Nan values for errors in  parameters and covariance of the second component of the model. This prevents for potential plotting the errors later in i.e. cell[44]

**Comment by adonath** [comment]
@Bultako @AtreyeeS Is this issue still present?

**Comment by AtreyeeS** [comment]
No this should be solved since #1990 . While adding the background model, some changes were done to solve this as well. We now extract the covariance of the spectral parameters within the tutorial. 
`covariance = result.parameters.covariance`
`spec.parameters.covariance = covariance[2:5, 2:5]`
The notebook works fine.

**Comment by adonath** [comment]
OK, thanks! Closing now, please reopen if the issue appears again.

**Comment by Bultako** [comment]
Could it be possible to attach the resulted covariance to the model *automagically* when doing the fitting? I think things worked in this way before and users did not have to make this step so explicitly. Now trying to guess which index of the covariance they should attach to the model and how to do it.

**Comment by adonath** [comment]
@Bultako Yes, this worked when we only fitted a single model instance, but even then the sub-covariance was not set on the `.spectral_model` and `.spatial_model`.

Now the complexity of our models as increased a lot (a hierarchical structure of multiple `SkyModel` and `BackgroundModel` per dataset and multiple datasets). So the way it works now is that the "global" covariance is attached to the `result.parameters` object after the fit. But unfortunately
it is not easily possible to "dispatch" the sub-covariances to the sub-parameter lists, because we work with a flattened global parameter list and the information, which parameter belongs to which model instance and dataset is lost. I guess we need to introduce either `name` attributes for `SkyModel`, `BackgroundModel` and `Dataset` or keep references to the parent object in the `Parameter` objects.

So doing this automatic setting of the sub-covariances is technically not possible at the moment, but I agree it's probably desirable to have this in future.
