### ISSUE TITLE
Removing environment variable GAMMAPY_EXTRA

### ISSUE THREAD

**Issue by dcfidalgo** [gammapy/gammapy#1889]
Right now we are using the `GAMMAPY_EXTRA` env variable only to access either the folder `datasets` or `test_datasets` in the gammapy-extra repository.
However, we also have the `GAMMAPY_DATA` env variable.
As a user this points to the downloaded data sets, as a developer it should point to `$GAMMAPY_EXTRA/datasets` if you want to run tests locally, so i have to define both env variables.

I would suggest to move the `test_datasets` into the `datasets` folder and get rid of the `GAMMAPY_EXTRA` variable.
Then as a developer i only need to point `GAMMAPY_DATA` to the `datasets` folder in my gammapy-extra repository.

@Bultako  and anyone, thoughts?

**Comment by dcfidalgo** [comment]
ah sorry, i just saw that we also use it to access the `logo/gammapy_logo.pdf` and `gammapy_logo.png` ...

**Comment by cdeil** [comment]
> I would suggest to move the test_datasets into the datasets folder and get rid of the GAMMAPY_EXTRA variable.
> Then as a developer i only need to point GAMMAPY_DATA to the datasets folder in my gammapy-extra repository.

This assumes that we will always ship all tutorial and test datasets via the `gammapy-extra` git repo. I don't think that's the way to go. E.g. there's already files in https://github.com/gammapy/gammapy-fermi-lat-data/ and other datasets will appear. @Bultako  worked hard (see [here](https://github.com/gammapy/gammapy-webpage/blob/gh-pages/download/data/gammapy-data-index.json)) to make `gammapy download` and `GAMMAPY_DATA` independent of git and Github.

I'm not sure if we can / should get rid of `GAMMAPY_EXTRA` for developers. I think it would have to be replaced with a second `gammapy-test-data-index.json` solution, where we have control and are able to define test dataset files, without exposing those to users.

My suggestion would be to keep GAMMAPY_EXTRA for now, and gradually evolve the Gammapy tests to use less data files, and to access them via GAMMAPY_DATA in some places (I think we already do this / it's possible?), and then to re-discuss this point in a future Friday call if we can transition completely away from accessing GAMMAPY_EXTRA in tests (always anyone is welcome to put issues on the agenda).

**Comment by Bultako** [comment]
I think we do need both environment variables, mainly because of the high volume of the whole datasets. It is the analogy for notebooks with the execution time. We cannot afford to provide `gammapy download datasets` taking minutes to download GBs of data (and many not needed by users), neither provide notebooks taking tens of minutes to execute. 

Saying this, what to put in the `GAMMAPY_DATA` env var and what to put in `GAMMAPY_EXTRA` env var is a something that can fine-tune easily, and as @cdeil said we are happy to be GitHub independent, we could store these datasets anywhere we like. In the same way, which notebooks should be placed in `Gammapy` repo and which ones in `Gammapy-extra` is a similar question. 

Coming to the suggestion made by @dcfidalgo, note that you have decided to point your `GAMMAPY_DATA` to your local git repo of `Gammapy-extra/datasets`. **This should not be like this.** We could decide in a future to place some of the `GAMMAPY_DATA` anywhere else (or add data from a different GH repo) and then your set-up will not work. I personally have my `GAMMAPY_DATA` env var pointing to a folder I downloaded with `gammapy download datasets`. There could be also the case that some datasets in `Gammapy-extra/datasets` may not delivered to the users with `gammapy download datasets` (because they are not in the [list](https://github.com/gammapy/gammapy-webpage/blob/gh-pages/download/data/gammapy-data-index.json), so with your set-up you will be having false positives when testing your code/notebooks. 

So, short answer:
- Developers need a bigger dataset collection that we cannot afford to deliver to users.
- I would use `GAMMAPY_EXTRA` for anything not related with user needs.


P.S.
We do also use `GAMMAPY_EXTRA` env var to access some images when building the documentation, so it is also needed for doc maintainers.

**Comment by dcfidalgo** [comment]
Ok, i see.

>Coming to the suggestion made by @dcfidalgo, note that you have decided to point your GAMMAPY_DATA to your local git repo of Gammapy-extra/datasets. This should not be like this. We could decide in a future to place some of the GAMMAPY_DATA anywhere else (or add data from a different GH repo) and then your set-up will not work. I personally have my GAMMAPY_DATA env var pointing to a folder I downloaded with gammapy download datasets. There could be also the case that some datasets in Gammapy-extra/datasets may not delivered to the users with gammapy download datasets (because they are not in the list, so with your set-up you will be having false positives when testing your code/notebooks.

I also had my `GAMMAPY_DATA ` pointing to the downloaded dir `gammapy_tutorials/datasets`. 
But when i ran the tests locally, one test failed because it could not find the needed dataset.
I see now that the two `datasets` folders created by`gammapy download datasets` and `gammapy download tutorials` are slightly different:
```
diff -r gammapy-tutorials/datasets/ gammapy-datasets/
Only in gammapy-tutorials/datasets/cta-1dc: caldb
Only in gammapy-tutorials/datasets/cta-1dc/data/baseline/gps: gps_baseline_110380.fits
Only in gammapy-tutorials/datasets/cta-1dc/data/baseline/gps: gps_baseline_111630.fits
Only in gammapy-tutorials/datasets/cta-1dc: index
Only in gammapy-tutorials/datasets/cta-1dc: make.py
Only in gammapy-datasets/: ebl
```
That is why the test actually failed, it required the ebl dataset. Is there a reason why the two `datasets` folders are different?

Also, in `gammapy/catalogs` you have:
```
gammapy/catalog/fermi.py
354:                    "$GAMMAPY_DATA/catalogs/fermi/Extended_archive_v15/Templates/"
956:                    "$GAMMAPY_DATA/catalogs/fermi/Extended_archive_v18/Templates/"
1021:    def __init__(self, filename="$GAMMAPY_DATA/catalogs/fermi/gll_psc_v16.fit.gz"):
1126:    def __init__(self, filename="$GAMMAPY_DATA/catalogs/fermi/gll_psch_v07.fit.gz"):
1158:    def __init__(self, filename="$GAMMAPY_DATA/catalogs/fermi/gll_psch_v08.fit.gz"):
1199:    def __init__(self, filename="$GAMMAPY_DATA/catalogs/fermi/gll_psch_v13.fit.gz"):

gammapy/catalog/hawc.py
169:    def __init__(self, filename="$GAMMAPY_DATA/catalogs/2HWC.ecsv"):
```
which right now does not make much sense if your `GAMMAPY_DATA` is pointing to your `gammapy download` datasets folder. 

So maybe we could restrict ourselves to use only the `GAMMAPY_EXTRA` variable in the gammapy source code (leave `GAMMAPY_DATA` for the tutorials), or introduce an option in `gammapy download` that allows to download all the needed datasets for the tests + catalogs.

As a side note: Maybe we should introduce a check for `GAMMAPY_DATA` when running `gammapy info`. 
It looks a bit awkward that it tests for `GAMMA_CAT`, `GAMMAPY_FERMI_LAT_DATA` and `CTADATA` but not the one that is actually needed for the tutorials ...

**Comment by Bultako** [comment]
@dcfidalgo 
Thanks for your raising all this !

As it was conceived `gammapy download datasets` should fetch all the datasets that are declared/harcoded shomehow in the source code and also used in the tutorials, **with the exception of code for tests**. That's what I called datasets related with user needs.

On the other hand `gammapy download tutorials` should fetch only the datasets that are needed for the execution of tutorials.

So, datasets from `gammapy download tutorials` should be a big part of  `gammapy download datasets` and `$GAMMAPY_DATA` should point to files downloaded by `gammapy download datasets`.

I have just made myself a test now and run both `gammapy download datasets` and  `gammapy download tutorials`. The I've made the diff with the following output.

```
$ diff -r gammapy-tutorials/datasets/ gammapy-datasets/
Only in gammapy-datasets/cta-1dc: caldb
Only in gammapy-datasets/cta-1dc/data/baseline/gps: gps_baseline_111140.fits
Only in gammapy-datasets/cta-1dc/data/baseline/gps: gps_baseline_111630.fits
Only in gammapy-datasets/cta-1dc/index/gps: hdu-index.fits.gz
Only in gammapy-datasets/cta-1dc: make.py
Only in gammapy-datasets/: ebl
```

So datasets for tutorials are a part of the whole gammapy-data.
`gammapy download datasets` size is 96MB and `gammapy download tutorials` is 84MB.
With this reasoning, I think the code in the scripts for catalogs should remain with `$GAMMAPY_DATA`

I understand it is a bit confusing to have datasets downloaded by both gammapy download commands. 

@cdeil @dcfidalgo 
Maybe we could download the whole gammapy-data with `gammapy download tutorials` (not only those used in the tutorials) The difference in size is not so big (12MB) and that would simplify the code. I could do that in the coming week, I planned to refactor the code to solve minor issues with `gammapy download`.

On the contrary I don't know if I would include the datasets for tests in the download, these are datasets non-related with user needs. Ok, developers would need to have two env vars (`GAMMAPY_DATA` and `GAMMAPY_EXTRA`) but users will get rid of un-needed datasets. I've had a look at the size ~142MB in total - `datasets/` + `test_datasets/` from Gammapy-extra. I would like to know what do you think on how catalogs could evolve in Gammapy, and what could be done with the others `GAMMAPY_FERMI_LAT_DATA`  and `GAMMA_CAT`. Are these datasets related with user needs hardcoded in source? Will be more coming? If you think we have achieved a quite stable state with catalogs, we could deliver all the datasets  in Gammapy-extra with the two `gammapy download` commands, since I think 140MB is feasible.

> As a side note: Maybe we should introduce a check for GAMMAPY_DATA when running gammapy info.

Sure, I can do it.

**Comment by Bultako** [comment]
More info on this.
For some unknown reason  that I have to investigate, `gammapy download tutorials` did not downloaded all the files in my test. The results are now as they should be.

```
$ diff -r gammapy-tutorials/datasets/ gammapy-datasets/
Only in gammapy-datasets/: ebl
```

And the difference in size is only 868KB.
If `ebl/` catalog is not shipped with the tutorials is because it is not used, but I'm in favor for shipping the whole dataset collection also with `gammapy download tutorials`.

**Comment by dcfidalgo** [comment]
@Bultako - Thanks!
>For some unknown reason that I have to investigate, gammapy download tutorials did not downloaded all the files in my test. 

I also noted some unstable behaviour of the `gammapy download` command, for example this gives me very likely a different content in the test folders:
```
gammapy download datasets --src cta-1dc --out test1
gammapy download datasets --src cta-1dc --out test2
gammapy download datasets --src cta-1dc --out test3
```
Do you experience the same? Is it just me?

**Comment by cdeil** [comment]
I didn't have a close look, just a general comment: if the download implementation is structured as a two-phase process, the implementation is easier and more testable: first compute a complete manifest (a list) or files to download, as the diff of files requested and locally already available. This doesn't need to hit the network (apart from the index file) and is easy to test. Then execute the download, possibly in parallel. The parallel download code has nothing gammapy-specific in it; it's not mixed with our special case of having notebooks or tutorials.

For another project we did this: https://github.com/hipspy/hips/blob/master/hips/tiles/fetch.py
It also mixes the generic parallel download feature with the current application, not passing a list of filenames / URLs, but a list of objects. So it's more complicated than it needs to be and not directly re-usable. I think (but am not even sure) the current Gammapy download code also isn't as clearly structured / separated as it could be.

**Comment by Bultako** [comment]
Solved in https://github.com/gammapy/gammapy/pull/2001
