### ISSUE TITLE
Notebooks related with GTI durations of observations broken 

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1928]
* cta_1dc_introduction.ipynb
* cta_data_analysis.ipynb
* analysis_3d.ipynb

```bash
$gammapy jupyter --src=./tutorials test

INFO:gammapy.scripts.jupyter:   ... TESTING ./tutorials/cta_1dc_introduction.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.30 mn
INFO:gammapy.scripts.jupyter:   ... FAILED
INFO:gammapy.scripts.jupyter:

KeyError in cell [57]

--SOURCE CODE: 
print(obs)
--TRACEBACK: 
KeyError: 'START'

INFO:gammapy.scripts.jupyter:   ... TESTING ./tutorials/cta_data_analysis.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.16 mn
INFO:gammapy.scripts.jupyter:   ... FAILED
INFO:gammapy.scripts.jupyter:

KeyError in cell [12]

--SOURCE CODE: 
%%time
maker = MapMaker(geom, offset_max="2 deg")
maps = maker.run(observations)
print(maps.keys())

--TRACEBACK: 
KeyError: 'START'

INFO:gammapy.scripts.jupyter:   ... TESTING ./tutorials/analysis_3d.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.16 mn
INFO:gammapy.scripts.jupyter:   ... FAILED
INFO:gammapy.scripts.jupyter:

KeyError in cell [7]

--SOURCE CODE: 
%%time
maker = MapMaker(geom, offset_max=4.0 * u.deg)
maps = maker.run(observations)

--TRACEBACK: 
KeyError: 'START'
```

**Comment by cdeil** [comment]
@dcfidalgo - Favor Atender.

**Comment by dcfidalgo** [comment]
@Bultako I just ran 
`gammapy jupyter --src=./tutorials test --kernel=gammapy-dev`
with the updated master and everything passes.
I also tried to print out an observation in a notebook and it worked fine. Not sure what is happening, i will have a closer look asap.

**Comment by dcfidalgo** [comment]
I was talking to @Bultako and we figured out what happened.
He was using the old version of the CTA 1DC data set we have on gammapy-extra, in which the hdu-index file has an error in the HDU_NAME for the GTI tables (it says `EVENTS` instead of `GTI`). So when creating a DataStoreObservation `obs = datastore.obs(11038) and accessing `obs.gti.table` it actually returned an event list, in which the key 'START' was obviously missing.

In the new hdu-index file for the CTA 1DC data set, this error is corrected and `obs.gti.table` returns an actual GTI table. Closing this issue now.
