### ISSUE TITLE
Creating axis with one bin with node_type center

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1952]
Hello! I am not sure if it is a bug or a problem with my understanding. It seems it is impossible to create an axis with only one energy bin and `node_type=center`
eg:
`import numpy as np`
`from gammapy.maps import MapAxis`
`MapAxis(nodes=np.linspace(0, 10, 1), unit='TeV', name='test', node_type='center', )`

fails. Incidentally, `axis = MapAxis(nodes=np.linspace(0, 10, 1),  node_type='center')` pretends to work, but then, accessing the `axis` object fails.

**Comment by AtreyeeS** [comment]
Well, as @registerrier just explained to me, with only one `node`, it obviously fails to understand what the `min` and `max` values are. So, it should fail.

But I still think its a bit weird. How does a a user create a differential map with only one bin? At the very least, I think the axis creation should fail at the first step instead of pretending to work and then giving strange problems later.

comments @cdeil , @adonath ?

**Comment by Bultako** [comment]
> But I still think its a bit weird. How does a a user create a differential map with only one bin? 

I guess a quick patch in the code of MapAxis to create an axis of one single bin with `node_type='center'` could be to create the axis with `node_type='edges'`

@AtreyeeS 
Does the command below solve your needs?

```python
MapAxis(nodes=(0,10), unit='TeV', name='test', node_type='edges', )

MapAxis

	name       : test      
	unit       : 'TeV'     
	nbins      : 1         
	node type  : edges     
	edges min  : 0.0e+00 TeV
	edges max  : 1.0e+01 TeV
	interp     : lin   
```

**Comment by AtreyeeS** [comment]
@Bultako : Well, this should work for most use cases, but this then, `node_type` is `edges`. And in some special cases, eg: https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/cube/models.py#L301

we specifically want it to be center.

**Comment by adonath** [comment]
Thanks @AtreyeeS, for bringing this issue up. Conceptionally, I think, it makes totally sense to have a `MapAxis` with just one bin and `node_type=center`. Technically there is the issue, that we use linear interpolation to transform pixel to physical coordinates for the axis, which requires at least two nodes.
So I'm not sure what to do here. Maybe implement a special case and change to zero order interpolation for one-binned axes?

**Comment by cdeil** [comment]
This is the error:
```
>>> from gammapy.maps import MapAxis
>>> MapAxis(nodes=[42], node_type='center')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/work/code/gammapy/gammapy/maps/geom.py", line 602, in __repr__
    vals = self.edges if self.node_type == "edges" else self.center
  File "/Users/deil/work/code/gammapy/gammapy/maps/geom.py", line 406, in center
    return self.pix_to_coord(pix)
  File "/Users/deil/work/code/gammapy/gammapy/maps/geom.py", line 527, in pix_to_coord
    return pix_to_coord(self._nodes, pix, interp=self._interp)
  File "/Users/deil/work/code/gammapy/gammapy/maps/geom.py", line 296, in pix_to_coord
    np.arange(len(edges), dtype=float), scale(edges), fill_value="extrapolate"
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 543, in __init__
    "least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries
```
@AtreyeeS - note that it fails in `__repr__`, not directly in `__init__`, that's why this doesn't error out yet:
```
>>> axis = MapAxis(nodes=[42], node_type='center')
```

> So I'm not sure what to do here. 

Me neither.

> Maybe implement a special case and change to zero order interpolation for one-binned axes?

That's one option.

Another might be to change the internal data structure of `MapAxis` to something a little more general: always have lo, hi, center for every bin, and store those as data members. Currently only a `nodes` data member is stored, and it sometimes contains center and sometimes edges.

This proposed change to `MapAxis` would be mostly transparent, all current uses could behave the same. Specifically if the user gives just one center, then we would fill the given value as `lo = hi = center` and certainly the `__repr__` wouldn't have to error out.

Whether we would want to support interpolation / extrapolation for this one-node case, and whether it would require an if / else or could be done in some more elegant way I don't know. So overall this proposal doesn't achieve much, we would just always compute `lo`, `hi` and `center` in `__init__` on axis creation. And it's a bit more general in that there could be `center` nodes anywhere.

Note that `MapFit` works with one energy bin already (probably because we don't use node_type center e.g. for exposure):
https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/cube/tests/test_fit.py#L151
It might be useful to make a PR where a full chain of MapMaker and MapFit gets to run with minimal changes / hacks for this, to see whether it just requires a change in one place or if there's many places where it fails.

And then discuss in the next call whether we want to support image analysis via 2D map objects or 3D with one energy bin, and for which maps to use `node_type` center or edges, and only then decide on which changes to implement for `MapAxis`?

**Comment by AtreyeeS** [comment]
> Specifically if the user gives just one center, then we would fill the given value as `lo = hi = center` and certainly the `__repr__` wouldn't have to error out.

Are you proposing to have an axis of 0 bin width? Will this not be a problem later on, maybe in `MapEvaluator` or so on? 
But the proposal of having lo, hi, center for each bin sounds good to me.

**Comment by cdeil** [comment]
> Are you proposing to have an axis of 0 bin width? Will this not be a problem later on, maybe in MapEvaluator or so on?

It depends on how `node_type` is used in analysis. E.g. if this is used for sky diffuse models or exposure, and the only operation used on those is to `interpolate`, then they should never need `lo` and `hi`, and it doesn't matter if those are present or what is stored there.

Note that @registerrier and you are filing several issues on specific cases where it's not clear what `node_type` is supposed to do in Gammapy, and that also isn't clarified in the spec yet (see #1887).

It would probably be most efficient if one of you (or @adonath) writes a short section, e.g. after this one: https://docs.gammapy.org/0.8/development/howto.html#coordinate-and-axis-names, or on the maps docs page, that explains if / how `interp_type` and maps with one bin should be handled in Gammapy. And then once it's clear and agreed how it's supposed to work, there would presumably be a few small PRs in Gammapy to make it so, and at least one PR to the spec to make it clear in the format spec als.

**Comment by AtreyeeS** [comment]
Yes, I agree. This needs a bit of clarity on what exactly we want to support (and give proper errors for the cases which we will not)

> It depends on how node_type is used in analysis. E.g. if this is used for sky diffuse models or exposure, and the only operation used on those is to interpolate, then they should never need lo and hi, and it doesn't matter if those are present or what is stored there.

Well, yes. But I was also thinking of computing the model fluxes, eg : https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/cube/fit.py#L195
and there zero bin widths might create confusing errors...

**Comment by cdeil** [comment]
Sure, if you want to create an integral quantity like flux, you need to have a map with `lo` and `hi`.

**Comment by adonath** [comment]
We shortly discusses this at the coding sprint again and the conclusion was to allow for node-type `center` by using nearest neighbour interpolation in the case of one energy bin.

**Comment by adonath** [comment]
I'm not sure why we missed this, but currently there is not a single use case, where we could allow `node_type="center"` for modelling fitting, because in the model evaluation we integrate the spectral model in a certain energy range. So we require the bin size of the energy bin (even if it's a single one) to be defined. So I propose to just disallow the single energy bin for now and raise and error on `MapAxis.__init__()`.

**Comment by adonath** [comment]
Resolved by #2653 for now.

**Comment by adonath** [comment]
I'm reopening this because of https://github.com/cosimoNigro/agnpy_paper/issues/18#issuecomment-983712319.

When evaluating models for flux point fitting we actually rely on the bin center for the energy, see https://github.com/gammapy/gammapy/blob/master/gammapy/datasets/flux_points.py#L207. So I guess we should implement the handling proposed in https://github.com/gammapy/gammapy/issues/1952#issuecomment-441977426, i.e. change to nearest interpolation and an additional check if the edges are required for integration in certain places.

Alternatively we change the internal data model for `MapAxis` to be able to provide bin centers as well as edges. This could be useful e.g. in cases where the center is not derived from the bin edges as well.

**Comment by adonath** [comment]
I'll work in this.
