### ISSUE TITLE
MapCoord.match_axes_units does not return a MapCoord with units

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1953]
When using `MapCoord.match_axes_units` to get a `MapCoord` object from a `WcsGeom` geometry with energy units in the axes, the returned `MapCoord` object does not contain units in this energy axis.

I guess removing `value` at the end of the line below could solve this issue.
https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/maps/geom.py#L921

But... it rises a new one when calling `HpxNDMap._interp_by_coords`, since operations here are done on numpy arrays and not in `astropy.quantities`. In this case we could add `value` to `coords[ax.name]` in the lines below?

https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/maps/hpxnd.py#L350

https://github.com/gammapy/gammapy/blob/93b4238ae6a3c36e605f77eaa16b9def0692b34d/gammapy/maps/hpxnd.py#L353

**Comment by adonath** [comment]
@Bultako If I remember correctly I implemented the `MapCoord.match_axes_units` method as a temporary solution (there is a TODO comment in the code explaining this) to handle `Quantity` input for `Map` methods, which did not handle quantities internally. I just checked and indeed there is just a single call in `HpcNDMap.interpolate_by_coord()`. I thought there we other places, were we called this method as well. My suggestion would be, that we solve this issue in the general context of refactoring the `gammapy.maps` code to support `Quantity` uniformly in the API. So I'll put the 1.0 milestone for  now (even if I hope it can be done earlier...).

**Comment by Bultako** [comment]
Ok.
Sounds sensible.

**Comment by cdeil** [comment]
@adonath - Probably we should aim to have API changes well before v1.0, at the latest in v0.13 in July 2013, so that there is some chance to get feedback, and then the dev time before v1.0 is spent on polishing and cleanup. This is a small issue, but there's also #1805 and others assigned to v1.0 that should be put on earlier milestones. There will always be shuffle back and forth between the milestones, but to maybe help a bit I've added v0.12 and v0.13 just now and always put them at the mid of the month mentioned in the roadmap.

**Comment by adonath** [comment]
Meanwhile `MapCoord.match_axes_units` has been removed in.
