### ISSUE TITLE
Ignore NaN values in EnergyDependentTablePSF.table_psf_in_energy_band

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2008]
Since 8085117f9890cddd4769ef7fee66b5e742393989, `EnergyDependentTablePSF.table_psf_in_energy_band` no longer makes sure the computed psf values are not `nan`. This, I think, is because the psf values are now obtained using `evaluate` rather than `_get_1d_psf_values`, which checked for `nan` values and set them to zero. It can happen that the psf values are `nan` in some energy bins if they are queried at energies with zero exposure. Can we include a similar check in `table_psf_in_energy_band`, to make sure `nan` values are set to zero?

**Comment by adonath** [comment]
Thanks @lmohrmann for reporting this. I must admit I don't really like this hard-coded handling of `NaN` values, because it silently "fixes" computations, where you might want to know, that they are wrong, unstable or not defined. If possible, I'd like avoid it in Gammapy.

Can you alternatively fix it in your script "in place" using:

```
psf = EnergyDependentTablePSF()
psf.psf_values[np.isnan(psf.psf_values)] = 0
```

If this is a re-occuring problem, because we cannot avoid `NaN` values during the PSF export, than I would suggest to describe this in https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/irf_components/index.html#point-spread-function along with a proposal how to handle this during the evaluation of the exported PSF.

Does this sound reasonable to you?

**Comment by lmohrmann** [comment]
Thanks for the quick response, @adonath !

I think I actually agree with you, setting the `nan` values to zero is a bit dangerous. Your proposed work-around works, so that fixes the problem for me. However, we might still want to add a check to the `table_psf_in_energy_band` function, since that produces a PSF with `nan` values only if any of the energy bins contains a `nan`. Then, the `_compute_splines` function that is called at the end of `TablePSF.__init__` crashes with a cryptic error message and it's not clear for the user where the error actually occurs (took me a bit to find it...).

What do you think?

**Comment by cdeil** [comment]
Just to give my 2 cents: NaN values in IRFs, often at low energy, are something that has come up often. We have a guideline [here](https://docs.gammapy.org/0.10/development/howto.html#interpolation-and-extrapolation). I'm not sure how the current Gammapy code compares to that guideline. Initially we wanted to use the "very safe" option, but then moved to the "medium safe" option and I think in many cases even the "least safe". 

The problem is that it's an almost impossible problem: at the energy threshold the AEFF is very low, so very few MC events, so PSF and EDISP get extremely bad. As soon as any analytic function gets involved (like probably the PSF splines here) often NaN values occur. Actually the "least safe" option of  putting any PSF that doesn't result in NaN works well in practice. At least currently no-one in their IRF exporters applies safe cuts on IRF production, so IRFs always arrive with bad PSF and EDISP at low energy. Throwing an error and not giving the user a result is a bit mean. Telling users to add IRF modification hacks to their scripts is also not a good solution (99% of users should execute via high-level scripts or config file a year from now and we don't want to expose IRF fix options there).

@adonath @lmohrmann - proceed as you like here. I just wanted to mention that IMO putting the "least safe" option might be OK and the best in practice. Why exactly does the NaN value arise? Is it really something that @lmohrmann should fix in the IRF producer, or is it "normal" to get such IRFs and users asking for analyses in these energy bands?

**Comment by lmohrmann** [comment]
Thanks for looking into this, @adonath.

Your notebook on PSF denoising looks very interesting, seems to be a very promising idea!

I also agree with what you wrote about the quality of the IRFs - this should be the responsibility of the producers, but I guess at least at the moment we need to assume that the IRFs are not perfect and certainly not denoised.

Coming back to this particular example: in this case the `NaN` values were not part of the exported PSF but were produced by `irf.irf_reduce.make_mean_psf`, here:
https://github.com/gammapy/gammapy/blob/b01eaa076f0e54e0b2f659c4947662ba6ff21e07/gammapy/irf/irf_reduce.py#L89

So maybe the first thing to do is fix that line, since it's perfectly possible that the exposure is zero, no? Whether we want to add checks for the IRFs as they are read in directly is another matter then.

**Comment by adonath** [comment]
@lmohrmann I agree this line should be changed, it's bad that the `make_mean_psf` method creates `NaN` values, when there haven't been any before. I'll prepare a PR...
