### ISSUE TITLE
CompoundSkyModel does not work with MapDataset

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2090]
The `MapDataSet` does not seem to work when a `CompoundSkyModel` is passed to it. This is probably because a `CompoundSkyModel` has no attribute `skymodels`:

https://github.com/gammapy/gammapy/blob/a0eb1d926c78de3528d1707cf9fdeb22a9a62cc6/gammapy/cube/fit.py#L97

Perhaps the `CompoundSkyModel` should be removed?

**Comment by adonath** [comment]
Yes, you are right `MapDataset` does not work with `CompoundSkyModel`. If I remember correctly I already removed it from the public docs. I guess it's probably rather save to remove, because it was probably not really used by users as a stand-alone class, but only as a returned object by the `+` operator. I'd be in favour of removing it as well, but I'm open to other opinions.

**Comment by AtreyeeS** [comment]
I don't see any stand alone use for the `CompoundSkyModel`...
Rather, it is confusing to the user I think

**Comment by adonath** [comment]
Resolved by #2092.
