### ISSUE TITLE
Speed up mcmc_sampling tutorial

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2188]
As mentioned in #2186 I think we should spend a bit of time to speed up `make docs-all`, and specifically speed up the slowest tutorial notebooks.

The second slowest currently is this one:
https://docs.gammapy.org/0.11/notebooks/mcmc_sampling.html
```
INFO:gammapy.scripts.jupyter:   ... EXECUTING temp/mcmc_sampling.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 94.4 seconds
```

I didn't look yet, but probably one can just sample less or use better starting parameters, and bring down the execution time to <~ 20 sec?

Also, I think it would be nice to put `%%time` in the cells that take the most execution time, like we do in other notebooks - to help maintainers, but also users to see which parts of a given analysis are slow.

Probably it's this: suggest to put this line into a separate cell:
```
sampler = run_mcmc(dataset, nwalkers=8, nrun=500)  # to speedup the notebook
```

Another small thing: there's two headings on plotting the results right after each other, one of the two should be removed.
https://nbviewer.jupyter.org/github/gammapy/gammapy/blob/master/tutorials/mcmc_sampling.ipynb#Plotting-the-results

I think model parameters are now exposed as attributes on the model instance?
Accessing parameters from the global parameter list on the dataset is error-prone and should be avoided.
```
dataset.parameters["lon_0"].frozen = True
```
So code here should be polished a bit: https://docs.gammapy.org/0.11/notebooks/mcmc_sampling.html#Define-priors

@facero - Are you available to have a look and send a PR for this in the coming weeks? If no, I could attempt it.

**Comment by cdeil** [comment]
@facero - Thanks for taking care of this in v0.13 cycle!

**Comment by facero** [comment]
I've opened a PR #2243 that bring execution time down to ~25sec. With less than that the contours get really ugly and same points it says somehting like "not enough point to draw contours".
I've fixed the two headings stuff.
Concerning the `%%time`, I had issues in the past and this is a known bug that when executing a `%%time` the output of that cell is not in memory. So at next cell the sampler is undefined. 
I think in the latest Ipython this has been fixed but several persons might still be on the old version. This is a very nasty bug and it took me some time to understand that this was due to `%%time`.

Concerning model parameters do you mean to replace `dataset.parameters` with `model.parameters` Something like :
`sky_model_simu.parameters['sigma'].frozen=True`  ?

**Comment by cdeil** [comment]
@facero - Thanks!

We use `%%time` already in many other notebooks, we should use it in this one as well. The ipython issue is fixed, and in the conda envs we ship for dev and users we use a good version. I think it's OK, would prefer to continue using it, as opposed to remove it everywhere for a few months.

For the other suggestions - I'll need to have a closer look at the notebook. Assigning this issue to myself for now. (but if you want to do any edits, feel free to send a PR any time).

**Comment by cdeil** [comment]
I'm closing this issue, done by @facero .
I did open a new one with different suggestions: #2304.
