### ISSUE TITLE
Fix Naima model evaluate_error

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2190]
Error evaluation is currently not implemented for the NaimaModel spectral model. The base class method, `evaluate_error()`, has been overridden in PR #2161 to raise `NotImplementedError`.
The issue comes from the fact that:
- naima [radiative models](https://github.com/zblz/naima/blob/master/naima/radiative.py) require evaluation on quantities, while
- the `evaluate_error()` method in the base class is built around the `uncertainties` package, that does not support quantities.

A workaround for this could for example involve the use of the `astropy.uncertainty.distributions` [package](https://github.com/astropy/astropy/blob/master/astropy/uncertainty/distributions.py), that allows to define normal distribution for parameters and fully supports quantities. This issue will somehow need to be fixed, if a consistent support for naima models is to be achieved.

**Comment by cdeil** [comment]
@luca-giunti - Thanks for bringing up this issue.

I'm pretty sure we could make an uncertainties-based solution work for these spectral models, one can always strip units to have Numpy arrays, do a computation, and then re-attach them after.

But I think maybe instead of adding to and improving our uncertainties-related code, we should look into whether we can't get a generic solution that doesn't use the uncertainties package.

Please have a look at #2255 and consider contributing there (especially to the first question / section).

**Comment by cdeil** [comment]
@adonath @luca-giunti - would changing `evaluate_error` for spectral models to only use `uncertainties` internally, not in the inputs / outputs help? Can you try?

**Comment by cdeil** [comment]
@zblz - if you have time to have a look at #2255 or this issue and give a recommendation how to best interface with emcee / sampling, that would be very welcome.

**Comment by cdeil** [comment]
I'm re-opening this issue for now so that we don't forget.  @luca-giunti - Can you send a PR with the test you implemented yesterday?

**Comment by adonath** [comment]
Fixed by #2623.
