### ISSUE TITLE
Pulsar and SimplePulsar

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2211]
In `gammapy.astro.source` we have [Pulsar](https://docs.gammapy.org/0.12/api/gammapy.astro.source.Pulsar.html) and [SimplePulsar](https://docs.gammapy.org/0.12/api/gammapy.astro.source.SimplePulsar.html) classes.

We used inheritance `Pulsar(SimplePulsar)` in a bad way, putting properties on the base class and methods on the derived class.
```
gammapy/astro/source/pulsar.py:85:4: W0231: __init__ method from base class 'SimplePulsar' is not called (super-init-not-called)
gammapy/astro/source/pulsar.py:111:4: W0221: Parameters differ from overridden 'luminosity_spindown' method (arguments-differ)
gammapy/astro/source/pulsar.py:170:4: W0221: Parameters differ from overridden 'tau' method (arguments-differ)
gammapy/astro/source/pulsar.py:183:4: W0221: Parameters differ from overridden 'magnetic_field' method (arguments-differ)
```

First question is whether we should remove this completely from Gammapy.
-> It's an option, but I would suggest we keep it and clean it up.

If we keep it, the question is how to change it: probably a single class with good defaults is possible to represent all use cases of the current two classes?
-> I haven't thought about this yet, don't have a detailed proposal yet.

@adonath - Thoughts?

**Comment by adonath** [comment]
I've just taken a look at the code again. The `SimplePulsar` is basically a calculator class for a pulsar  spin-down model. I.e. to compute `tau`, `magnetic_field` and `luminosity_spindown` from P and P_dot. As far as I can tell there is no point in introducing inheritance here, because all methods are overwritten in the sub-class anyway. So my proposal would be to just remove the inheritance and maybe re-name the `SimplePulsar` or maybe split it into separate methods.

**Comment by adonath** [comment]
To clarify: I think both classes are useful, but the use-cases are totally different. The `Pulsar` object implements the spin-down model starting from "birth" parameters. This is used for population synthesis. The `SimplePulsar` is rather used as a "pocket-calculator" for pulsar measurements. I think its functionality would be best attached to a `SourceCatalogATNFObject`, which doesn't exist (yet). 

I think it's not really possible to merge the functionality of the classes, because for the `SimplePulsar` the true age is never known and one would have to introduce some complicated logic whether some attributes exist or is derived from other existing properties. As I explained above it's also not reasonable from a use case perspective. So if you want to go ahead with the clean up I'd probably just delete the `SimplePulsar` and re-introduce the functionality with a `SourceCatalosATNFObject` later.

**Comment by cdeil** [comment]
@adonath - thanks for the comments.

I'm -1 on moving this to `gammapy.catalog`, having similar functionality in `gammapy.astro.source` and `gammapy.catalog` is hard to discover and maintain, and also not all pulsar info comes from ATNF. If we get pulsar functionality in `gammapy.catalog` (which I doubt, we should limit the scope, and PSR is borderline), then `SourceCatalogATNFObject` could import and use a pulsar class from `gammapy.astro` and use it to do a pulsar-related computation.

I'm assigning this to myself. I'll have a look and see if I just delete `SimplePulsar`, or if it's still useful somehow, make it independent of `Pulsar`, i.e. put a solution without inheritance.

**Comment by adonath** [comment]
As I wrote before the use-cases are completely different, so I just removed the inheritance in https://github.com/gammapy/gammapy/commit/9ac53e63362f0ce49252d111beb5ce709287400e
