### ISSUE TITLE
Data model and naming conventions for on / off datasets

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2252]
In #2250 I removed the `PHACountsSpectrum` class and (preliminary) introduced `.backscale` and `.backscale_off` on the `SpectrumDatasetOnOff`. I think it's clear, that we don't want do keep the names of the attributes, but rather change to something more common in VHE astronomy. In https://docs.gammapy.org/0.12/stats/index.html, we already introduced a naming convention for the quantities involved in an on / off analysis. I could just rename `backscale` to `a_on` and `backscale_off` to `a_off`, but even when those short names are useful in formulae, I don't particularly like it as names for data members, because they are not self-explaining.  For the same reason we probably use `counts` instead of `n_on` and `counts_off` instead if `n_off`. I'd prefer some thing more verbose for `a_on` and `a_off`, as well.

The second related question is which internal data model we want to choose for on / off analyses (independent of the serialisation). Currently the `backscale` is always set to unity, while `backscale_off` is set to `1/alpha`. This is also what is recommended [here](https://gamma-astro-data-formats.readthedocs.io/en/latest/spectra/ogip/index.html#pha). In this sense an internal data model purely based on `alpha` would be sufficient and simpler. But this probably does not generalise to map based datasets...

Currently we also store `livetime` and `aeff` separately in the `SpectrumDatasetOnOff`, while it could also be combined in an `exposure` attribute, as we have for `MapDataset`.

I guess a question related to this is whether `Dataset` becomes the single central data container for everything or stays just the data class for likelihood based analysis.

**Comment by cdeil** [comment]
Suggest to clean up our code to follow the suggestion here: https://docs.gammapy.org/0.12/stats/index.html

I.e. keep `a_on` and `a_off` separately, not just `alpha = a_on / a_off`. This is really well established in previous codes and the literature, and it really makes certain operations like stacking runs or grouping energy bins easier than if you write everything in term of `alphas` and other quantities.

If there is a good proposal with a better name than `a_on` or `a_off` we can discuss, but I would suggest to go ahead and clean up to use `a_on` and `a_off` in the meantime (project-wide variable name refactorings are not that bad with e.g. PyCharm).

I think I'm -1 to try and get consistency between `n_on`, `counts_on` or `counts`. In stats functions I think having `n_on` is pretty good, but as a map attribute probably `counts` is better as-is?

I'm +1 to go towards a data model which uses `exposure` and time only stored in meta or GTI, to be parallel with maps. This makes our stacking code more uniform and docs easier, as apposed to having `exposure` as data member in one case and `area` in the other.

@registerrier - Maybe you can chime in here what you think? And then @adonath - you post again with a concrete proposal what changes to make? And then once we agree the editing / cleanup can go ahead?

**Comment by registerrier** [comment]
I am +1 to have the explicit ON and OFF acceptances, `a_on` and `a_off`, rather than `alpha` only.  I think exposure is a bad term because it confuses with the exposure defined as `time * area`. So a verbose version could be `acceptance_on` and `acceptance_off`. This is pretty long, but most likely rarely accessed directly by a user.

Note that I think they probably should not be relative values, as is the case now, i.e. `a_on=1` per convention. If someone decides to apply some energy dependent integration radius (as is used to define CTA sensitivity), we should keep track of the acceptances per energy bin. The solid angle of the region is probably a good guess. Or if we don't explicitly track the `livetime_on` and the `livetime_off`,
it could be `solid_angle * livetime`. 
Note that this is the only way to keep the `alpha = a_on/a_off` link. Otherwise we have to assume that livetime is the same for `on` and `off`

**Comment by adonath** [comment]
My proposal here would be to just rename `backscale` to `acceptance` and `backscale_off` to `acceptance_off`. So for the datasets we use the more verbose terms `counts`, `counts_off`, `acceptance`, `acceptance_off`, `npred`, `npred_sig`, `alpha` and `background`. I would propose to extend the table here for an additional column https://docs.gammapy.org/0.12/stats/index.html.

Once we keep track of the GTIs in a `.gti` attribute, we can also get rid of the `livetime` attribute and change the internal data model from `aeff` and `livetime` to `exposure`. This makes it consistent with the `MapDataset`.

**Comment by cdeil** [comment]
@adonath - Sounds good. I would suggest to use `acceptance_on` instead of just `acceptance`.

With `acceptance` there was endless confusion how it compares to `exposure` and `background`, and while not helping much, I think calling it `acceptance_on` and `acceptance_off` will make it clear that this "acceptance" is something we only use when it comes to on / off measurements.

**Comment by adonath** [comment]
I added a "Dataset attribute name" column to the stats overview table in https://github.com/gammapy/gammapy/commit/a1bd7e317b76779db62c90ac415a0ca6b4b52321.

**Comment by adonath** [comment]
Rename was done in #2284.
