### ISSUE TITLE
Implement an interactive parameter editing

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#2253]
Following today's discussion at the gammapy dev. I managed to get a proof of concept of editing the model parameters interactively in the notebook with [ipysheet](https://ipysheet.readthedocs.io/). It can be very useful when analysing a region with multiple sources. The nice thing is that you can sort by frozen/free param which is very useful.

A proof of concept minimal working example is here:

```
from gammapy.spectrum.models import PowerLaw
from gammapy.image.models import SkyPointSource
from gammapy.cube.models import SkyModel
from gammapy.utils.fitting import Parameters

def edit_interactive(sky_model):
    
    import pandas as pd
    from ipysheet import from_dataframe, to_dataframe
    
    model_dict = sky_model.parameters.to_dict()
    df_model=pd.DataFrame(model_dict['parameters'])

    sheet = from_dataframe(df_model)
    display(sheet)
    
    return sheet
    
def sheet_to_model(sheet):
    dict_sheet = to_dataframe(sheet).to_dict()
    model_dict_=[]
    for i in range(sheet.rows):
        dict_={}
        for k in dict_sheet.keys():
            dict_[k]=dict_sheet[k][str(i)]
        model_dict_.append(dict_)

    model_dict={'parameters':model_dict_,'covariance': None}

    sky_model.parameters = Parameters.from_dict(model_dict)
    
    
    return sky_model


spatial_model  = SkyPointSource(lon_0="50 deg", lat_0="40 deg", frame="icrs") 
spectral_model = PowerLaw(index=3, amplitude="1e-11 cm-2 s-1 TeV-1", reference="1 TeV")
sky_model = SkyModel(spatial_model=spatial_model, spectral_model=spectral_model)

#You can sort frozen/free param by clicking the header of any column
#Edit the value param, not the scale or factor
sheet = edit_interactive(sky_model)

#then in a separate cell
sky_model = sheet_to_model(sheet)
print(sky_model.parameters['lon_0'].value)

```

It's still quite some work to have a fully functional implementation but I leave this here for futur reference if we want to implement it one day and for you to try.
Due to the formatting of small numbers (e.g. 1e-11) shows 0 for amplitude but I've seen that this can be changed. Also cells can be read-only, colored, etc

**Comment by adonath** [comment]
Thanks @facero! I agree this looks interesting and is certainly a more convenient API to work interactively with parameters. I could even imagine adding this e.g. as `Parameters.edit_interactive()` or a similar method to Gammapy.

**Comment by cdeil** [comment]
I think a model editor is a good idea. Suggest to attach it to the Model or Models class, note the Parameters class, because there you have the relevant info, whereas Parameters doesn't know about the model.

It's not high priority really. On the other hand, having "heavy users" or the Parameters and Model API like serialisation or model editor is a useful way to flesh it out, in that sense it is useful to have that soon.
If anyone starts with this, I strongly suggest to make a small minimal prototype and we merge it in, instead of developing it "on the side" with the goal to send a PR "next year".

@facero - At the moment this is assigned to you and v0.15, in November. Please comment in the next days if this is something you want to work on soon, or if we should move this to the v1.1 milestone which is our label for "will work on next year". Either way is fine.

**Comment by cdeil** [comment]
I just saw https://github.com/pandas-profiling/pandas-profiling - a nice example how to generate (slightly interactive) HTML output reports in Jupyter. I think this could be nice for models, but also e.g. for datasets, to see which datasets are present, how much memory they use, how many models and model parameters they have, ...). There could be benefit to make the str and HTML representation similar for datasets (x-ref #2234). There's also [panel](https://panel.pyviz.org/index.html). And JupyterLab has JSON rendering and editing built in (see [here](https://jupyterlab.readthedocs.io/en/stable/user/file_formats.html#json)).

Overall I now think a flat table of parameters is not a good representation, since models are usually a bit hierarchical (spectral, spatial, temporal parts), and sometimes really hierarchical (e.g. compound models, like Naima or absorption) One example to consider could be the [Fermi-LAT model editor](https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/images/latGrbAnalysis/LAT3_modEd.png) - if one just re-builds functionality in a new technology (JupyterLab in our case), it's often much easier and quicker than to come up with a good design.

**Comment by adonath** [comment]
There is now an example for this here https://github.com/gammapy/gammapy-recipes/pull/3.
