### ISSUE TITLE
Use Algolia DocSearch for Gammapy docs

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#2283]
I suggest to use [DocSearch](https://community.algolia.com/docsearch/) instead of the build-in sphinx search functionality for the gammapy online docs. 

You can test how the search window behaves with DocSearch [here](https://reactjs.org/docs/getting-started.html)

I've recently done this for another website so I'd be willing to take over the task. It's not a big deal, you basically have to register on the DocSearch web page and they scrape the website for you and send you a piece of JS code that you have to inject to the website. I already contacted them and they'd be willing to support gammapy.

Oh I forgot to mention - it' free ...

**Comment by cdeil** [comment]
@joleroi - Thanks for the suggestion!

Do you have an example of a Python Sphinx docs project, how the results look there?
I guess just trying it out and seeing what it looks like in a PR and how much better it is to what we have now is quite some work for you? However, I trust that what they deliver is good, probably we can just assume that. That's the advantage.

---

My main concern with putting this for the Gammapy docs is user privacy - probably what they do is to track users. That's a discussion we should have. E.g. it's very common to 
 have https://docs.readthedocs.io/en/stable/guides/google-analytics.html on documentation pages, e.g. Astropy does have this, and they use the analytics sometimes to see how many users they have and what users look at. That's extremely valuable. But also it's bad that Google tracks so much and depending on how Gammapy is used in the future by projects it might even be illegal to track users.

There's also the concern that this introduces another cloud service that could go down or break in the future. But presumably they have super-high uptime, and one could fall back to the Sphinx search we have at the moment? So that's probably fine.

---

An alternative to this DocSearch is to have a custom Google search to have better search results. That's e.g. what https://scikit-learn.org/stable/ does.

Either way - the main question is: take better search results and analytics, at the cost of user tracking?

**Comment by cdeil** [comment]
@joleroi - we discussed it. Others don’t seem concerned about user tracking at all. Let’s do it!

**Comment by joleroi** [comment]
@cdeil thanks for your thoughts.

I was going to suggest that I open a PR for you to test the new functionality and then talk about user tracking again (after you've seen the shiny feature). But if you already agreed on this - fine. I'll proceed.

**Comment by cdeil** [comment]
Yes, let's try it out.

If we get a bit of user tracking anyways, it might be nice to just get all the benefits we can and to have analytics about users, i.e. how many people visit gammapy.org and docs.gammapy.org and which docs pages they look at?

So what you're adding is specifically a solution for search, but not an analytics for all docs pages?
If so, do you know if it's possible to add Google Analytics in addition to our docs?
This is something I could set up, I forgot but apparently I had already added this to gammapy.org, so I could extend this to docs.gammapy.org as well.

**Comment by cdeil** [comment]
AlgoliaSearch was added by @joleroi in #2316, and following it there's quite some discussion on pros and cons there. Let's continue here now since this is an open issue.

We'll have the v0.14 release in the next days, and important tutorials coming up in the next weeks, so we need to resolve this question what to put for search. (Keep or improve a bit Algolia, roll back to Sphinx, something else). It's probably not a release blocker, we can also just ship as-is and continue discussing in the coming weeks.

I looked around a bit. Most projects use the build-in Sphinx search. It does use an index that's pre-built on `sphinx-build`, and JS to query it and show results. I don't know why it isn't efficient, most likely because we have a lot of API autodoc (could possibly be reduced and improved, see #2221). As you know, it has deficiencies (no results as you type, layout of results not great), but it also has big advantages (self-contained, no extra maintenance, can be tested and used locally and offline, fully open-source). There are some improvements possible, e.g. https://github.com/sphinx-contrib/sphinx-pretty-searchresults -- I couldn't find any "search as you type" popup plugin (except https://pypi.org/project/sphinxcontrib-lunrsearch/ which I didn't try yet, but doesn't seem widely used.

The next most-used thing is RTD, which has an open-source solution https://readthedocs-sphinx-search.readthedocs.io/en/latest/ built on ElasticSearch https://docs.readthedocs.io/en/stable/development/search.html . It's probably a great option if we went back to RTD, but not something we can use from GH pages (we certainly don't want to maintain or install Elasticsearch).

There's also the option to use Google search. See https://www.sphinx-doc.org/en/master/faq.html#using-sphinx-with (scroll a bit down), or see https://scikit-learn.org as an example. For https://scikit-learn.org I think the search results are good (Google quality), but there's ads and the layout isn't customised, overall it looks weird.

Also found this which I didn't read yet but it's probably relevant to this discussion: https://blog.readthedocs.com/seo-for-technical-docs/

Thoughts?

**Comment by cdeil** [comment]
@joleroi - I'm sorry to have wasted your time here, but overall my suggestion is that we should take Algolia search out again now (v0.14 release already delayed, has to happen on Monday).

We discussed this briefly in the Gammapy call this morning, and I think @adonath and @Bultako as the other Gammapy docs maintainers might feel the same way, that it would be better to remove this.

It's not an easy decision, because we all like the "search as you type" feature and slick JS results popup, and we believe that they can overall give better search results than the Sphinx built-in search.

But maintaining this isn't easy. We can't test locally or before a release, basically one has to set the version to the next stable release in the JS in the Gammapy repo, then release, and then they index those pages and the search should work. That's not a good workflow. Also, we would have to transfer the Algolia account to me and then to someome else in the Gammapy team and then to CTAO, so that we can see the analytics. And we already have Google Analytics for https://gammapy.org/ and no-one has time to look at those already, then would have a second analytics source where we can see how many users we have and what they look at. And there's just technical stuff to figure out, e.g. currently the Algolia CSS seems to interact badly with our existing CSS, i.e. it's no longer possible to scroll down in the sidebar and reach some sections of our docs e.g. from [here](https://docs.gammapy.org/dev/changelog.html). So basically, we long for simpler docs setup, and want to go that way, even at the cost of not getting a nice feature.

@joleroi - Thoughts?
Would you be willing to send a PR to roll this back?

Intrinsically there's no reason why Sphinx shouldn't be able to offer great search. We could add [this](https://github.com/sphinx-contrib/sphinx-pretty-searchresults) now as a minor improvement, and keep on the lookout for other features and plugins to get better Sphinx search in the future.

**Comment by joleroi** [comment]
I don't think these are strong points (have you ever tested the search locally before a release?) but after all it's not my decision. I will revert the commits that introduced the Algolia serach.

**Comment by cdeil** [comment]
> have you ever tested the search locally before a release?

Yes. Over the past year, I have spent (wasted?) many hours with Gammapy Sphinx docs issues, a few of them search related (see e.g.  #1184 or #2010). Things break as Sphinx or Algolia evolve - it's another moving part.
