### ISSUE TITLE
Improve data and notebook index file access for dev version

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2337]
In #2332 the dataset index file was changed to local, to make it possible to work on datasets and test locally or in a give pull request.

A temp fix for the issue described in https://github.com/gammapy/gammapy/pull/2332#issuecomment-527340825 is in 622d1a8814efa5e2980ac589b50fd10bd24b31ea, for now CI always runs in the source folder.

There is still the same problem for the notebooks index file:

https://github.com/gammapy/gammapy/blob/622d1a8814efa5e2980ac589b50fd10bd24b31ea/gammapy/scripts/downloadclasses.py#L15-L17

For the dev version, a request to Github master is made.
This is bad because it means that a dev can't test locally, and also CI can't test pull requests where the notebook index changes.
Instead, the local version should be used.

This is a reminder issue to make it better somehow. @adonath and I discussed a bit offline, and the only solution we didn't come up with a great solution yet, only the ones mentioned in https://github.com/gammapy/gammapy/pull/2332#issuecomment-527340825 which are non-ideal.

**Comment by Bultako** [comment]
I do not see the problem when testing notebooks in PRs because actually a local index file `tutorials/notebooks.yaml` is used for testing notebooks, not the one in github master. 

https://github.com/gammapy/gammapy/blob/8c2f79aa051ae1bdde722840b0c492d560a4f678/gammapy/utils/tutorials_test.py#L17

Anyhow, I'd be in favor of making the index files part of the package-data, maybe moving them to `gammapy/scripts/config/` folder. 

https://github.com/gammapy/gammapy/blob/8c2f79aa051ae1bdde722840b0c492d560a4f678/setup.cfg#L58-L62

Also, I would modify `gammapy download` to use the local index files if no `--release` flag is specified in the command.

**Comment by Bultako** [comment]
This issue is not relevant anymore, since https://github.com/gammapy/gammapy/pull/3211 we do not rely on index files for notebooks. And for datasets neither since we test with the master tarball of the `gammapy-datasets` repo.  
Closing.
