### ISSUE TITLE
Possible improper usage of `compute_lima_image`

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2403]
With the current implementation `compute_lima_image` takes as argument any possible `Kernel2D`. This can yield incorrect results. One can apply Li & Ma only by summing counts, so that applying convolution is valid only if the kernel is made of `1`and `0`. 
The only valid kernels should therefore be `Tophat2DKernel`, `Ring2DKernel`  and possibly `Box2DKernel`.

I am not sure there is a strong use case for other kernels than `Tophat2DKernel`. So that the only parameters should be `compute_lima_image(n_on, n_off, a_on, a_off, correlation_radius="0.1 deg")`.
Besides avoiding incorrect results if someone was to use a `Gaussian2DKernel`, this allows to avoid requiring to define a kernel in pixel coordinates.

There is one class that uses `compute_lima_image`, with any possible kernel, the `KernelBackgroundEstimator`.  The latter can still function with only a tophat kernel, so I propose to adapt it as well to use only a correlation radius. If not the significance it computes is incorrect.
 
Opinion @adonath ?

**Comment by cdeil** [comment]
I think it's also possible to have a PSF or PSF-convolved source template "matched filter" weights kernel and to use that, and to get a very fast and close approximation to what likelihood amplitude fitting / Li&Ma gives?

- https://www.aanda.org/articles/aa/full/2006/30/aa3498-05/aa3498-05.html
- https://www.aanda.org/articles/aa/full_html/2009/09/aa11311-08/aa11311-08.html

I see that currently we call `kernel.normalize("peak")` (see [here](https://docs.gammapy.org/0.13/_modules/gammapy/detect/lima.html#compute_lima_image)), which normalises to a peak value of 1 (see [here](http://docs.astropy.org/en/stable/api/astropy.convolution.Kernel.html#astropy.convolution.Kernel.normalize)). That's probably not useful for any application, we should remove that and let the caller decide the kernel normalisation?

My guess is that changing Li & Ma to only a "correlation radius" argument might be going in the wrong direction, and instead we should aim to create a more consistent API with TSMapEstimator and also keep the option to have any kernel shape for the "matched filter" method in Steward?

(I'm not sure, other options are to do what you propose, or to just delete those two functions and show an example, since the building blocks are map correlate and `significance` after correlation, i.e. both present in Gammapy)

**Comment by registerrier** [comment]
Well I think that the function should be doing what it says it is doing. You would not apply Li & Ma with any kernel.
We can add other specific function for matched filters if needed.

I propose to only expose to users a Li & Ma with a correlation radius, but still using a function that uses any kernel with the check you propose @adonath . The latter would be used in the `KernelBackgroundEstimator`.

Would that be an OK approach?

**Comment by cdeil** [comment]
@registerrier - What would the signature of the second function be? One contains only 3 lines and wraps the other? I'm -1 on this - the larger our API, the harder it is to teach and learn and use.

**Comment by registerrier** [comment]
The function exposed to users would be:
`compute_lima_significance(n_on, n_off, a_on, a_off, correlation_radius="0.1 deg")`

the 'private' one could be:
`_compute_lima_significance_kernel(n_on, n_off, a_on, a_off, kernel)`

I insist that the API as we have now is a recipe for very incorrect results. We cannot keep it as is. Any usage of the Li & Ma formula with an improper kernel will yield silently wrong results.

**Comment by cdeil** [comment]
@registerrier - I agree we should change something and improve.

Currently I think it would be better to have one function with proper kernel normalisation settings that supports the common use cases mentioned in the Stewart papers I cited above. They are not only of interest within Gammapy, so a second private function IMO isn't ideal.

Also the fact that `TSMapEstimator` is a class and the very similar `compute_lima_significance_image` is a function, and one uses "Map" and the othere "image" isn't great API. Suggest to have it as goal to have a bit larger cleanup of https://docs.gammapy.org/0.13/detect/index.html#module-gammapy.detect than just to change this one argument vor v0.15. @registerrier or @adonath - you make a full proposal for cleanup, we discuss a bit, and then do it within the next 2 months.

**Comment by registerrier** [comment]
This is now partly solved with PR #2762 . The `LiMaMapEstimator` now takes a dataset, a radius and applies Li & Ma estimation.
The question of the `TSMapEstimator` and its relation to the `LiMaMapEstimator` is another one. I propose to close this issue for now.
