### ISSUE TITLE
Unify coordsys and frame handling between maps and models

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2437]
Currently we handle coordinate systems / frames in two different ways in Gammapy:

- In `gammapy.maps` we have the `coordsys` keyword with allowed values of `CEL` and `GAL`.
- In all other parts of Gammapy we are compliant with the `SkyCoord` API and use a frame keyword. 

This inhomogenity even lead to bugs like #2402. My proposal would be to adapt the `Map` API to use the `frame` keyword as well. Internally we just completely rely on things like `SkyCoord.to_pixel(wcs)` and `celestial_frame_to_wcs` and leave the coordinate handling 100% to astropy. This way we also get rid of functions like `skycoord_to_lonlat` or `coordsys_to_frame`.

I guess alternatively we could introduce `coordsys` in other parts of Gammapy and always restrict to `CEL` and `GAL`. While I can see the motivation for this, I think it complicates our code and API, because we deviate from the established astropy.coordinates API.

 I'm happy to take over this task for v0.15.

What do you think @cdeil and @registerrier?

**Comment by adonath** [comment]
One further comment: this also opens up the path to evaluating models in different coordinate systems. E.g. analytical background models could evaluated in the nominal system of an observation, why the source is evaluated on the sky.

**Comment by registerrier** [comment]
I am +1 on following the astropy `frame` keyword as much as possible. 
Having the ability, in the future, to use specially designed frames such as the nominal system would make the issue of handling IRFs in the correct frame much easier.

I have difficulties seeing how much work this represents though. How much is feasible before v0.15?
In particular, does this means that `MapCoord` must now become an array of `SkyCoord` with other quantities? This would significantly change the API, right?

**Comment by adonath** [comment]
@registerrier I think we can find a reasonable compromise in the sense, that we keep `MapCoord` mostly as is i.e. `MapCoord.lon` and `MapCoord.lat` are `Longitude` and `Latitude` objects, while `MapCoord.coordsys` get's renamed to `MapCoord.frame` and becomes an astropy frame object.
The convenience `MapCoord.skycoord` remains and still returns a `SkyCoord` object. Note that the transition to Quantities we have already done in #2344.

**Comment by registerrier** [comment]
OK. Seems good then.

**Comment by adonath** [comment]
On the other hand, as the current system works, it might not be a priority for v1.0...

**Comment by cdeil** [comment]
I'm +1 to improve this, but yes, it needs some discussion first of all how it should work (e.g. where SkyCoord objects are used internally as data members and the API, especially during model & likelihood evaluation, and we need the same discussion for Time and temporal models), and then an estimate what could be done in a limited number of days of your time @adonath .

For good performance it's important that no frame transforms occur on each model evaluation, only  in the data reduction or fitting setup phase. But that could be achieved in different ways, with or without using `SkyCoord` objects, and with or without full support for frames other than "icrs" and "gal". A simple change would be to move the handling of "CEL" and "GAL" only to the maps FITS I/O 
in one function for legacy support of Fermi ST (if needed at all), and otherwise to only have "icrs" and "gal" in gammapy.maps; that would be a small cleanup.

**Comment by adonath** [comment]
Addressed in #2709.
