### ISSUE TITLE
Plotting the error  on the Spectral Model using the High Level Analysis

### ISSUE THREAD

**Issue by JouvinLea** [gammapy/gammapy#2503]
Hi all,
As I mentioned to Regis, I tried the high level interface for all of my Gammapy analysis.
I am for the moment only doing 1D spectral analysis.
It is not possible to get the error on the model in the plot with the _analysis.flux_points.peek()_ since _analysis.model.parameters.covariance_ is empty. The covariance on the spectral parameters is stored in _analysis.fit_result.parameters.covariance._
For the moment to have the error plot on the models, I am doing:
_model = analysis.flux_points.model
model.parameters.covariance = analysis.fit_result.parameters.covariance
model.plot_error(ax=ax_sed,energy_range= [0.07*u.TeV, 10*u.TeV])_

And this is clearly ugly...

I think there is several problems here:
- I don't know from the high level interface how to have this _analysis.model.parameters.covariance_ not empty after calling _analysis.run_fit()_.

- in the method _analysis.get_flux_points()_, there are those two lines: 
        model = self.model[source].spectral_model.copy()
        self.flux_points = FluxPointsDataset(data=fp, model=model)
so analysis.model and analysis.flux_points.model are different and this is not easy to understand as a simple user. You are thinking if I modify the analysis.model, it will also be the case for the one used in the flux point computation.

- A complete misleading name of method is this one: analysis.get_flux_points(). It returns an object `FluxPointsDataset ` containing a model but this is absolutely not obvious for a standard IACT user. If I see get_flux_points(), I expect to only get `FluxPoints` object. I would propose that this get_flux_points() method return a `FluxPoint` object. And if we want to plot more than the simple Fluxpoint.plot() method, we add a method in analysis named for example plot_flux_points() that will also plot the spectral model etc...

**Comment by facero** [comment]
Karl reported to me that he had a similar issue when doing trying to plot the spectral butterfly. The workaround was of the same sort:
```
spec = analysis.model['crab'].spectral_model
spec.parameters.covariance = analysis.fit_result.parameters.covariance[2:5,2:5]
spec.plot_error(energy_range=[1,10]*u.TeV)
```
Somehow the covariance is not copied back to the spectral parameters

**Comment by cdeil** [comment]
I agree this is a very big usability issue, labeling it high-priority and assigning to v0.15 milestone.

The solution is to set the covar after estimating it not just in the results object, but in the model.
@adonath @QRemy - Agreed? Or was that controversial?

@adonath @QRemy and I also discussed options last week how to expose the covariance and parameter error information on sub-model-components and parameter objects. There the solution isn't obvious, but we'll make it better soon. My suggestion would be that we add `.parent` attributes to models and `.model` to Parameter objects, which get set when doing `analysis.model.component[3].spectral.parameters.covariance` so that the covar is directly available from any sub-model component. The alternative solution would be that we copy down covar information to the parts at the end of covar estimation. And yet another alternative would be that we offer a good API to copy covar for parts, but let the user do it explicitly.

**Comment by adonath** [comment]
What we currently have is the following pattern:
```python 3
crab_spec.parameters.covariance = results_joint.parameters.get_subcovariance(
    crab_spec.parameters
)
```
This is already an improvement to what we had before. @cdeil and @QRemy agreed to maybe pair-code on an automatic setting of the sub-covariances after the fitting on Monday. I'll keep the v0.15 for now...

**Comment by adonath** [comment]
Now the covariance tracking is done automatically and the plotting of errors works. Will close the issue.
