### ISSUE TITLE
Should LightCurveEstimator support overlapping time bins?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2647]
**Gammapy version**
The latest dev version

**Bug description**
`LightCurveEstimator` at present does not support overlapping time bins. This behaviour is enforced by the `_check_and_sort_time_intervals` which throws an error in case of overlapping time bins. 

**Expected behavior**
While I do not foresee any common use case for overlapping time bins, I am not sure it is completely bizarre to have something like this (eg: different times from LST and SST). 
Would it be better to leave the time selection to the user?

@registerrier @JouvinLea

**Comment by cdeil** [comment]
See [_check_and_sort_time_intervals code](https://github.com/gammapy/gammapy/blob/4f223a2cdbd04ffb1a2ca210e9a2082b28a7bc5e/gammapy/time/lightcurve_estimator.py#L159-L181), it is called on init [here](https://github.com/gammapy/gammapy/blob/4f223a2cdbd04ffb1a2ca210e9a2082b28a7bc5e/gammapy/time/lightcurve_estimator.py#L132), and this restriction is not mentioned in the docstring [here](https://github.com/gammapy/gammapy/blob/4f223a2cdbd04ffb1a2ca210e9a2082b28a7bc5e/gammapy/time/lightcurve_estimator.py#L72-L80).

+1 to simply remove this check and allow it. 

I don't think there's a strong use case for it, but there can be cases a user wants that (e.g. monthly light curves starting weekly, like a "moving average" flux), and overall I think we should build a minimal clean core first (see #2555 and #284) and then (only if really useful) add back such code (with proper documentation) that does input validation checks.

@registerrier - Thoughts?

**Comment by registerrier** [comment]
The time sort and check for overlap was introduced for various reasons:
- ensure a sorted light curve as output
- efficient distribution of datasets in time bins with only one time bin per dataset. 
In practice this avoids a light curve with bin to bin correlation, which I think is a desirable feature.  You can still perform a sliding average by calling the `LightCurveEstimator` several times.

@AtreyeeS raises indeed the possibility that we have two distinct measurements (e.g. MSTs and LSTs subarrays) covering not exactly the same bin. Precisely, the point here is to get only one flux measurement for that time bin, not 2.

I agree that the documentation should be explicit about what is expected. Note that it raises an error if the input is incorrect.

Note also, that removing it, requires so changes in the rest of the code, since the assumption that a dataset appears in only one time interval is no longer valid.

For the issue of gammapy-benchmark, you can change the GTIs on the fly as well, no?

**Comment by AtreyeeS** [comment]
Yes, avoiding bin-to-bin correlations is indeed important. 

> @AtreyeeS raises indeed the possibility that we have two distinct measurements (e.g. MSTs and LSTs subarrays) covering not exactly the same bin. Precisely, the point here is to get only one flux measurement for that time bin, not 2.

So if the user proceeds with different reduced datasets for different sub-arrays, then s/he has to run the `LightCurveEstimator` separately as well?

> For the issue of gammapy-benchmark, you can change the GTIs on the fly as well, no?

Of course the main repo should not be affected due to some weird way I chose to do the benchmarks. Closing this issue for now.
