### ISSUE TITLE
EBL absorption estimation wrong for z < zmin of the model

### ISSUE THREAD

**Issue by santiagopita** [gammapy/gammapy#2695]
**Gammapy version**
Dev version and 0.15

**Bug description**
Problem found by @jlenain : EBL absorption estimation wrong when z below zmin of the model (survival probability > 1).

**Expected behavior**
Survival probability should always be <=1 and converge to 1 at z=0

**To Reproduce**
```python3
from gammapy.modeling.models.spectral import Absorption, AbsorbedSpectralModel, TemplateSpectralModel
ebl_model = 'dominguez'
z=0.0000000001
absorption = Absorption.read_builtin(ebl_model).table_model(z)
absorption.evaluate(energy = 1 * u.TeV, norm = 1., tilt=1., reference=1 *u.TeV)
```
**Other information**
Problem due to extrapolation of the model for z<zmin of the model

![ebl_wrong](https://user-images.githubusercontent.com/25453995/71267591-4546ab00-234b-11ea-9e37-4404b66ba2a1.png)

**Comment by adonath** [comment]
In https://github.com/gammapy/gammapy/commit/0e0aba2fbaec5d32b2702c8fdf275f9f81ccd7b8, I changed the default behaviour to raise an error. I also added a `np.clip()` call to the evaluation to prevent the model "overshoots", when users for extrapolation by overwriting the interpolation parameters.

**Comment by adonath** [comment]
I realised there is a bit of problem with this solution, because one typically wants the extrapolation in energy but probably not in z. Currently there is no way of specifying different extrapolation behaviour per axes in the `RegularGridInterpolator` we use. I went back to the extrapolation default, but kept the `np.clip()` option.  This fixes this issue in a reasonable way...

@santiagopita Pleas comment if you prefer a different solution.
