### ISSUE TITLE
Crash of print(dataset) when there is no mask_safe

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#2736]
**Gammapy version**
V0.15

**Bug description**
print(dataset)
  File "/home/khelifi/MesProgrammes/anaconda3/envs/gammapy-0.15/lib/python3.7/site-packages/gammapy/cube/fit.py", line 129, in __str__
    mask = self.mask_safe.reduce_over_axes(np.logical_or).data
AttributeError: 'NoneType' object has no attribute 'reduce_over_axes'

Which is expected if self.mask_safe is None!

**Expected behavior**
No crash

**Proposal**
Add a test if self.safe_mask exists before making any operation on it!

**Comment by registerrier** [comment]
The issue is not only with `__str__`. Looking at the code, we see that `MapDataset.stack` and `MapDatasetOnOff.stack` also call `mask_safe` without checking properly. 

We can either:
- Create a `safe_mask` property that returns a `Map` with the correct geom full of 1. But this implies that a geom can be found.
- Add a `if .. else` statement in the missing cases. But it seems that we miss a general set of tests for the various combinations of existing or non-existing properties.

**Comment by adonath** [comment]
This specific issue is resolved, but let's keep it open as reminder for systematic tests...
