### ISSUE TITLE
Add telescope (sub-)array specification format converters

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#282]
In the future we should add a class to convert between various formats to store TELARRAY specifications and then re-think how to store this in observation lists. Note that the HAP-exported event list files have a TELARRAY extension (see https://gammapy.readthedocs.org/en/latest/api/gammapy.data.TelescopeArray.html).
Options:
- comma-separated values in a column in a CSV file. But this is not very user-friedly to edit in a CSV file.
- The HESS integer telescope pattern is also not very user-friendly and does not scale to the 100 CTA telescopes.
- A bitpattern 100010110101 would be another option, less human-readable than the comma-separated telescope numbers, but better to store in a CSV file.

**Comment by cdeil** [comment]
@mapazarr – Thanks for making the issue. I wouldn't be sad if you implement this while working on `gammapy.obs`, but otherwise I can also do it soon.

It's not clear to me if there should be an extra `TelescopePattern` or `TelescopeArraySubset` (or whatever a good name is) class, or if everything can / should be added to the existing `TelescopeArray` class.

Note that the telescope pattern is very important for background modeling, just today I saw a presentation in HESS stressing that point (see [here](https://hess-confluence.desy.de/confluence/display/HESS/HAP+Combined+Analysis+Documentation)).
So splitting the off runs by telescope pattern and comparing acceptance profiles is definitely something that should be doable after your GSoC work.

**Comment by mapazarr** [comment]
I see the importance of having the information of which telescopes participate in an observation, but the telescope pattern as in H.E.S.S. is not good for CTA: trigger pattern as a bit mask with an integer
variable: limitation of 32 bits (32 telescfopes), but CTA could have ~100 telescopes.
Maybe we should have a look to how [ALMA](http://www.almaobservatory.org/) and [ACS](http://www.eso.org/projects/alma/develop/acs/) do it?

**Comment by cdeil** [comment]
@mapazarr – We still need to support the HESS int telpattern, because it's so widely used and e.g. what you need to give to HAP in a runlist. But I agree it's not a good solution and should not be our internal storage format.

What format does the current TELARRAY FITS extension and the event list use?
(I know I could just look, but I don't have much time this week ... you're in charge now for `gammapy.obs` and I'll just give feedback.)

Maybe internally a Numpy array or Python list of ints would be a good format (if every telescope is identified via an integer), or a list of strings (if tels are identified in CTA via strings).

I'm pretty sure this has not been discussed in CTA, so :+1: to see what ALMA and ACS do or even what you like best (and then provide converter functions to a few other common formats that are used in HESS or convenient, like telpattern, bitpattern or comma-separated list of ints).

**Comment by cdeil** [comment]
This is probably something that will soon be implemented in `ctapipe`. Let's just wait on this one ...

**Comment by cdeil** [comment]
I'm closing this old issue. Most likely this is something that only needs to be dealt with in the CTA pipeline (ctapipe), not the CTA science tools (Gammapy).
