### ISSUE TITLE
Possible Problem with PSF desciption of PointSources

### ISSUE THREAD

**Issue by tunbehaun273** [gammapy/gammapy#2862]
**Gammapy version**
Different Analyses of PointSources have been performed on real Hess data as well as simulated CTA-1dc data in the versions v15, v16, v17 (the latest at the times). For the CTA data the analyses were done according to the tutorials on the gammapy website.  For the Hess data the background was fitted for each observation and the observations were stacked when their energy threshold was within the same energy bin (to avoid problems with the exposure stacking which does not take into account energy dependent masks).

**Bug description**
When looking at the spatial residuals of the CTA-1dc analyses (performed on the crab and on Markarian 421) the predicted counts are wider than the counts (see slides 2&3 in the attached pdf).
Both sources were simulated as PointSources so it is surprising that they look more confined than the npred which should follow the PSF in a radial profile. These features are not always visible as clearly if one has little statistics or just looks at the simple significance maps.
This problem was discovered when looking at the spatial extension of the crab (pdf slides 4&5). With the "normal" PSF (dP/dOmega) the counts are a lot wider than the PSF. A GaussianSpatial model doesn't give a good fit either (in contrast to the crab extension paper https://arxiv.org/abs/1909.09494 ). 

Experiments to export the PSF in dP/dr (linear binning without correcting for the solid angle) somewhat flattened the spatial residuals, however the PSF gets wider than the counts in this case which doesn't allow for any extension fitting.
Also the check on a real PointSource PKS 2155-304 didn't show a good agreement between counts and PSF.

**Expected behavior**
For the CTA-1dc data one would expect a good agreement between counts and npred in the radial profiles, as well as for PKS 2155-304. 

**To Reproduce**
If CTA-1dc data is available just perform an analysis on the Crab or Markarian 421 and plot the Li&Ma significance maps (use npred as background prediction) as well as radial profiles (with appropriate binning). I would guess any other source with enough statistics should also show some spatial residuals.
The pixel size for the CTA analyses were 0.02 deg, for the Hess analyses stdImpact was used with pixel size of 0.01 deg.

 
We are running out of Ideas what might cause this problem and would be grateful for input from your side!
[PSF_in_gammapy.pdf](https://github.com/gammapy/gammapy/files/4480128/PSF_in_gammapy.pdf)

**Comment by registerrier** [comment]
Thanks for the detailed feedback @tunbehaun273 !

We have to investigate where the issue might come from. My guess for the first issue  is connected with the definition of the `PointSpatialModel`. 
In the current implementation, to properly deal with the source position inside a bin the point source is smeared over 4 pixels. This inevitably broadens the source profile and should be visible for bright sources. The impact is directly linked to the bin size. So that reducing the bin size to 0.01 deg for the CTA data will reduce the effect.

We have to add an oversampling evaluation for sources with limited extent to properly deal with bin sampling effects. It is possible that the second issue discussed in your document is also due to such an effect.

We need a specific test on source extension and point source profile for the validation tests.

**Comment by tunbehaun273** [comment]
I tested this for the CTA Crab data and it indeed reduced the effect slightly for a 0.01 deg binning (upper figure for 0.02 deg and lower figure for 0.01 deg). So if this causes the problem I feel that it is strange that we see the opposite effect for the Hess data (counts are wider than the PSF here). In case we extract the PSF correctly in dP/dOmega (as it is written here https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/psf/psf_table/index.html#psf-table ) I would assume to also see the PSF wider than the counts, similar to what we see when extracting the PSF in dP/dr.

![Crab_radprofile_0 02deg](https://user-images.githubusercontent.com/60741323/79447647-75901480-7fe0-11ea-969b-d7b211e8d606.png)
![Crab_radprofile_0 01deg](https://user-images.githubusercontent.com/60741323/79447657-7a54c880-7fe0-11ea-939e-8966730de7ba.png)

**Comment by adonath** [comment]
Thanks for the issue report @tunbehaun273!

@registerrier I'd be very surprised if the issue was related to the way we evaluate the point source. The effect seems larger then just a single pixel. In a sense this 4 pixels methods just shifts the profile by a given sub-pixel fraction. I don't think it can really explain the larger ring artefacts in the residuals. If the issue was related to the 4 pixel method one would probably expect an x/y symmetric (and not radial symmetric) feature. To me it seems the shape of the profile is not correct. In the past (also for event sampling) most issues were related to a missing / additional Jacobian factor when transforming the PSF profile to a 2D PDF. Maybe we should investigate in this direction as well.

For the event sampling we added a self-consistency check here: https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/event-sampling/checks/psf_energy_check.ipynb It shows at least that the PSF is handled consistently between simulations and fitting in Gammapy, but of course not necessarily that it is correct. But I guess we should probably extend this tests a little bit. E.g. add the visualisation of the PSF kernels and compare for the Gaussian case.

Looking at the status of our analysis validation I would recommend to try to reproduce the issue first with the HESS DL3 DR1 data and CTA 1DC data in (https://github.com/gammapy/gammapy-benchmarks/tree/master/validation). At least for the 1DC data it should be possible with sufficient statistics. The first step is probably just adding residual maps (in energy bands?) to the result folders, which we haven't done yet and check those...

I'm adding @fabiopintore to the discussion here, as I know he has started validation of Gammapy against ctools. These issues should definitely also show up there.

**Comment by fabiopintore** [comment]
Thanks for including me.
Not sure about the cause of this issue, but I would also suggest to check the Jacobian terms of the transformation, which could be a suspect.
I started some validations of the gammapy event-sampler by analyzing the simulated data with Ctools. I considered, for now, only a point-like source (using the CTA-DC1 IRF for the simulations) but at a first glance I didn't encounter any particular issue. However, a deeper investigation may be needed.

**Comment by registerrier** [comment]
Indeed @adonath and @fabiopintore , I have also checked that the profile of the `npred` obtained for a point source convolved with a gaussian `PSF` is barely different from the actual PSF profile. What is the effect of changing the bin size on the CTA Mkr 421 example above @tunbehaun273 ?

One possible issue with the CTA Crab data is that at large offset, the extrapolation of the PSF is not exactly the same with the `MultiGaussPSF` and the `PSF3D`. At low offsets, there is little difference, but I have noticed different behaviors at larger ones. I can check that.

**Comment by tunbehaun273** [comment]
For the Markarian 421 example the features also got less with 0.01 deg bin size, however they are still there:
![Mrk421_radprofile_0 01](https://user-images.githubusercontent.com/60741323/79551969-b0ef1980-809a-11ea-8434-41791c17b45a.png)

For comparison the rad_profile with 0.02 deg bin size
![Mkr421_radprofile_0 02](https://user-images.githubusercontent.com/60741323/79551983-b482a080-809a-11ea-92b7-e225c1c40aeb.png)

**Comment by registerrier** [comment]
Here I show the effect of the projection to of a `MultiGaussPSF` to a `PSF3D` for CTA 1DC IRFs.

```
rad = np.linspace(0,1.5*u.deg,100)
psf1 = obs.psf.to_energy_dependent_table_psf(theta=4.3*u.deg,rad=rad)
psf2 = obs.psf.to_psf3d(rad).to_energy_dependent_table_psf(theta=4.3*u.deg,rad=rad)
table1 = psf1.table_psf_in_energy_band([0.2,10]*u.TeV)
table2 = psf2.table_psf_in_energy_band([0.2,10]*u.TeV)
table1.plot_psf_vs_rad(label='MultiGaus')
table2.plot_psf_vs_rad(label='3D')
```
For an offset of 2.3 degree there are little differences:
![Unknown](https://user-images.githubusercontent.com/5047091/79588350-16133100-80d4-11ea-8ef4-c700bea9124e.png)
Conversely, for an offset of 4.3 degrees, the differences are much more pronounced:
![Unknown-1](https://user-images.githubusercontent.com/5047091/79588399-275c3d80-80d4-11ea-8848-12945e77e8d2.png)

If you take exactly 4 or 5 degrees you have equal profiles, but as soon as some interpolation in offset is performed you have different results.

Obviously, interpolating over the functional parameters or over the PSF profile yields very different results when the PSF tails vary strongly.
When producing average PSFs, one unfortunately has to go through PSF tables, because one cannot average functional parameters (e.g. sigmas). That is why we use this approach when computing the PSFMaps.

The effect you see on the off-axis CTA 1DC events could likely be due to this: events were generated interpolating over parameters while the average PSF you are using is the result of averaging the PSF tables. 

It might be that we still have a bug somewhere in the conversion to the `PSF3D`. I'll check that.

**Comment by tunbehaun273** [comment]
For the problem in the Crab analysis with Hess data in gammapy I compared the PSF used in the HAP analysis with PSFs used in the gammapy analysis.
![PSF_comparison_above0 52TeV](https://user-images.githubusercontent.com/60741323/79851190-43f2c100-83c5-11ea-975e-f8905065d205.png)
 As you can see the v4 PSF agrees pretty well with the HAP PSF. In the HAP analysis there are no such residuals present as in the gammapy analysis.
![Bildschirmfoto von 2020-04-13 10-31-45](https://user-images.githubusercontent.com/60741323/79851620-deeb9b00-83c5-11ea-8ecc-ad4728184b09.png)
So for this analysis maybe the problem is not the PSF description but rather the events filling in the counts cube? Any ideas what could go wrong there, what I could check to solve this problem?

**Comment by QRemy** [comment]
When fitting something potentially extended with only a point source you can create such ring features because the fit try to use the PSF extent to compensate for the missing extented source in the model. So I would do these tests only on sources that are for sure not extended.

**Comment by tunbehaun273** [comment]
In the PDF I added on my very first comment you can see a check on PKS 2155-304. There the residuals don't look that bad but the statistics are not as good as for the crab. And the shapes of the counts profile and the npred profile don't agree very well.
We are currently also looking for a bug in the fits export of the event files. Maybe the problem is there and not in gammapy.

**Comment by registerrier** [comment]
Is there anything to be done for this issue @tunbehaun273 ?

**Comment by tunbehaun273** [comment]
The issue with the Hess ImPACT data is solved. It was not a problem with gammapy. 
If the issue with the CTA multiGauss PSFs for high offsets is fixed as well I think this issue can be closed

**Comment by tobiaskleiner** [comment]
@tunbehaun273 Could you tell what was it that solved the problem finally? I am having a similar issue when using the point spatial model.
You could solve it for the Crab or for PKS 2155-304 or both?

**Comment by tunbehaun273** [comment]
@tobiaskleiner The problem with our datasets was a bug in the FITS export of HAP data. A new production of the FITS files solved the problem for both Crab and PKS.

**Comment by tobiaskleiner** [comment]
@tunbehaun273 Do you remember what kind of bug? Related to PSF?

**Comment by tunbehaun273** [comment]
@tobiaskleiner The IRFs were fine. Some of the reconstructed quantities of the events were not exported correctly.
