### ISSUE TITLE
Possible mistake in `wstat ` calculation in `MapDatasetOnOff`

### ISSUE THREAD

**Issue by IftachSadeh** [gammapy/gammapy#2893]
**Gammapy version**
0.17

**Bug description**
possible mistake in `wstat ` calculation in `MapDatasetOnOff`

**Detailed info**
The test statistic for `MapDatasetOnOff` is calculated as: https://github.com/gammapy/gammapy/blob/2b2f8dca0b6ba4dc9119f357fa02c9b3c7b53800/gammapy/datasets/map.py#L1114-L1123
`mu_sig ` is defined as the `Signal expected counts in the on region` (https://docs.gammapy.org/dev/stats/index.html), however, the current implementation actually gives the `Total expected counts in the on region`:
https://github.com/gammapy/gammapy/blob/2b2f8dca0b6ba4dc9119f357fa02c9b3c7b53800/gammapy/datasets/spectrum.py#L269-L276
as `npred()` gives the sum, `signal+background` counts.
If I understood correctly, actually you'd want to have: `mu_sig = self.npred_sig().data ` for the `stat_array()` func.

**Comment by registerrier** [comment]
`MapDatasetOnOff` has no `background_model` so `MapDatasetOnOff.npred()` should return only predicted signal counts. Do you have a case where `background_model` is not `None` on a `MapDatasetOnOff`?

Otherwise, the code you quote is from `SpectrumDataset` for which `npred` returns signal + background, because it uses `cash` statistic.
The code for `SpectrumDatasetOnOff` correctly uses only `npred_sig` which returns only signal expected counts :
https://github.com/gammapy/gammapy/blob/2b2f8dca0b6ba4dc9119f357fa02c9b3c7b53800/gammapy/datasets/spectrum.py#L763-L772

**Comment by IftachSadeh** [comment]
You're right. Thanks for the quick replay!
The code does behave as expected.

Though I would suggest thinking about changing `self.npred()` to `self.npred_sig()` in `map.py` to match the structure in `spectrum.py`. (Maybe adding a wrapper function for `self.npred()` to just return `self.npred_sig()` for now). The code would be more verbose and easier to interpret.

For instance, if you compare
https://github.com/gammapy/gammapy/blob/2b2f8dca0b6ba4dc9119f357fa02c9b3c7b53800/gammapy/datasets/map.py#L1272-L1294
and
https://github.com/gammapy/gammapy/blob/2b2f8dca0b6ba4dc9119f357fa02c9b3c7b53800/gammapy/datasets/spectrum.py#L774-L799
You basically have the same code in these two cases, with the same statistical meaning for model-predicated signal counts, but with different (actually conflicting)  function names.

**Comment by adonath** [comment]
This will be addressed by @AtreyeeS. I'll assigned the issue to you..
