### ISSUE TITLE
`plot_spectrum_datasets_off_regions` shows up to 10 sets of off regions

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2919]
**Gammapy version**
v0.17

**Bug description**
This is very much low priority.

The function [plot_spectrum_datasets_off_regions](https://github.com/gammapy/gammapy/blob/9428f86b55850776dfdc95b098106dc6a8a94081/gammapy/visualization/utils.py#L6) don't show all the sets of reflected regions in case the passed `Datasets` contains more than 10 datasets.

**Other information**
The reason is that there are not enough colors to plot all the sets of reflected regions. The colors are defined with `color_cycle = plt.rcParams["axes.prop_cycle"]` which leads to 10 colors (hence the 10 sets of reflected regions that are displayed).

This helper function is not really adapted for the use with many observations, also because:
- we display the run ID in the legend for each observation, and for tens of runs this can become messy
- there is no `alpha` option set for the regions, so if two runs have the same reflected regions only one of them will appear in the plot 

Since this function lives now in `gammapy.visualization`, it might be worth cleaning it up a bit to generalize its use

**Comment by adonath** [comment]
I thinking's general it is tricky to make a plot where all off-regions for many observations  are plotted on the the same sky map. To avoid cluttering of the plot one would need to work with alpha values, line styles and many more colors, as you already suggested. 

I think the plotting functionality we provide will always be limited to standard versions of plots and not be adaptable to every users needs. Especially choice of colors, alpha and fonts etc. is also a matter of taste in many cases. Offering all options to customise a plot puts a lot additional implementation and maintenance effort on our side and I would clearly try to avoid it.

In my view the solution to this problem is documentation. Looking at the code of [plot_spectrum_datasets_off_regions](https://github.com/gammapy/gammapy/blob/master/gammapy/visualization/utils.py#L6) it is really limited and we should also encourage users to just copy and paste from it, when they need a custom version of the plot. 

Back to the issue:
Because of the loop over datasets in the plotting method, it will be hard to implement a clean keyword forwarding and we should probably just rely on the matplotlib property cycle. This means if users want more colors they need to modify the standard property cycle of matplotlib using `plt.rcParams`. But this definitely requires a docs example...

**Comment by adonath** [comment]
I think the action item here would be:
- Modify plot_spectrum_datasets_off_regions to take all properties from the property cycle (i.e. include at least linestyle and alpha)
- Show how to modify the property cycle from "outside" and but this as an example in the docstring

**Comment by adonath** [comment]
We could also accept a `Cycler` object to be passed to `plot_spectrum_datasets_off_regions`, see e.g. [here](https://predictablynoisy.com/matplotlib-cycles) how it is used.

**Comment by alexiscoutinho** [comment]
If `Cycler` is to be supported, then the line `colors = color_cycle.by_key()["color"]` should be removed and the loop become something like `for props, dataset in zip(prop_cycle(), datasets):` where `prop_cycle` is the default `color_cycle` or user defined. The legend would then have to be toggled off by default or above a certain threshold. `kwargs = {...}` would obviously need changes.

**Comment by adonath** [comment]
@alexiscoutinho Feel free to open a PR..:-)

**Comment by adonath** [comment]
Fixed in #2932
