### ISSUE TITLE
Ordering of keywords in FITS headers.

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#298]
When creating a FITS I/O (`~astropy.io.fits`) object from an `~astropy.table.Table`, the order of the keywords in the header is not always very nice. 

An example of this behavior is in the `~gammapy.background.CubeBackgroundModel.to_fits_bin_table` method. In this case, the axis units of a `~astropy.io.fits.BinTableHDU` are placed at the end of the axis descriptions.

It would be great to have utility function that can be called to reorganize the header.

**Comment by cdeil** [comment]
I'm closing this old issue now.

In Gammapy we're using `Table`, and `Table.meta` doesn't fully represent the FITS header.
It's a known issue, but usually doesn't matter for most users.
If there are cases where full control over the FITS header is needed, the `astropy.io.fits` classes should be used.
But we don't want to do that in most (all?) parts of Gammapy, because `Table` is a much friendlier object.
