### ISSUE TITLE
Behaviour of `ExcessMapEstimator`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2989]
Currently, the `ExcessMapEstimator` behaves differently for `MapDataset` and `MapDatasetOnOff`.
In the first case, the `npred` is taken as the background - ie, the background and the source models are both considered. In the second case, only the `counts_off` and the `background` are considered, and the counts from the source ignored.

This is quite confusing. We should enforce similar behaviour, and I think that the `npred` should be considered in case of  `MapDatasetOnOff` as well. What do you think @registerrier @adonath ?

**Comment by adonath** [comment]
@AtreyeeS I guess, including sources in the `MapDatasetOnOff` background does not make it and on-off measurement anymore? I need to think about this some more...

**Comment by adonath** [comment]
@AtreyeeS Can you check: isn't it that the background is missing from `MapDatastOnOff.npred()`?

**Comment by AtreyeeS** [comment]
Yes, `MapDatasetOnOff.npred()` does not have the background added. But I am not sure if it is OK to just add the background in this case to the model predicted counts? Does it still behave properly with `wstat` in that case?

**Comment by registerrier** [comment]
With wstat the actual background is a function of `npred`. The background method we use only give the estimated background in case no emission in present (i.e. `alpha * counts_off`).

You cannot use the background in the `npred` otherwise the `wstat` does not mean anything. 

For `ExcessMapEstimator` to behave consistently with `MapDataset`  and `MapDatasetOnOff`, you have to modify the `WStatCountStatistic` so that you can deal with WStat with an additional Poisson component with known intensity. It should fairly straightforward to do.

For the moment, there is a `mu_bkg` parameter in `wstat` but it does not do what we need (it simply replaces the proper profile estimate by a fixed value (I don't know why).

**Comment by adonath** [comment]
Thanks @registerrier, for the explanation! However in my comment above I meant something slightly different: even for `wstat` one can get an expected background given the current npred from the the signal (see https://docs.gammapy.org/0.17/api/gammapy.stats.get_wstat_mu_bkg.html#gammapy.stats.get_wstat_mu_bkg). Can't we modify `MapDatasetOnOff.background` to return this background estimate and then include it the `MapDatasetOnOff.npred()` as well? The `stat_array()` remains unchanged...

**Comment by adonath** [comment]
I have thought a bit more about this:
- My proposal from the last comment probably applies to the get things like `MapDatasetOnOff.plot_residuals()`, `MapDatasetOnOff.residuals()` to behave as expected
- For the `ExcessMapEstimator` it depends a bit on the use case I think. If `wstat` is applied within the `ExcessMapEstimator` the background is re-optimized internally, which might not be what we want. E.g. when doing the fit using a `MapDatasetOnOff` and e.g. computing a residual map, the background estimate would not be the same as the one resulting from the fit. Which is think somehow an unexpected behaviour... 
- When computing a "normal" flux map the implementation does already the right thing...

**Comment by registerrier** [comment]
I think we should make things uniform with `SpectrumDatasetOnOff` where we have a `npred_sig` that focuses only on the model `npred`. 
And then indeed we could modify `background` so that it returns the background taking into account the model and possibly add an `npred` that would return `background + npred_sig`.

**Comment by adonath** [comment]
Here is the conclusion / action items how to unify the behaviour:
- Modify both `SpectrumDatasetOnOff.backgroud` and `MapDatasetOnOff.background` to return the expected (marginalised) background using `get_wstat_mu_bkg()`
- Introduce `MapDatasetOnOff.npred_sig()` and modify `MapDatastOnOff.npred()` to add the background component

I would proposed to add an optional `mu_bkg` argument to `WStatCountsStatistic` in a separate PR. I still need to make up my mind about the details...
