### ISSUE TITLE
Reading PSF_TABLE from GADF fits does not check for correct shape and uses opposite dim order

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3025]
**Gammapy version**

`gammapy==0.17`

**Bug description**

When loading the `PSF_TABLE` IRF in GADF format as described here https://open-gamma-ray-astro.github.io/gamma-astro-data-formats/irfs/full_enclosure/psf/psf_table/index.html,
gammapy does not check that the data is consistent (bin definitions to psf table shape).

Also, the dimension order seems to be opposite to that expected in AEFF_2D or EDISP.
Probably a confusion from the differnt dimensin orders in FITS vs. numpy

> psf_valueQuantity

    PSF (3-dim with axes: psf[rad_index, offset_index, energy_index]

Which is how it is written in the fits files, but aeff2d and edisp transpose this so that it matches the order specified in 
the GADF documentation for the numpy convention.

Another thing that is strange to me is that it uses `lo` and `hi` for the energy and source offset bins but just
a single array for `offset`

**Expected behavior**

Be consistent about axis order and check for data consistency upon reading.

**Comment by MaxNoe** [comment]
Relevant code points:

In `EffectiveAreaTable.from_table` the data is transposed:
https://github.com/gammapy/gammapy/blob/43d64a89f2c2cdf10d1b315adb0d77f7c4e87215/gammapy/irf/effective_area.py#L410

So is the energy dispersion matrix in:
 https://github.com/gammapy/gammapy/blob/43d64a89f2c2cdf10d1b315adb0d77f7c4e87215/gammapy/irf/energy_dispersion.py#L171

Which has even a `TODO: why does it need to be transposed`

But it is not for the PSF:
https://github.com/gammapy/gammapy/blob/43d64a89f2c2cdf10d1b315adb0d77f7c4e87215/gammapy/irf/psf_3d.py#L152

**Comment by MaxNoe** [comment]
Also, what is the difference between `PSF3D` and `TablePSF`?

**Comment by adonath** [comment]
Related #1221

**Comment by adonath** [comment]
@MaxNoe The first classes implemented in Gammapy many years in ago, where actually the IRF classes. At this point we thought it was a good idea to represent the cases with different PSF dimensions with separate classes (instead of single ND-class). For these "historical" reasons, there are 3 "table" PSF classes:
- `TablePSF`: depends on theta (offset to source)
- `EnergyDependentTablePSF`: depending on theta and energy
- `PSF3D`: depending on theta, offset and energy

In fact I think the `TablePSF` is basically un-used and we could consider to remove it. In general the IRF classes are one of the remaining things we have to cleanup in Gammapy (https://github.com/gammapy/gammapy/issues/776, but not before v1.0). Up to now the design worked well enough so we didn't have a good reason to improve it, once e.g. non-radially symmetric PSFs etc. will be introduced for CTA, we will refactor and improve the class structure to be much more general. There was a proposal by @kbruegge already some time ago (https://github.com/gammapy/gammapy/pull/1288), but the work was not continued.

**Comment by MaxNoe** [comment]
I think we should at least make the axis order consistent before 1.0

**Comment by adonath** [comment]
Agreed, I set the Milestone accordingly...

**Comment by maxnoe** [comment]
I don't think it is a good idea to implent this guessing only for one special case for one IRF.

Either you want to be able to guess the axis order, than you should implement the guessing for all IRFs, or you don't, then this should error.

Only supporting it for one special case of one IRF will probably result in some pretty confusing behaviour for users.
