### ISSUE TITLE
SpectralCube writeto method is not tested

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#304]
In order to store an image HDU in a fits file, a primary HDU (even empty) has to be set. The `to_fits` method doesn't do it this way:
http://gammapy.readthedocs.org/en/latest/_modules/gammapy/data/spectral_cube.html#SpectralCube.to_fits
I suspect, from the experience with the `CubeBacgroundModel` class
https://github.com/gammapy/gammapy/pull/299/files#diff-82cdfbacfcc0119d2ccf6621da08de7bR408
that it won't work. Since there is no test covering the `writeto` method, this problem passed unnoticed.

**Comment by cdeil** [comment]
Thanks for noticing this.
I quickly looked through the tests:
https://github.com/gammapy/gammapy/blob/master/gammapy/data/tests/test_spectral_cube.py

Indeed there is no test for the write method, probably I just wrote it and it has never been executed.
So yes, please fix it by using `PrimaryHDU` instead of `ImageHDU` and add a test that writes / reads a cube and has a few asserts that data members before / after writing match.

**Comment by mapazarr** [comment]
PR #299 addresses this issue.
