### ISSUE TITLE
Problem with sphinx output using python 3.4

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#305]
Sphinx with python 3.4: if using `python setup.py build_sphinx -w` I get the otuput in one line: escape commands (like `\n` and others are not interpreted as they should: `new line` in this case). In addition, it is not shown progressively, while running, but all at once in the end.

I'm not sure if this is the right place to report this, but it's quite annoying, when debugging the docs problems within gammapy. Maybe @cdeil or @adonath have some input/workaround? Can you reproduce the problem at least?

The output was correctly parsed, when I was using python 2.7 (as the travis-ci does).

**Comment by cdeil** [comment]
@mapazarr – This bug report is a bit confusing. Is it for the #299 branch only? Or also for `master`?
It also always helps to show the full log by copy & pasting the command and output from your console into a [gist](https://gist.github.com/) and then linking to the relevant line number from the issue.
This greatly increases the chance that I can figure out what the issue might be from the issue description.

**Comment by mapazarr** [comment]
OK, here is an example:
https://gist.github.com/mapazarr/bd8f6a1d472753669245#file-gistfile1-txt-L10
Does this happen to you as well?

**Comment by mapazarr** [comment]
It happens also in `master` branch: version `0.3.dev1336`. Strangely enough, the output seems fine when not using the `-w` option.

**Comment by cdeil** [comment]
Yes, I see the same behaviour locally.
On travis-ci it looks OK, but maybe that's because of how they display the log: https://travis-ci.org/gammapy/gammapy/jobs/71208167#L1346

It's not a Gammapy issue ... it's the same for Astropy or other affiliated packages (I tried wcsaxes).

@embray or @astrofrog – Any idea why with `python setup.py build_sphinx -w` the log output on the console is garbled when adding the `-w` option? Is this something that should be reported in the Sphinx or astropy-helpers issue tracker?

**Comment by astrofrog** [comment]
@eteq - any ideas? I'm suspecting that there's a decode missing somewhere so that when the log is printed, it should be rendered as normal text, not bytes

**Comment by mapazarr** [comment]
As I said, it works fine with python `2.7`. The `gammapy` travis-ci uses python 2.7, so no problem there.

**Comment by eteq** [comment]
@cdeil @mapazarr  - yep, @astrofrog has the right idea.  ``-w`` has to parse the log, so it follows a code path different from when there's no ``-w``.  

The reason why this is different in 3.x (I think) is that `Popen` yields bytes instead of strings in 3.x vs 2.x .  So the decode is necessary in 3.x but not in 2.x.

So can one of you double-check that https://github.com/eteq/astropy-helpers/tree/fix-output-of-w fixes it?  That seems to do it for me - if so I'll issue a PR against astropy-helpers to fix this.  Easiest way to check is probably just to manually make the change shown in commit https://github.com/eteq/astropy-helpers/commit/b08cea4fbfa56389c87fb4a6d2c3dd70338cefa4

**Comment by mapazarr** [comment]
@eteq I added the line and it works. Thanks! The output comes all of a sudden, instead of progressively. I don't recall if this was the case with python 2.7.

Another thing: since the fix is only necessary for python 3.x, shouldn't the fix be dependent on the python version?

**Comment by mapazarr** [comment]
OK I tested with python 2.7: the output without the fix comes progrssively (and in colors/bold, i.e. formatted output). With the fix it comes all of a sudden and unformatted (as for python 3.4).

**Comment by eteq** [comment]
@mapazarr - that's strange... The behavior I see is that in py 2.7 *or* py 3.4 the ``-w`` option is all of a sudden and unformatted, while without ``-w``, both are progressive and formatted.  Are you sure you had ``-w`` in 2.7?

It's hard to see how you could get progressive output with ``-w``.  The output has to be checked for whether or not the build succeeded, so it all gets stored in-memory using ``Popen``'s ``PIPE`` functionality, but that means there's no way to see it until it's all there.  Then after that it gets ``print``ed.  So that's why it's not progressive, and there's really no way it could be if the ``-w`` path of the code is actually getting reached.

So that's why no separate py 3 and py 2 code path: the change in the new branch works just fine on both py 2 (where it's a no-op) and py 3 (where it's a fix), so it's better to do the same thing on both.

@mapazarr - can you clarify *why* you are using ``-w``?  The main use case for that is for automated tools like travis, which uses success or failure of the command to decide if the build succeeded.  For local use actually inspected by human eye, there should never be need for it, which is why no effort was put into making sure it was pretty.

**Comment by cdeil** [comment]
@eteq – Could you please open an astropy-helpers PR for the fix you've proposed?
I think discussing this there is the more appropriate tracker, because this has nothing to do with Gammapy.

Here's an affiliated package that is running a Python 3 sphinx build and the output is incorrectly printed with a `b'...'` and without newlines:
https://travis-ci.org/astroplanners/astroplan/jobs/71686667#L870

It would also be good to add Python 3 Sphinx builds to Astropy to make sure it keeps working with Python 2 and 3:
https://github.com/astropy/astropy/blob/master/.travis.yml#L47

**Comment by eteq** [comment]
@cdeil - good point, I was just using this thread to make sure the fix I made actually works.  See astropy/astropy-helpers#175 for the PR.  @mapazarr, perhaps you can respond to my question there?

Also, re: adding py3 sphinx builds: in principal that's a good idea, but the sphinx build takes a long time on astropy, and so far it hasn't been a problem (b/c the actual tests are still run in py3).  So it seems to me like the time tradeoff favors just using one version for now.

**Comment by cdeil** [comment]
@eteq - Thanks!
Closing this issue and locking it to make sure discussion continues only in https://github.com/astropy/astropy-helpers/pull/175.
