### ISSUE TITLE
Unify the naming convention for energy objects

### ISSUE THREAD

**Issue by fabiopintore** [gammapy/gammapy#3078]
The current naming convention for variables and functions that treat the energy is quite confuse, as many variants are possible. I list here all the names that can be found in Gammapy (although I warn that I could have missed some other possibilities):

- Minimum and maximum energy
Variables:
> e_min, e_max, min, max,
> e_mins, maxs --> in estimators.lightcurve,
> energy_min,
> e_reco_lo, e_reco_hi --> in irf.edisp_kernel

Functions:
> data.e_min, data.e_max 

- Energy ranges
Variables:
> e_range, e_edges, energy_band, 
> energy_bounds, energy_edges, 
> spec_erange_min, spec_range_max --> in catalog.gammacat,

Functions:
> .edges, edges.min,
> datasets.energy_ranges,

**Expected behavior**

The naming convention should be unified through Gammapy. I would propose to use `e_min`, `e_max` for minimum and maximum energies, and `e_range` for the energy range.

**Comment by adonath** [comment]
Thanks a lot @fabiopintore for this overview! 

I wonder whether we should avoid the `e_` prefix completely. Even if from the context it's always clear that it refers to energy, I feel like we should just be more explicit in our API and  use:
- `energy`, where we refer to a single value or array of energy "centers", such as in `SpectralModel.evaluate()`
- `energy_min` and `energy_max`, where we refer to a single number or array of energy mins and max such as in `MapGeom.energy_mask()` or `SpectralModel.integral()`
- `energy_edges`, where there is an array of energy edges such as `FluxPointsEstimator.__init__`
- `energy_bounds`, where there is a tuple of single values defining a range of energy, such as in `SpectralModel.plot()`

The remaining general question for me is whether we rely on min and max energies passed separately or as a tuple or whether we keep maybe both. So always use `energy_edges` instead of `energy_min` and `energy_max`. There I don't have a strong opinion. I think depending on the use-case one or there other might be more convenient...

Note that for now this only applies to our API. I think we should exclude e.g. column names of table etc. Those are partly defined by the data formats, we rely on. E.g. in `FluxPoints`.

**Comment by adonath** [comment]
Please comment @AtreyeeS, @registerrier, @QRemy, @bkhelifi, @Bultako, @LauraOlivera, @luca-giunti

**Comment by luca-giunti** [comment]
+1 for using `energy_` instead of `e_`. I would actually avoid most abbreviations (like `npred`, `stat`, `sigma_ul`) as a general rule...

**Comment by fabiopintore** [comment]
I agree with the proposed naming convention. Although it's quite clear in the code what we're meaning, `energy_` is better than the simple `e_` .

**Comment by AtreyeeS** [comment]
+1 with the naming convention proposed by @adonath . 
I do not know if there is further possibility of such cleanup, but if there is, I would prefer to use `MapAxis` as much as possible rather than bounds or edges or centers.

**Comment by adonath** [comment]
@AtreyeeS I was thinking about this too. I guess we should rely on `MapAxis`, where we make use of the extra information such as `name`, `interp`, or need both `edges` and `center`. If we don't need the extra information passing the energy values as Quantities is probably sufficient. But I guess there are corner cases e.g. the `FluxPointsEstimator.__init__`, where would use `interp` to define the energy center of the points. However one would probably never use anything else then `interp="log"`...

**Comment by AtreyeeS** [comment]
As a user, I find it very convenient to have an `energy_axis` defined, and pass that (specially on `init`) and instead of passing centres or edges or min and max...
But of course, `Quantity` suffices mostly and it is quite reasonable to expect this much care from the user...

**Comment by bkhelifi** [comment]
My main comment is: which energy? true or reco? For non-TeV experts, one needs to be pedagogical as they can make mistake without realizing. I would propose to always presice the nature of the energy....

**Comment by adonath** [comment]
Conclusion from the dev meeting today: if it's uniquely clear that it's true energy we use `energy_true`. We need to figure out the places where this is the case...For models I think we should always use `energy`, because it is mixed. E.g. a `PowerLawSpectralNormModel` mac be evaluated in `energy` as well as `energy_true`.

**Comment by AtreyeeS** [comment]
Regarding the question of models, `SkyModel.evaluate_geom` and `SkyModel.integrate_geom` should mention in the doc-string that the `geom` should have an `energy_true` axis.

**Comment by adonath** [comment]
Most of this has been implemented in #3101. I'm sure there are a few places we forgot, I'll keep this open for now...

**Comment by AtreyeeS** [comment]
Coming back to this, `FluxPoints` still uses `e_min` and `e_max`. Probably this is fixed by what is defined in GADF, so we have to stick with it? Or can it be replaced by `energy_min` and `energy_max`, respectively?

**Comment by adonath** [comment]
@AtreyeeS On the `FluxPoints` class we already use `.energy_min` and `.energy_max`, but the internal table still uses the `e_min` and `e_max` column names. However we could deviate from that. We already deviate from the GADF column names with the `stat` and `loglike` terms...

**Comment by adonath** [comment]
@fabiopintore Do you have time to check the Gammapy code base one last time for this?

**Comment by AtreyeeS** [comment]
I do not know if we intend to change this, but `SpectralModel.plot()` takes `energy_range` as an array, whereas `SpectralModel.integral()` takes `energy_min` and `energy_max`. A bit annoying.

**Comment by adonath** [comment]
@AtreyeeS See https://github.com/gammapy/gammapy/issues/3078#issuecomment-715320223 Do you propose anything in addition?

**Comment by AtreyeeS** [comment]
Ah! I did not realise we can pass multiple quantities to `.integral` at the same time. 
So just call it `energy_bounds` instead of `energy_range` in `plot` in the proposal?

**Comment by adonath** [comment]
@AtreyeeS I think `energy_bounds` would make it consistent with e.g. `MapAxis.from_energy_bounds()`...so I'd be +1 for the rename...

**Comment by fabiopintore** [comment]
Hi @adonath and @AtreyeeS. Yes, I can take care of this task. I also agree that we can use `energy bounds` rather than `energy_range` in `SpectralModel.plot()`.
About the `FluxPoints` class that generates a table with `e_min` and `e_max`, I think we can define them as `energy_min` and `energy_max`. Of course, this depends if we want to deviate or not from the GADF... or maybe we can suggest a GADF switched to our energy definition to make columns clearer :)

**Comment by adonath** [comment]
@fabiopintore I think the flux points can remain as they are for now, as we will refactor them a bit later anyway...

**Comment by adonath** [comment]
I think after #3402 has been merged there is nothing to do anymore?

**Comment by adonath** [comment]
Resolved by #3402.
