### ISSUE TITLE
Unusual change in `datasets.info_dict`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3105]
In gammapy-v0.17 `Datasets.info_dict` used to return `significance`, which has changed to `sort_ts` in the present dev. @registerrier @adonath Do they denote exactly the same thing?
Because there is a large change in the values.

See, for example: https://docs.gammapy.org/dev/tutorials/extended_source_spectral_analysis.html (max~ 7.1) vs https://docs.gammapy.org/0.17/notebooks/extended_source_spectral_analysis.html (max ~ 11) [The lifetime info in the docs is messed up - ignore it- this has been fixed by @adonath  in #3095]

Is this reasonable?

**Comment by adonath** [comment]
Thanks @AtreyeeS! Hm, this minimal test case:

```python3
from gammapy.datasets import SpectrumDatasetOnOff

path = "$GAMMAPY_DATA/joint-crab/spectra/hess/"
obs_1 = SpectrumDatasetOnOff.from_ogip_files(path + "pha_obs23523.fits")

info = obs_1.info_dict()
print(info["sqrt_ts"])

```
Returns for `dev`: 14.194477583584098
Returns for `v0.17`: 18.87204157

Looking at the code I can see that the definition changed in the following way:
- In `v0.17` the significance is computed from the summed background and constant alpha
- In `dev` the significance is computed from a corrected "acceptance_off", like `acceptance * counts_off / info["background"]`

If I remember correctly the last change was introduce by me, noticing that `dataset.info_dict()` and `dataset.to_image().info_dict()`, didn't return the same value for `sqrt_ts`, which I found unusual as well.

I guess the underlying question here is whether one computes the significance taking into account the information in the different energy bins as well, or just sums up. But then the question is e.g. how to handle energy dependent alpha...

**Comment by adonath** [comment]
A third way to define "significance" taking energy info into account is the following:
```python3
wstat = WStatCountsStatistic(
    n_on=obs_1.counts,
    n_off=obs_1.counts_off,
    alpha=obs_1.alpha
)

import numpy as np

np.sqrt(wstat.stat_null[obs_1.mask_safe].sum() - wstat.stat_max[obs_1.mask_safe].sum())
```
Which yields:
```
19.787690770640566
```
This assumes the energy bins are independent...

**Comment by registerrier** [comment]
Usually, when summing the different energy bins you have to weight the alpha by the number of OFF in order to conserve the total number of excess events.  So the solution implemented in `dev`  would seem appropriate to me.

In the example above, if you compute the sum of the TS in each energy bin, you have to take into account the number of d.o.f. (namely as many as energy bins). So you cannot take the `sqrt_ts` as a measure of the significance.

**Comment by registerrier** [comment]
As a general question, the move to change to `sqrt_ts` might prove confusing.

**Comment by adonath** [comment]
@registerrier and @AtreyeeS I looked into the issue again and just realised I'm fixing the problem in #3106. In the previous version `info["background"]` was filled incorrectly with `.npred_background()` (which is the marginalised background) instead of `alpha * counts_off`. Now there is `info["background"]` and `info["npred_background"]`...

**Comment by adonath** [comment]
The significance is back to the old value: https://docs.gammapy.org/dev/tutorials/extended_source_spectral_analysis.html#Cumulative-excess-and-signficance
