### ISSUE TITLE
Missing PSFKing.to_psf3d

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3186]
Some data release rely on the `PSFKing` format. At the moment, `PSFKing.to_psf3d` is not implemented making most analyses impossible to run. 

This should be added. Or conversely if one introduces a generic `PSF` base class, this could be a method on the base class.

**Comment by adonath** [comment]
After  #3185 is merged I can do some more clean up and address this issue as well...

**Comment by adonath** [comment]
Addressed in #3197. The solution is different: instead of going through `.to_psf3d()`, the `.evaluate()` method is used directly during data reduction... There is even the question whether `.to_psf3d()` is needed at all, as the parametric PSF implement all the methods needed, such as `.evaluate()`, `.containment()`, `container_radius()` etc.
