### ISSUE TITLE
Wrong label in SpectrumDataset.plot_counts()

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3271]
**Gammapy version**
v0.18.2

**Bug description**
I think that the "fit range" label [here](https://github.com/gammapy/gammapy/blob/635ff43540ab39feff9b60c6ecf9a907ae50a3c7/gammapy/datasets/spectrum.py#L74) is wrong, because the `mask_fit` is actually not applied when computing the `MapDataset.energy_range`. This method is called in the `SpectrumDataset.plot_counts()`, that is therefore showing vertical lines in the wrong place.

**Expected behavior**
I expected the vertical lines to display the fit range, not the energy range defined by the safe mask.

**Other information**
I would propose to change [this](https://github.com/gammapy/gammapy/blob/635ff43540ab39feff9b60c6ecf9a907ae50a3c7/gammapy/datasets/spectrum.py#L72) line to actually take into account the `mask_fit`.

**Comment by AtreyeeS** [comment]
Even taking `MapDataset.energy_range` is not ideal behaviour I would say. Because the takes the `[energy_min[mask].min(), energy_max[mask].max()]`, which is fine if the masked bins are at the energy edges. But this breaks if some bins in the middle are masked, say `dataset.mask_safe.data[3:-3]= False`.
This might not be very common, but probably it will be good to change the plot.. maybe a light shaded background for the un-masked bins?

Regarding plotting of `mask_fit` or `mask_safe`, I remember there was already such a discussion on slack. And it seemed the preference depends on the use case.

So probably it can be an option, `MapDataset.plot_counts(apply_mask_fit=False)` like we have in the `ExcessMapEstimator`?

**Comment by adonath** [comment]
@AtreyeeS +1 for the suggestion to plot masks as shaded regions! I'll think about it once more whether there is an alternative way to visualise this, but I think this definitely goes into the right direction. Maybe we can collect a few proposals here and then decide...

**Comment by adonath** [comment]
Here is a quick example how @AtreyeeS 's proposal could look like:

![image](https://user-images.githubusercontent.com/3715928/111498958-bccbdb80-8742-11eb-8336-54e385d7a6c9.png)

**Comment by adonath** [comment]
I think we could implement this shaded area plotting as `RegionNDMap.plot_mask()`.

**Comment by adonath** [comment]
For reference here is the core of the mask plotting code:
```python3

from scipy.ndimage.measurements import label as ndi_label

def plot_mask(ax, region_map, color="k", label=""):
    edges = region_map.geom.axes["energy"].edges.reshape((-1, 1, 1))
    
    labels, nlabels = ndi_label(region_map.data)
    
    for idx in range(1, nlabels + 1):
        mask = (labels == idx)
        xmin = edges[:-1][mask].min()
        xmax = edges[1:][mask].max()
        ax.axvspan(xmin, xmax, color=color, alpha=0.05, label=label)
        label = None

    return ax
```

**Comment by adonath** [comment]
The conclusion from the dev meeting was to add the `RegionNDMap.plot_mask()` and `Map.plot_mask()` methods. Both can offer two modes: either plot a shaded region or just the contours. The latter can possibly achieved with matplotlib keywords like `edgecolor` and `facecolor`. If this is possible it would the preferable solution....

**Comment by adonath** [comment]
@luca-giunti Do you have time to work on this and prepare a PR? The remaining work is to adapt `SpectrumDataset.plot_counts()` to use `.plot_mask()` so that we get a plot similar to the one I posted above. Should be possible to implement in ~1h I guess.
