### ISSUE TITLE
FluxPointEstimator optional keywords 

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3295]
**Gammapy version**
latest dev

**Bug description**
in the `selection_optional` keyword for `FluxPointEstimator`, the documentation mentions `norm-scan` as an allowed keyword. However, the accepted keyword is rather `scan`. This should be corrected.

Also, if `norm-scan` is not executed, `.plot_ts_profile` does not work.
This is expected behaviour, but it should be documented. And the error message should be improved. Presently, there is no check and the error happens somewhere in Astropy-packages, and the message is difficult to understand.

**Comment by QRemy** [comment]
Also the doc mentions `selection_optional : list of str`, but`selection_optional = "all"` works, while `selection_optional = ['all']` fails. Maybe the default should rather be selection_optional = None.

 The description of selection_optional should be:  "Which ~~additional~~ specific quantities to estimate", otherwise "additionnal" suggests  estimated on top of the defaults.

**Comment by adonath** [comment]
A few more points from my side:
- I agree the docstring should mention a str for "all" explicitly
- I think the description is correct: `selection_optional` specifies the quantities on top of the default ones (such as `norm`, `ts`, `norm_err`, etc.). The default quantities cannot be specified.
- However the description of the default is incorrect, the doctoring still says: "By default all steps are executed.", which is not the case.
- In addition we should mention which default quantities are computed or at least provide a link to the table in https://docs.gammapy.org/dev/estimators/index.html#introduction

**Comment by QRemy** [comment]
Looking closer to the code I reached the same conclusions than you @adonath and implemented that in #3309 (except you last point).
