### ISSUE TITLE
FoVBackgroundMaker fit option

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3311]
The `FoVBackgroundMaker` takes two options for pre-computing the background norms
- `scale` - the predicted background counts are just scaled to the total counts (outside the exclusion regions)
- `fit` - the  predicted background is fit to the data

The `fit` and `scale` should be identical in case of the `tilt` being frozen, I imagine?
So I would expect that the `fit` option should fit both the `norm` and the `tilt`? 
At present, the tilt is frozen by default.
Should we change  it? @registerrier @adonath @QRemy @luca-giunti

**Comment by adonath** [comment]
@AtreyeeS No, taking it strictly I think the `scale` and `fit` option are only equivalent for either very high statistics per bin, or if there is just a single spatial bin to fit. Both of which are not neccessarilly the case. In practice I guess they deliver similar results most of the time, if only the norm of the background is adjusted, but I would expect different results for low statistics...

**Comment by AtreyeeS** [comment]
I see. But it can still be nice to be able to fit the `tilt` during `FoVBackgroundMaker.run()`, no?

**Comment by adonath** [comment]
@AtreyeeS Yes, definitely! But this already works, if users pre-define the `FoVBackgroundModel`, or do you just propose to change the default behaviour in `FoVBackgroundMaker`?

**Comment by AtreyeeS** [comment]
I feel it would be convenient to be able to fit the tilt without having to pre-define the `FoVBackgroundModel`.

eg: I want to fit the norm and tilt during the data reduction process and create a stacked map, instead of having a 2 step process

```
stacked = MapDataset.create(
    geom=geom, name="stacked"
    )
maker = MapDatasetMaker(
        selection=["counts", "exposure", "edisp", "psf", "background"])

safe_maker = SafeMaskMaker(
    methods=['offset-max'], 
    offset_max=offset_max, aeff_percent=10,
    )
bkg_maker = FoVBackgroundMaker(exclusion_mask=exclusion_mask, method='fit')
for obs in observations:
    cutout = stacked.cutout(
        obs.pointing_radec, width=2 * offset_max, name=f"obs-{obs.obs_id}"
    )
    dataset = maker.run(cutout, obs)
    dataset = safe_maker.run(dataset, obs)
    dataset = bkg_maker.run(dataset, obs) ## nice to stack the fitted background directly.
    stacked.stack(dataset)
```

Maybe it can be made configurable on `init`?

**Comment by registerrier** [comment]
It could be easily done by passing the `NormSpectralModel` on the `FoVBackgroundMaker` init. This would make this option configurable.

**Comment by adonath** [comment]
I agree with @registerrier here. I think adding an option like `freeze_tilt=True` is bit arbitrary, because there are a few other spectral norm models, that have completely different parameters. However as a compromise one could rename the `spectral_model_tag` parameter to `spectral_model` and allow an instance of `NormSpectralModel` as well.

Another option that already works, is to modify the default value of `PowerLawNormSpectralModel`, like:
```python3
from gammapy.modeling.models import PowerLawNormSpectralModel

# modify default value on the class level
PowerLawNormSpectralModel.tilt.frozen = False

pwl = PowerLawNormSpectralModel()
print(pwl)
```
I think for advanced users this is even an acceptable solution...

**Comment by AtreyeeS** [comment]
> I agree with @registerrier here. I think adding an option like `freeze_tilt=False` is bit arbitrary, because there are a few other spectral norm models, that have completely different parameters. However as a compromise one could rename the `spectral_model_tag` parameter to `spectral_model` and allow an instance of `NormSpectralModel` as well.

Totally agree. 

> Another option that already works, is to modify the default value of `PowerLawNormSpectralModel`, like:
> 
> ```python
> from gammapy.modeling.models import PowerLawNormSpectralModel
> 
> # modify default value on the class level
> PowerLawNormSpectralModel.tilt.frozen = False
> 
> pwl = PowerLawNormSpectralModel()
> print(pwl)
> ```
> 
This is a very nice solution. I am +1 in favour of documenting and showing this

**Comment by AtreyeeS** [comment]
Before closing this issue, I wanted to bring up a related point.

It is often useful (eg: for large exclusion regions) to know if there are enough counts to do the background normalisation on. Perhaps these can be defined as class members instead of in `make_background_scale`  so that they are accessible? 
This is specially useful then the `exclusion mask` is defined on a different Geom; calling `interp_to_geom` and doing it outside is not very intuitive.
What do you think?

**Comment by adonath** [comment]
@AtreyeeS I agree this is useful information to keep however I'm not sure yet how this fits in our current scheme. The idea of the `exclusion_mask` being separate from the geom of the dataset, was that typically exclusion masks are defined in a general way, e.g. from a catalog or some allsky map or regions etc. and can live independent from a `MapDataset` and the geometry of the dataset. They are also typically not energy dependent. 

In general I'd say the counts outside exclusion regions is some kind of meta information, just like whether the fit converged, the fit statistic value etc. and we don't have any scheme to save and pass on this kind information yet, but it is definitely required! For flux points we have it partly, because anything can bis just stored in the output table, including information like `table["fit_sucess"]` etc.

One thing we could add is just `FoVBackgroundMaker.make_exclusion_mask`, which returns the re-projected exclusion mask, but this is a two-line implementation. In general one could add this kind of information to `dataset.meta_table` or `map.meta` as well, but this is just not defined yet either. Currently I'm not sure what to do, because the good solution would require a provenance scheme exposed as `MapDataset.history` or similar, which is probably too much work for now. Maybe you any other idea?

**Comment by adonath** [comment]
Partly solved in #3319...

**Comment by registerrier** [comment]
I suppose that the parameter error is a good indication of the available statistic. If you run the `FovBackgroundMaker` with the `fit` option you have access to the errors on the `SpectralModel` parameters (as long as you don't stack).
A possibility here is to manually add an error with `scale` option (namely `np.sqrt(count_tot)/bkg_tot`).

**Comment by AtreyeeS** [comment]
This seems to be a common use case for many H.E.S.D. analysis. I will add this
