### ISSUE TITLE
Cleanup `MapDataset.to_spectrum()`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3367]
We currently have `MapDataset.to_spectrum()` and `MapDataset.to_spectrum_dataset`. The difference between the two is not very clear from the doc-string.

https://github.com/gammapy/gammapy/blob/1071cedc49ed484776c1bfe00892efcd46375973/gammapy/datasets/map.py#L1242

If I understand correctly, the latter does a containmemt correction for extended sources. 

For clarity, we can maybe merge the two, or make `to_spectrum` hidden?

**Comment by adonath** [comment]
Gammapy already allows for a `MapDataset` with a `RegionGeom`. This enables use-cases like containment correction for arbitrary region shapes and "contamination" correction of nearby sources for 1D analysis. In this scenario the `SpectrumDataset` is basically redundant...

So I think the `.to_spectrum()` methods is the more general and even simpler method, however it requires users to understand that it is not a simple "classical" 1D analysis anymore as the resulting dataset is a `MapDataset` and still contains e.g. the PSF info. I am definitely -1 to remove or hide the method. I think there are fair use-cases where this is useful. However I fully agree on the lack of documentation. So that's maybe the obvious place to improve first?

**Comment by AtreyeeS** [comment]
Looking at the code, `MapDataset.to_spectrum_dataset()` first calls `to_spectrum` and then has an additional code block for `containment_correction=True`

I see what you mean by "SpectrumDataset is basically redundant". `to_spectrum` should (more than) suffice for most use cases.

It is not totally clear to me how to improve the documentation here, but this we must do. I am adding it to the docs TODO for now

**Comment by adonath** [comment]
Maybe one could maybe rename `to_spectrum() just to a more generic `to_region_geom()` or similar?

**Comment by registerrier** [comment]
+1 on not using `to_spectrum` as it falsely suggests that this is creating a `SpectrumDataset`.
`to_region_geom` might more adapted, although this is not technically creating a `RegionGeom`. Having an action verb before `to` might be more adapted here. (e.g. `squash_to_region`. 

Regarding documentation, the complex notion is that more than dimensionality what distinguishes a `MapDataset` from a `SpectrumDataset` is the presence of a `PSFMap`. So complex modeling that require spatial integration over a region requires using a `Region`-based `MapDataset`. This is not supported a priori by `SpectrumDataset`. That's probably where we should draw the line for medal evaluation in regions?

**Comment by adonath** [comment]
@registerrier We already have `Map.to_region_nd_map()`, so what about `MapDataset.to_region_map_dataset()`?

**Comment by adonath** [comment]
The reason why it was named `MapDataset.to_spectrum()` is the consistency with `MapDataset.to_image()`, which also returns a `MapDataset`. So one could choose e.g. `.to_region_map_dataset()` and `.to_image_map_dataset()`.

**Comment by adonath** [comment]
Solved by #3471.
