### ISSUE TITLE
Stacking of Map cutouts is erroneous

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3368]
** Bug description **

If we have 2 maps which are themselves cutouts (eg; maps obtained from our `MapMaker` process), and then we perform a cutout on them

`map1 = dataset1.counts.cutout(dataset1.counts._geom.center_skydir, width=2.0*u.deg)`
`map2 = dataset2.counts.coutout(dataset2.counts._geom.center_skydir, width=2.0*u.deg)`

and then want to stack `map1` and `map2` onto a large target Geom, 

```
counts = Map.from_geom(geom)
cutout = dataset1.counts.cutout(dataset1.counts._geom.center_skydir, width=2.0*u.deg)
counts.stack(cutout)
```

 just stacks in one corner according to the pixel index, forgetting the geometries.

** Reason **

I discussed this privately with @adonath and the reason is that in
https://github.com/gammapy/gammapy/blob/master/gammapy/maps/wcsnd.py#L789 we only check for the alignment of the WCS and not the actual position. So when stacking a cutout from a cutout into the initial geom, the WCS projections are aligned, but the slices are not valid anymore. The slices from the smallest cutout are only valid for the bigger cutout and not the initial parent geometry.

This is a reminder issue to fix before 1.0 release

**Comment by adonath** [comment]
Just for the record. Here is already a possibly fix: https://github.com/gammapy/gammapy/compare/master...adonath:aligned_wcs_geom?expand=1 and this fix will also allow to make `datasets.stack_reduce()` work for cutout `MapDataset` objects.
So instead of relying on storing the parent slices, one could possibly just re-compute the slices created in `.cutout()`. However the fix hasn't been tested yet...

**Comment by adonath** [comment]
As I already started to work on the cutout slices I'll sign the issue to me.
