### ISSUE TITLE
Dataset energy range handling

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3427]
All `Dataset` classes define different energy ranges related to the definition of the different `mask` attributes. Currently a single energy range is derived even if the energy range varies with e.g. position. This issue outlines a possible solution to make the handling uniform and more general. First I propose to define three energy ranges, related to the the masks defined on the dataset:
- `.energy_range`, which is the global energy range derived from `.mask`
- `.energy_range_safe`, which is the energy range derived from `.mask_safe`
- `.energy_range_fit`, which is the global energy range derived from `.mask_fit`
Instead of a single value for the min and max energy we should return a `Map` object to keep the information on the position dependency. E.g. it can be useful to plot a map of the lower energy threshold of a flux map.

In addition we should mirror the API on the `Datasets` object. The challenge here is that the datasets can have different types and geometries. So it requires some handling of the energy ranges between the different datasets.

Finally it could be very useful to store the information one the energy ranges used for e.g. flux map and flux points estimation on the corresponding result objects. The logic here is to reduce the energy range maps on the input datasets, e.g.. by taking the min or max energies in each dataset / bin group.

**Comment by bkhelifi** [comment]
Hi all,
There is a fourth type of energy range, I think, the (future) one coming from the IRFs... This range is the first that is defined in the data flow.

**Comment by adonath** [comment]
Thanks @bkhelifi indeed...in some cases it's equivalent to `energy_safe` but it doesn't have to be, depending on the choice of the user. On the other hand the recommended IRF energy range might not be the one actually used during the analysis, e.g. if a more strict energy range is applied by other criteria. So A good way might be handle the IRF energy range as part of `meta` information, because it is not necessarily equivalent to the energy range used in the analysis.

**Comment by bkhelifi** [comment]
This is for the moment premature, as the IRFs does not contain energy ranges... We do not know how they will be stored. I do expect however that the maximal energy of validity of IRFs will depend on the offset (because at least of statistical issue). So at least an array will be needed, not only a meta information into the FITS header.
It is not needed to implement such `maps' of validity range of IRFs now. But it enters perfectly in the scheme that you are proposing...

**Comment by alexiscoutinho** [comment]
@adonath Does linking #3020 mean that returning a `Map` object is not desired anymore? Because `_energy_range` could be expanded to support this feature independent of that PR.

**Comment by adonath** [comment]
Thanks a lot @alexiscoutinho for responding and sorry for the delay on #3020, it just was not on our priority list, until now. After some thought and discussion in the developer calls we agree that the most flexible solution would be indeed to return a `Map` object. In practice this means:

- Remove the `region` argument from `energy_range_` attributes
- Return a tuple of `Map` objects in all the `energy_range_` attributes 
- Adapt the implementation, such that the returned `Map` object contains the energy threshold, that varies with position

What do you think?

**Comment by alexiscoutinho** [comment]
I tried to imply in my previous comment that `_energy_range` could return either a `Quantity` or `Map` object if `region` is passed or not, respectively. However, if it is decided that getting the greatest energy range in a certain region is not really useful (I don't know), thus justifying removing `region`, then I think closing #3020 would be the ideal action since it would be too different from its original proposition. No hard feelings either way.

**Comment by adonath** [comment]
Thanks a lot @alexiscoutinho! Getting the greatest energy in a range is still useful, however in the proposed scheme it can be achieved like so:
```python3
e_min, e_max = dataset.energy_range
e_max.to_region_nd_map(region, func=np.max)
```
The advantage is that more information is conserved in the `.energy_range` attribute. I'd be happy to review any new PR on this. If you prefer that we close #3020, that's fine by me as well...
