### ISSUE TITLE
Improve dataset generator

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#345]
The [gammapy.datasets.make_test_dataset](http:/gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_dataset.html) and [gammapy.datasets.make_test_eventlist](http://gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_eventlist.html) functionality should be improved:
- [ ] make a class out of the 2 functions
- [ ] add method to provide an observation table as input and generate data subsequently, as alternative to the current method: use a dummy observation table produced with [gammapy.datasets.make_test_observation_table](http://gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_observation_table.html)
- [ ] add a command line tool to produce a dataset
- [ ] [gammapy.datasets.make_test_observation_table](http://gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_observation_table.html) and [gammapy.datasets.make_test_bg_cube_model](http://gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_bg_cube_model.html) could be methods of the class
- [ ] improve bg models and add sources
- [ ] add method to generate bg from IRFs (i.e. CTA bg rate IRFs) (see #267)
- [ ] the tools used for the modelling of the background should be shared with [gammapy.datasets.make_test_bg_cube_model](http://gammapy.readthedocs.org/en/latest/api/gammapy.datasets.make_test_bg_cube_model.html)

**Comment by cdeil** [comment]
Completely agree it would be nice to have better tools to simulate data.

But it's quite a big task, and at least for me, this has lower priority than analysis features for Gammapy.
Especially since I've recently figured out how to use ctobssim (see [here](https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess_crab)) to simulate event lists for any IRF and source / background model Gammalib supports (which is a lot, all we need).

So if I were to do it, I would write a tool that uses the Gammapy observation handling and e.g. the TeVCat of Fermi catalogs and bring the CTA IRFs into a format that works (see #267), but then call ctobssim to do the sampling. I think that could be done in a day or two.

But of course, like most things in Gammapy ... what happens depends on whether someone is willing to to the work. So if someone has time and wants to improve the dataset simulation capabilities of Gammapy in any way, please go ahead or ask how best to proceed here or on the mailing list.

**Comment by cdeil** [comment]
I'm closing this old issue. Those old helper functions were removed. We can add some conveniences or examples back once we have an event sampler.
