### ISSUE TITLE
Cryptic error message when FluxPointsEstimator reaches empty bin

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3505]
In the current dev, when you pass `energy_edges` that are not fully contained in a single energy axis bin, the FluxPointsEstimator provide an INFO message about a dataset that does not contribute in the energy range and fail. The error message is weird because it relates to the model:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-5d8a7a5c9b26> in <module>
      1 fpe = FluxPointsEstimator(energy_edges=energy_edges, source="crab", selection_optional="all")
----> 2 flux_points = fpe.run(datasets=datasets)

~/Code/gammapy-dev/gammapy/gammapy/estimators/flux_point.py in run(self, datasets)
    656         ):
    657             row = self.estimate_flux_point(
--> 658                 datasets, energy_min=energy_min, energy_max=energy_max,
    659             )
    660             rows.append(row)

~/Code/gammapy-dev/gammapy/gammapy/estimators/flux_point.py in estimate_flux_point(self, datasets, energy_min, energy_max)
    695 
    696         datasets_sliced.models = datasets.models.copy()
--> 697         return super().run(datasets=datasets_sliced)

~/Code/gammapy-dev/gammapy/gammapy/estimators/flux.py in run(self, datasets)
    129         models = datasets.models.copy()
    130 
--> 131         model = self.get_scale_model(models)
    132 
    133         energy_min, energy_max = datasets.energy_ranges

~/Code/gammapy-dev/gammapy/gammapy/estimators/flux.py in get_scale_model(self, models)
     93             Scale spectral model
     94         """
---> 95         ref_model = models[self.source].spectral_model
     96         scale_model = ScaleSpectralModel(ref_model)
     97 

~/Code/gammapy-dev/gammapy/gammapy/modeling/models/core.py in __getitem__(self, key)
    531             return self.__class__(list(np.array(self._models)[key]))
    532         else:
--> 533             return self._models[self.index(key)]
    534 
    535     def index(self, key):

~/Code/gammapy-dev/gammapy/gammapy/modeling/models/core.py in index(self, key)
    537             return key
    538         elif isinstance(key, str):
--> 539             return self.names.index(key)
    540         elif isinstance(key, Model):
    541             return self._models.index(key)

ValueError: 'crab' is not in list
```

It is difficult for a user to figure out what is going-on in the context. 
In practice, the sliced_datasets contains no dataset, because MapDataset.slice_by_idx fails and the exception raised is caught, only leading to the info message above.

To reproduce simply increase to e.g. the number of energy edges in the spectral_analysis.ipynb tutorial.

It is not clear to me what the right behavior should be here. It did not fail in v0.18.2. (although the resulting `FluxPoints` are a bit weird).

A minima, the error message should be clearer. 
In general, it maybe me good that an INFO message is printed giving the actual binning that will be used for the current datasets.

Opinions @adonath, @AtreyeeS , @QRemy , @bkhelifi ?

**Comment by adonath** [comment]
Just to add a bit more context: I think the underlying issue is actually a result of the tight coupling between `Models` and `Datasets`. If there is no dataset contained in `Datasets`, one cannot set `datasets.models` and as a result `datasets.models` is empty. In general this is a bit weird behaviour because `Models` can live independently of `Datasets`. I'll change the behaviour to raise an error when `datasets.models` is set for empty datasets.

**Comment by adonath** [comment]
Just as an alternative solution: maybe we just let it fail, but with a proper error message? So the error is currently caught here: https://github.com/gammapy/gammapy/blob/master/gammapy/datasets/core.py#L280, so we could instead raise a more meaningful error.

I just checked and in the `LightcurveEstimator` we just skip the bin instead of putting `NaN`. Maybe implement the same behavior of the `FluxPointsEstimator`?
