### ISSUE TITLE
Inconsistency between gammapy.utils.coordinates.fov and gamma.makers.utils

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3510]
**Gammapy version**

Current master

**Bug description**

In `gammapy/utils/coordinates/fov`, `sky_to_fov` is defined like this:

```python
    # Create a frame that is centered on the pointing position
    center = SkyCoord(lon_pnt, lat_pnt)
    fov_frame = SkyOffsetFrame(origin=center)

    # Define coordinate to be transformed.
    target_sky = SkyCoord(lon, lat)

    # Transform into FoV-system
    target_fov = target_sky.transform_to(fov_frame)

    # Switch sign of longitude angle since this axis is
    # reversed in our definition of the FoV-system
    return -target_fov.lon, target_fov.lat

```

Observe the `-` in front of `target_fov.lon`.

The only place this function is used is in `gammapy/makers/utils.py`, where there is an if condition and the same transformation is basically done "by hand" again: 

https://github.com/gammapy/gammapy/blob/a3f6b0945b15cfea1d5fc3f711ef58929161d49a/gammapy/makers/utils.py#L60-L89

But this time, no `-` in front of `lon`.

This seems inconsistent. Is this a bug? Or intentional? Then there should proabbly be some kind of comment why it is negated in the one function but not in the "by hand" approach, which essentially duplicates the same code again.

**Comment by adonath** [comment]
Thanks @maxnoe for noticing!  The [code here](https://github.com/gammapy/gammapy/blob/master/gammapy/makers/map.py#L151) uses the `FOVALIGN` keyword in the background meta data to choose the coordinate transformation. The keyword is documented here: https://gamma-astro-data-formats.readthedocs.io/en/latest/general/coordinates.html#field-of-view. There it says "FOV LON should increase with decreasing OTHER LON", so I guess in both cases the minus sign is required? 

I think the ideal solution would be to just get rid of the "pseudo FoV" coordinates. Right now I can't even remember why it has been there at all. I guess because it comes from a time, where background model where radially symmetric anyway? And because both have been used in the past? Maybe you remember @lmohrmann or @registerrier?

In any case it would be good to check whether the definitions are consistent between Gammapy and pyirf / ctapipe.

**Comment by maxnoe** [comment]
In ctapipe, we right now just use the SkyOffsetFrame for `TelescopeCoordinate` (origin in AltAz). We don't have a frame aligned with `ICRS`.

There is this issue I opened in astropy about a polar sky offset frame: https://github.com/astropy/astropy/issues/10783 which could be used for the `fov_theta / fov_phi` coordinates.

**Comment by lmohrmann** [comment]
A few comments:

1) Not sure why they are called `pseudo_fov_coord` in the code, but this is simply a transformation from sky coordinates to FoV coordinates, or not? The background is provided in FoV coordinates, so I don't see how we could get rid of these...? (@adonath)

2) You can have the FoV coordinate system aligned with AltAz or aligned with ICRS. Since the "LON" axis in the ICRS system is inverted (i.e. increases from right to left), I could image the different sign is actually correct - but would need to explicitly test this to be sure. Right now, we provide background models in HESS aligned with ICRS, so `FOVALIGN` is `RADEC`. This is mostly because I checked at some point that the transformation back to sky coordinates works for this case, so I'm quite sure that this is still the case.

3) Not sure I understand what you want to say about the polar coordinates @maxnoe - can you elaborate?

**Comment by maxnoe** [comment]
@lmohrmann regarding 3: 

We have to different fov coordinate system. Both are spherical coordinate systems, the difference is whether you rotate into the pole or rotate into the crossing point of zero-meridian and equator.

If you look at the small section IACT fovs have in these two coordinate system, the first is essentially a 2d polar coordinate system while the second is a cartesian system.

**Comment by lmohrmann** [comment]
@maxnoe  OK, so you're saying that we might be able to use that new frame in Gammapy, should we ever want to make use of the polar coordinates? That's totally fine I guess.

But it's not really related to the original issue, which was about the sign on the longitude axis when transforming from a sky system to a FoV system, if I understood correctly. As I wrote, there are two options for the alignment of the FoV system here (note that this is a different distinction than the question of polar vs cartesian FoV coordinates, that you nicely explained), and the transformation need not be the same for these two options (but I'm not saying that the current code is definitively correct!...)

**Comment by maxnoe** [comment]
@lmohrmann Yes, this was only a general side comment concerning the different coordinate system and what is defined/implemented in GADF, ctapipe and astropy.
