### ISSUE TITLE
Normalize containment?

### ISSUE THREAD

**Issue by kpfrang** [gammapy/gammapy#3572]
Hi all. I'm currently looking into the calculation of the containment radius. 
https://github.com/gammapy/gammapy/blob/b89d0109ef7f549e1c6f1e59071aac1229541715/gammapy/irf/psf/core.py#L66

From my understanding, the containment should reach exactly `1` in each energy bin. In this case, the calculation of `fraction_idx` makes sense to me. Is this correct?

I saw that this is currently not always the case, neither for the public HESS data nor for VERITAS data. I'm wondering if it would make sense to normalize `containment` here to force it to `1` in each energy bin?

E.g. adding something like 
```python
        containment = self.containment(rad=rad, **kwargs)
        containment = containment / np.max(containment, axis=0)
```

**Comment by adonath** [comment]
Thanks @kpfrang for the issue! 

The data format specification is explicit on the normalization of the PSF and the responsibility of the producer for the normalization (see https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/irf_components/index.html#normalisation). It even declares that the forced normalization to unity is not necessarily desired, because in practice the PSF table is only exported to a max. rad value (such as 0.66 deg or similar). The point is that this value does not necessarily correspond to 100% containment of the "pre-exported" PSF, but maybe 98%. I think this is a well defined and reasonable recommendation. If Gammapy would re-normalize the PSF by default, it would overwrite and discard the GADF specification here.

In case you work with PSF data, that does not follow this specification, I would distinguish two cases:
- For the `EnergyDependentMultiGaussPSF` the normalization  is done on evaluation (see https://github.com/gammapy/gammapy/blob/master/gammapy/irf/psf/parametric.py#L320 and https://github.com/gammapy/gammapy/blob/master/gammapy/irf/psf/parametric.py#L342). So the issue should not be present there.
- For the `PSF3D` one can always call `PSF3D.normalize()` beforehand to force integration to unity. But this should probably be better documented.

**Comment by kpfrang** [comment]
Hi @adonath, 
thanks for the explanation. I didn't find the definition that you linked here before. Of course, you are right. From there it is clear, that in general it cannot be normalized here. So we will review the normalization in the converter instead.
