### ISSUE TITLE
Make RAD_MAX hdu optional?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3666]
The `RAD_MAX` hdu is assumed to be a default IRF in 0.19,

https://github.com/gammapy/gammapy/blob/d5d2e12fb2c4bdd3f9c027d97ac7d94056d2f25d/gammapy/data/data_store.py#L229

 leading to a warning message `No HDU found matching: OBS_ID = 33088, HDU_TYPE = rad_max, HDU_CLASS = None` for **every** run for present HESS and CTA datastores. This is rather annoying. Specially because `RAD_MAX` is not listed as one of the `available_irfs`, it appears a bit from nowhere.

https://github.com/gammapy/gammapy/blob/d5d2e12fb2c4bdd3f9c027d97ac7d94056d2f25d/gammapy/data/data_store.py#L260

This can (is) mislead(ing) users into believing that there is some issue with their runs, (and suppressing gammapy warnings is probably not the ideal solution).

Should we make this an optional hdu ? @registerrier @adonath @cosimoNigro @maxnoe @bkhelifi

**Comment by maxnoe** [comment]
@AtreyeeS and we get warnings about missing PSF and Background IRFs for each and every pointlike dataset we load. 

Maybe this warning system as a whole should be removed and replaced with a *clear* error message as soon something is actually trying to use one of these IRFs.

**Comment by bkhelifi** [comment]
rad_max is obviously optional... depending if the IRF is point-like or not. Do we have a metadata in the IRF files (edisp, area) are point-like or not?
By the way, the use cases are a bit more complex:
- full-containment production: we require to have "events", "gti", "aeff", "edisp", "psf". I do not remember for "bkg"
- point-source production: we require to have "events", "gti", "aeff", "edisp" and "rad_max" (the "bkg" is optional, "psf" not needed at all)
So, the design seems to be a bit more complex to handle these 2 use cases. Is not it?

**Comment by registerrier** [comment]
I agree. The logic behind should be changed. 

The `HDULocation` should not be in charge of warning of missing entries, because it cannot know what are the expected ones. What it could do is to emit a debug message about which HDUs it found.

The `Observation` constructor could complain if something is incorrect. For instance, if  `aeff.is_pointlike` but there is no `RADMAX_2D` or no `RADMAX` keyword in the header. But it is likely inefficient or problematic if we force some combinations directly at the level of the `Observation.__init__` (e.g. this forces to load IRFs into memory from the start).
As @maxnoe suggests, a more practical approach could be to raise an `Error` and/or emit a warning and skip the observation, if some inconsistency appears in `MapDatasetMaker.run(obs)`.
