### ISSUE TITLE
Incorrect label for FluxPoints plots

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3766]
**Gammapy version**
v0.19 an dev

**Bug description**
When plotting a `FluxPoints` in `dnde` or `e2dnde`, the label is confusing because it gives an interval where it should give the reference energy. 
**Expected behavior**
Give only the reference energy. Possible add it in the y-axis title.

**To Reproduce**
Just look at the flight curve flare tutorial. It is incorrect there.

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
Would keep the info in the legend, because it generalizes to plotting multiple light curves at different energies.

**Comment by adonath** [comment]
The strict solution here is actually to change the node type here (in fact for all differential quantities): https://github.com/gammapy/gammapy/blob/master/gammapy/estimators/map/core.py#L570

The label is already handled correctly here: https://github.com/gammapy/gammapy/blob/master/gammapy/maps/axes.py#L237, but internally even for `dnde` maps the `node_type` remains "edges", that's why the label is still shown as an energy range.
