### ISSUE TITLE
Make matplotlib and iminuit non-optional dependencies?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3865]
Inspired by @LauraOlivera 's comment https://github.com/gammapy/gammapy/pull/3864#issuecomment-1081511702, but I remember we have also discussed this in the past with users and in developer calls. Given that both Matplotlib and iminuit provide fundamental functionality we rely on, it might be good to make those non-optional dependencies. Instead of making iminuit required we could alternatively change to the scipy backend by default. For matplotlib there is not really an alternative for now. This might only change after v1.0 if we decide to support other plotting backends such as bokeh or similar....

**Comment by LauraOlivera** [comment]
Thanks @adonath for starting this discussion. I agree that matplotlib should be made non-optional, especially since there is currently no alternative.

About the fitting backend: what is the reason we have iminuit as the default? if the arguments "pro-iminuit" are strong enough, and if the implication is that we think a "normal" user should pick it, then I would argue it is non-optional.

**Comment by QRemy** [comment]
I would prefer to keep Minuit as default, first because in general we have more experience using it  (it's everywhere in the tutorials and probably in most our own analyses), and secondly because scipy methods come with some limitations that beginners may ignore if they don't read extensively scipy doc for example :
-bounds on variables are only availables for Nelder-Mead, L-BFGS-B, TNC, SLSQP, Powell, and trust-constr methods.
-In general the bounds handling of Minuit is more robust because it uses a space transform instead of hard limits as explained in the lmfit doc https://lmfit.github.io/lmfit-py/bounds.html (that implement it for scipy methods)
-by default optimize_scipy uses Nelder-Mead method that tends to take more time as it does not use any gradient evaluations. In general BFGS requires less function call than Nelder-Mead even if the gradient is estimated, but I remember that the bounded version, L-BFGS-B, was getting stuck more easily.

**Comment by maxnoe** [comment]
Not from myside. I fully agree that gammapy is basically not usable without these "optional" dependencies

**Comment by QRemy** [comment]
> Just a side note: the default algorithm actually depends on the arguments you give to scipy. E.g. it will automatically chose L-BFGS-B if you give bounds

@maxnoe yes but gammapy set the method to Nelder-Mead if not provided 

https://github.com/gammapy/gammapy/blob/699c117a371a89cd4a85136858c18fef49296553/gammapy/modeling/scipy.py#L16-L17

**Comment by adonath** [comment]
Solved in #3936 and #3941.
