### ISSUE TITLE
Parameters stored in fit results are not stable

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3868]
**Gammapy version**
0.19

**Bug description**
Parameters stored in fit results should not change if one later modifies the fitted model parameters. This is instead the case, because the parameters stored in the fit result point to the fitted model parameters. 

![image](https://user-images.githubusercontent.com/47325742/161095343-c8130e36-eb78-4583-a0f8-827012094ffc.png)

This is completely unexpected, because the fit results should contain the best fit parameters at a given analysis stage, which should always remain the same. 
A simple solution would be to make a copy of the parameters [here](https://github.com/gammapy/gammapy/blob/7e2976713facc0d443ade5279e91c4ae6b38c6c4/gammapy/modeling/fit.py#L221).

**Comment by adonath** [comment]
Thanks @luca-giunti, I agree this should be the preferred behavior.

**Comment by registerrier** [comment]
> I think I'd even prefer to remove the `.parameters` completely. However this is not backwards compatible...

Having a copy of the parameters provides a working mechanism to explore the values of other parameters during e.g. a `stat_scan`. In the longer run, this could provide some useful debug information for flux points too.

**Comment by adonath** [comment]
> Having a copy of the parameters provides a working mechanism to explore the values of other parameters during e.g. a stat_scan. In the longer run, this could provide some useful debug information for flux points too.

OK, but in this case it should still be better to store a copy of the full model. Because e.g. 3D joint fits might have >10 "norm" parameters from background models, where it's completely unclear to which observation they belong, because this info is not stored in the `Parameters` list. I think the isolated `Parameters` list is pretty much useless and even "dangerous" to use, because parameter names are not unique. I guess at some point we will be able to write a `FitResult` to YAML, it is completely unclear what to do with the isolated parameter list in this case.

However storing a copy of the model could be convenient... and then users can access the parameters like `results.models.parameters`. I checked and I proposed this already in https://github.com/gammapy/gammapy/pull/3646, but decided to remove it again (https://github.com/gammapy/gammapy/pull/3646/commits/163133114c4f49245877ae988d579025fcd2019e), because the time was too short for a more detailed discussion.

**Comment by luca-giunti** [comment]
Summary from the dev call:
- the preferred solution will be to store a shallow copy of the` Models` in the optimize results
- this can be made backward compatible by keeping the parameters property, but pointing it to the model copy parameters
- this behavior needs to be documented 
- the `stat_scan` and `stat_surface` with `reoptimize=True` need testing

**Comment by adonath** [comment]
@luca-giunti  Do you have time to implement the fix here?

**Comment by luca-giunti** [comment]
@adonath thank you for the reminder. Yes I'll try to do it this week

**Comment by adonath** [comment]
Solved in #3918.
