### ISSUE TITLE
stat, counts, explicit references to equations in papers

### ISSUE THREAD

**Issue by relleums** [gammapy/gammapy#3888]
Dear GammaPy,

in the [documentation](https://docs.gammapy.org/0.19/stats/index.html#counts-statistics-classes) you refer to Li&Ma1983, but I do not find a reference in the [sources](https://github.com/gammapy/gammapy/blob/master/gammapy/stats/counts_statistic.py).

Further in Li&Ma1983 are several different estimates for the same quantities. I have both seen the 1st estimate in Eq. 9 and the 2nd estimate in Eq. 17 being used in the wild. From what I see in ```gammapy.stats.counts_statistic``` I assume you implement Eq.9.

I am a bit afraid to make a pull request as I do not understand yet the purpose of a statefull class in the implementation. Why not using stateless functions?

Here is [what I use so far](https://github.com/cherenkov-plenoscope/lima1983analysis/blob/master/lima1983analysis/__init__.py)

**Comment by relleums** [comment]
As I am new to GammaPy: Why is  the module ```stats``` not a standalone python-package?

**Comment by adonath** [comment]
Thanks @relleums for the issue! 

The `CountsStatistic` classes do not "directly" implement the analytical solutions for the significance of Li&Ma but they  implement the hypothesis testing procedure instead. So the significance (in Gammapy called `.sqrt_ts`) is implemented like https://github.com/gammapy/gammapy/blob/master/gammapy/stats/counts_statistic.py#L24, where `.ts` is the difference in likelihood between the null and the best fit hypothesis. The nice thing about this is, that this formulation is equivalent to what is done for model fitting using Poissonian per bin statistics. However you can convince yourself that for a single bin this is fully equivalent to the Li&Ma solution.

Gammapy currently support two cases:
- The case with known background (alpha -> infinity), which is implement in the `CashCountStatistics` and refers to the `cash` fit statistic used for binned likelihood fitting.
- The case with an off measurement which is implement in the `WStatCountStatistics` and refers to the `wstat` fit statistic often used for binned likelihood fitting (this corresponds to Eq. 17 in the Li&Ma paper)

Eq. 5 in the Li&Ma paper is not supported in Gammapy. 

> I am a bit afraid to make a pull request as I do not understand yet the purpose of a statefull class in the implementation. Why not using stateless functions?

The only reason I think is convenience and code readability / simplicity. When using the counts statistics in Gammapy we often compute multiple quantities at the same time (like excess, significance, acceptance etc.). It was just convenient to have everything in a single name space and import just one class instead of multiple functions. The shared state is the data. 

> Why is the module stats not a standalone python-package?

There is no specific reason for this, except that we probably considered the functionality to small to justify a separate package. But in general I agree the scope for such functionality is bigger than just Gammapy.

**Comment by adonath** [comment]
On more note: computing the required signal counts for a given background and significance limit, as implemented in the code you linked, can be achieved with 

- https://docs.gammapy.org/0.19/api/gammapy.stats.CashCountsStatistic.html#gammapy.stats.CashCountsStatistic.n_sig_matching_significance 



- https://docs.gammapy.org/0.19/api/gammapy.stats.WStatCountsStatistic.html#gammapy.stats.WStatCountsStatistic.n_sig_matching_significance

**Comment by adonath** [comment]
@relleums Do propose any change to the documentation or API here? Or does the implementation make sense now, after my previous comments?

**Comment by adonath** [comment]
Maybe adding the explicit reference to the equations of the Li&Ma paper to the properties of the `CountsStatistics` classes make sense.

**Comment by bkhelifi** [comment]
With the new documentation, the current [Wstat counts statistics documentation](https://docs.gammapy.org/0.20.1/user-guide/stats/index.html#wstat-counts-statistic) mentions explicitly the eq 17 of Li&Ma. So, I think that we have answered to the interrogation of @relleums.
And if confirmed, I think that this issue could be closed

**Comment by bkhelifi** [comment]
I have maybe a remark about the [Wstat counts statistics documentation](https://docs.gammapy.org/0.20.1/user-guide/stats/index.html#wstat-counts-statistic), the `Excess errors` sub-section of the WStat section gives an example using the cash stats and not the Wstat stats. It seems inappropriate to me

**Comment by adonath** [comment]
Thanks @bkhelifi!  I can confirm the issue is addressed, for further comments please open a new issue.
