### ISSUE TITLE
Meta info in spectrum PHA files

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#413]
@JouvinLea asked me to add some meta info to the PHA file, namely offset, muon efficiency and zenith angle
- The latter two can be read from the event list header (see http://gamma-astro-data-formats.readthedocs.org/en/latest/events/index.html)
- The offset is not well defined a priori, I guess, because it depends on the position of the target in the sky. There is a default target in the event list header but there might be cases where other positions in the sky are to be observed.

The latter problem is actually solved in the `SpectrumObservation` class. https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectrumObservation.html?highlight=spectrum%20observation#gammapy.spectrum.SpectrumObservation

It takes a runnumber and a target region as input, and provides an offset property.
@JouvinLea: Would it be an option for you to just use this class instead of the PHA file? It would be no problem to add the muon efficienct, and zenith angle as further properties. Or to we want some of this meta info in the PHA header (@cdeil ?)

**Comment by JouvinLea** [comment]
@joleroi : yes I need these three parameters for the grouping since I read the header of each phafile to attribute the good band in zenith, efficiency and offset.
As you said for the muon efficiency and the zenith this is easy since this is in the meta of the event list. So for the moment I add these two parameters as members of CountSpectrum. 
For the offset,  I give it as an argument in the function write and to_fits of CountSpectrum. 
I added in the function to_fits the three keywords OFFSET, MUONEFF and ZEN for the phafile.
Perhaps there is something better to do but I really need the offset in the header of the phafile that represents the ON events!

**Comment by joleroi** [comment]
Ok, just for me understanding: How do you write the PHA file?

**Comment by cdeil** [comment]
@joleroi  - Whatever meta info you / @JouvinLea need in whatever places is fine with me.

**Comment by joleroi** [comment]
@JouvinLea : 
> I added in the function to_fits the three keywords OFFSET, MUONEFF and ZEN for the phafile.

Does this work for you? Or should I make some modifications to the code?

**Comment by JouvinLea** [comment]
@joleroi :
That works for me but I'm not sure this is well written...

**Comment by joleroi** [comment]
@JouvinLea : I you want to, you can make a pull request and I will have a look at your code. I think this is important functionality that is also relevant for other users.

**Comment by joleroi** [comment]
FYI: I started to write down some specifications for "our" PHA file here

http://gamma-astro-data-formats.readthedocs.org/en/latest/xspec/index.html

If you have any additions, please let me know (you can also edit the file directly, just check out this repository https://github.com/gammapy/gamma-astro-data-formats)

**Comment by joleroi** [comment]
Since https://github.com/gammapy/gammapy/pull/999 all meta info available for an observation is copied into the meta attribute of the ``SpectrumObservation``.
