### ISSUE TITLE
FluxPoints serialisation loses GTI information

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4230]
**Gammapy version**
1.0

`FluxPoints.write()` does not serialise the GTI information.
For example, in the light curve flare tutorial, 
`lc_1d.gti`  exists.
But,

```
lc_1d.write("lightcurve_pks2155.fits", format="lightcurve", overwrite=True)
lightcurve = FluxPoints.read("lightcurve_pks2155.fits", format="lightcurve")
print(light curve.gti)
```
gives `None`.

This is rather problematic as the light curve cannot be converted into `FluxPointsDataset`s for modelling and fitting.

**Comment by AtreyeeS** [comment]
Some of the meta information like `n_sigma` and `n_sigma_ul` is lost as well.
Only the table is serialised

**Comment by adonath** [comment]
Thanks @AtreyeeS! The sad truth is that we do not have any official or documented data format for light curves that allows for this. As long as the definition of data formats is behind, the serialization in Gammapy will be incomplete. We can start to introduce and document our own Gammapy formats, but then we might do the work twice. I'll change the label from bug to feature request, because I think right now we do not claim anywhere that out serialization is complete...

However users should be able serialize the gti independently using e.g. `GTI.write()`?

**Comment by AtreyeeS** [comment]
> However users should be able serialize the gti independently using e.g. `GTI.write()`?

Yes indeed @adonath.  So the minimal thing to do would be to mention this explicitly in our tutorials, and also show how to explicitly attach a GTI to a FluxPoints object. As far as I remember, GTI handling is not exposed very well in our tutorials, because it is mostly handled by gammapy and not left to the external user.

**Comment by registerrier** [comment]
Some remarks here:
- indeed `GTI` should be serialized along with `FluxPoints` for provenance
- For lightcurve modeling, time intervals of the lightcurve should rather be used, no? The issue rather lies with the current choice of evaluating time from `GTI` rather than from the dataset time geometry.
