### ISSUE TITLE
Ensure events are sorted in time order

### ISSUE THREAD

**Issue by JonathanDHarris** [gammapy/gammapy#425]
Some code will require that event lists are in time order.

We should update the docs to reflect this
http://gamma-astro-data-formats.readthedocs.org/en/latest/events/index.html#required-column-names

and  add to the check_times method
https://github.com/gammapy/gammapy/blob/master/gammapy/data/event_list.py#L721

I'll probably pick this issue up soon if no one else wants it

**Comment by cdeil** [comment]
I've moved this discussion to the format spec:
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/107
and once that's resolved we can adapt Gammapy.

**Comment by cdeil** [comment]
I've added a note that we shouldn't rely on TIME being sorted in EVENTS here: 063a3226d4aaeee9efda37418f685c5a679fcd04

Otherwise I reviewed the code, there's no place where we rely on TIME sorting in EVENTS.

Closing this issue now.

Improving code and documentation concerning Time in Gammapy is covered by this issue:
https://github.com/gammapy/gammapy/issues/284#issuecomment-557467376
