### ISSUE TITLE
PointSpatialModel: min and max of lon_0

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4255]
**Gammapy version**
1.0 +

**Bug description**
By default, there is no lon_0 range on the PointSpatialModel, ie they are nan. And it seems that iminuit does not like this (ie no convergence)

**Expected behavior**
The constructor sets limits for lat_0 but not lon_0. Maybe one could harmonize this...

**To Reproduce**
The following nb: [pks2155.ipynb](https://github.com/bkhelifi/mynbs/blob/master/random/class.ipynb)

**Comment by AtreyeeS** [comment]
Hi @bkhelifi ! I do not think that this is a bug. In general, we do not have parameter ranges fixed by default for gammapy, except when it is a natural hard limit, ie the longitude for spatial models (not specifically for the `PointSpatialModel`).

Having parameter limits of course improves the fit convergence and the performance, and in general we do need to specify it in most cases. However, I think we discussed in a dev call that we will not have min and max defaults because it is difficult to specify correct ones satisfying all use cases, but rather explain how to do this in our tutorials

**Comment by registerrier** [comment]
I don't think `lon_0` should have parameter bounds by default. It is a periodic quantity (contrary to `lat_0`) and there is no way to properly define a good default. If minuit explores a part that is not covered by the geometry it will get stuck anyway.

**Comment by registerrier** [comment]
A solution for this is now given in the how to  introduced in #4268. Closing.
