### ISSUE TITLE
Light curve plot with MJD on the time axis

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#4258]
It is standard to plot gamma-ray light curves with the time axis in MJD.

This is extremely useful for very large periods of time (e.g. multi-year monitoring), where the [current default plotting (see this tutorial)](https://docs.gammapy.org/1.0/tutorials/analysis-time/light_curve.html?highlight=light%20curves#light-curve-estimation-by-observation) with ISO time will be too detailed for such a wide time axis.

Could we add the option to have the time axis in MJD to the `FluxPoints.plot()` function?

Incidentally, when I was trying to plot myself manually a LC in MJD I run into #4257.

**Comment by adonath** [comment]
The way to configure this currently is on the `TimeMapAxis` itself:

```
from gammapy.maps import TimeMapAxis

TimeMapAxis.time_format = "mad"
```

This is e.g. shown here: https://docs.gammapy.org/1.0/tutorials/analysis-time/light_curve_simulation.html#check-setup

The reason is that the plot formatting happens on the `TimeMapAxis` and because there are more places where the info is used. But I agree that its would be convenient to have it in `FluxPoints.plot(..., time_format=)` as well.

**Comment by registerrier** [comment]
This has been implementd in #4395 . Closing now.
