### ISSUE TITLE
test_fitter1D fails with numpy dev on travis-ci

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#439]
@bsipocz - Since today, the Gammapy build using numpy fails on travis-ci here:

```
gammapy/astro/population/tests/test_spatial.py::TestMorphologyModels::test_fitter1D[model_class0-test_parameters0] <- ../../home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/modeling/tests/test_models.py 
```

https://travis-ci.org/gammapy/gammapy/jobs/107441265#L1079

I see the same fail on two unrelated PRs. Re-starting the build doesn't help, the error occurs at the same position. It looks like this test hangs, right? Any idea why or how to debug this?
Maybe make that build optional for sucess because numpy dev isn't stable enough?

**Comment by bsipocz** [comment]
@cdeil - Indeed it looks like an issue with travis, maybe those tests needs some external data access? In the last few weeks there used to be some network related issues on travis. I'm not sure we could make the output more verbose, you already run it with ``-V``.

There was a discussion about testing against numpy prereleases, too. So I think for gammapy (unless it uses some exotic part of np that astropy doesn't), it would be enough to test against that, rather than the dev. Or add another test against the prerelease, and allow the build fail against the dev. However this fail doesn't look like a np issue, as in that case the tests should run until the end, or at least I would expect a segfault or some error code coming from np.

**Comment by cdeil** [comment]
Hmm ... as a temp solution I propose #440

**Comment by bsipocz** [comment]
I would reopen this issue as the fail is still there and #440 was just a workaround for the travis status.

**Comment by cdeil** [comment]
Ok to keep this open as a reminder that we should try and understand this fail ...

**Comment by cdeil** [comment]
@adonath - I'm clearing out old issues today.

For `gammapy/astro/population/tests/test_spatial.py` I currently see this:
https://gist.github.com/cdeil/89d53bf5ebf53b19d307fc8d849e28c2

I.e. no fails, but some are skipped, e.g.
```
gammapy/astro/population/tests/test_spatial.py::TestMorphologyModels::test_deriv_1D[Paczynski1990-test_parameters0]
```

This is something you wrote.
Could you please have a look?
If you don't want to do this, please just assign back to me.

**Comment by adonath** [comment]
@cdeil For testing we use `Fittable1DModelTester` from `astropy.modeling.tests.test_models`, which saves ~100 lines of model testing code. As the models don't have a derivative or a bounding box defined (which are tested by default by `Fittable1DModelTester`), the tests are skipped. Changing this would require and upstream fix in astropy or some hacking on our side...

**Comment by cdeil** [comment]
So we just close this old issue, it's fine as-is, right?
I'm doing it now ... if that wasn't appropriate, please re-open and comment what can / should be done.
