### ISSUE TITLE
Datasets.read() fails when you have no bkg file saved

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#4573]
**Gammapy version**
Version 1.0

**Bug description**
Reading in a `Dataset` that has no bkg file saved for the observation results in fail. 

```
File ~/anaconda3/envs/gammapy-1.0.1/lib/python3.9/site-packages/astropy/io/fits/file.py:562, in _File._open_filename(self, filename, mode, overwrite)
    559 ext = os.path.splitext(self.name)[1]
    561 if not self._try_read_compressed(self.name, magic, mode, ext=ext):
--> 562     self._file = open(self.name, IO_FITS_MODES[mode])
    563     self.close_on_error = True
    565 # Make certain we're back at the beginning of the file
    566 # BZ2File does not support seek when the file is open for writing, but
    567 # when opening a file for write, bz2.BZ2File always truncates anyway.

FileNotFoundError: [Errno 2] No such file or directory: 'pha_obs23523_bkg.fits'
```

**To Reproduce**
```
from gammapy.datasets import Datasets
from gammapy.datasets import SpectrumDatasetOnOff

dataset = SpectrumDatasetOnOff.read("$GAMMAPY_DATA/joint-crab/spectra/hess/pha_obs23523.fits")
dataset.counts_off = None
datasets = Datasets(dataset)

datasets.write('test_no_bkg')

Datasets.read('test_no_bkg')
```

**Comment by MRegeard** [comment]
Hi @Astro-Kirsty, 
I think these are the lines that are wrong. 

https://github.com/gammapy/gammapy/blob/02f9abe0b5f565ede68074c146e713950e89e5c6/gammapy/datasets/io.py#L127-L131

The two if statements are switched. Therefore, when you wrote the dataset, even though `counts_off=None`, `pha_obs23523.fits` was written in the header of the written fits file. But then when writing, because the if statement are correct, `pha_obs23523.fits` is not written. 
When reading, the code read through the fits file header to check which fits file it needs to open. And it don't find it.
