### ISSUE TITLE
Change `write` API for `TemplateSpatialModel`

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#4747]
I tried to use the `write` function of the `TemplateSpatialModel` and noticed that it has a different API than other `SpatialModel`s. 
Instead of having a function 
```python
def write(self, filename, overwrite=False)
```
the function looks like this

https://github.com/gammapy/gammapy/blob/da122ea83dc441ffc327b767329b36146923b7f3/gammapy/modeling/models/spatial.py#L1409-L1415

So it's using `self.filename` from the instantiation of the class. 
Can we change that?

**Comment by registerrier** [comment]
Hi @StFroese , `write` is using the `self.filename` attribute because it is usually called from `Models.write()` to write the full model list to disk. 

The expected behavior is that the user will set `template_model.filename` before calling write if the template was created instead of read. Maybe this needs better documentation?

Another option could be to add a `filename` argument set to `None` by default  on the `write` method. It could override the internal value. 

Opinion @QRemy @adonath @StFroese ?
