### ISSUE TITLE
Issues with gammapy development installation

### ISSUE THREAD

**Issue by OlgaVorokh** [gammapy/gammapy#477]
Hi,

When I run 
python setup.py develop
I get the following error: https://gist.github.com/OlgaVorokh/35d47bd00e69cb3020e8

I am stuck on this -- it runs fine on my aws virtual machine, but fails with this error on my local setup. It's inconvenient to develop on virtual machine, so I finally got time to find out what's wrong with my local enviroment, but not sure where to start.

**Comment by cdeil** [comment]
I think MemoryError means you ran out of memory.
So you could look at how much RAM you have and which process took how much using your Linux system utilities like htop.

Note that the error happens when `python setup.py install` tries to install Astropy as a dependency.

Try installing Astropy first using `sudo apt-get install python-astropy` or `pip install astropy --user`.
If you have Astropy 1.1 or Astropy dev, `python setup.py install` for Gammapy won't try to install or upgrade Astropy.

If you don't manage to `apt-get install` and `pip install` recent versions of the Gammapy dependencies,
you could also give `conda` a try:
https://gammapy.readthedocs.org/en/latest/install.html#id1

Let us know how it goes ...

**Comment by OlgaVorokh** [comment]
@cdeil thanks for helping

**Comment by OlgaVorokh** [comment]
@cdeil thanks for helping me to solve this problem! My local gammapy setup finished successfully.
There was an old version of astropy on my laptop, but now

**Comment by OlgaVorokh** [comment]
@cdeil thanks for helping me to solve this problem! My local gammapy setup finished successfully.
There was an old version of astropy on my laptop, but now everything is OK
