### ISSUE TITLE
Define and add metadata on MapDataset

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4792]
MapDataset metadata need a specific `MapDatasetMetaData` container. We currently have a minimal `meta_table` that is not serialized. It should be replaced by a proper container with well defined entries and tested serialization.

A difficulty specific to `MapDataset` is that we have to design a mechanism for stacking the metadata. We have to understand how each stored information can be stacked.  Currently the `meta_table` is stacked horizontally which relies on `np.stack` for each column.  
A similar approach could be used if one stores the metadata attributes as arrays. But this makes validation more problematic.  Any opinion @adonath ?

Currently, we keep track of:
- telescope : str
- obs_id : str
- pointing coordinates : SkyCoord

There are much more information that we can transfer from the parent observation metadata if they exist there such as:
- instrument : str
- observation_mode : str
- event_type : str
- others?

Currently the proposition from the `ObservationMetadata` PR (#4738) is to have a `dict` for `optional` metadata. It is not clear if we can have this here as well. In particular w.r.t. stacking.

There is also the PR on livetime map (#4407), and a possibility to is have it as a meta attribute. 

Opinions, suggestions @adonath , @bkhelifi @QRemy @AtreyeeS and others?

**Comment by adonath** [comment]
@registerrier I think `pydantic` deals just fine with with lists of objects. So indeed the design can be, that attributes such as `.telescope` have a type of `Union[str, list[str]]`. The only risk I see is performance when we get very large lists and maybe some inconvenience of accessing specific meta data.

**Comment by bkhelifi** [comment]
Here is coming the question of metadata reduction...
- The `instrument` is obviously to be added... as well as `observation_mode`, `event_type`
- For `telescope`, I think that one should totally avoid to repeat N times this parameter. If there is a mixture of sub-arrays, one should have only one instance for each sub-array. The  list of `obs_id` will allow to know exactly the relative weight... 
- From the obs_id one can have the observation times, but I am wondering whether one should not have a TSTART and TSTOP at least. What do you think @kosack ? If there is a GTI selection, I am also wondering if one should not add it, as well as a PHASE selection
- The livetime map has to be added also, good point! Otherwise it is hard to rebuild it... PS: the livetime map is corrected from the radial acceptance -> its name should be more explicit, e.g. effective livetime or somethink else....
