### ISSUE TITLE
Consistency with the docstring for `overwrite`

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#4858]
Just a general comment, we should try to be consistent with the docstring for `overwrite`
We currently have multiple wordings throughout the code:

- Overwrite file if it exists.
- Overwrite file on disk if present
- Overwrite

Plus many more!

_Originally posted by @Astro-Kirsty in https://github.com/gammapy/gammapy/issues/4837#issuecomment-1772495483_
            
We should decided upon the wording in this issue, then I can adapt the docstrings

**Comment by MRegeard** [comment]
@Astro-Kirsty, I agree with you that we should find a standard for this parameter. 

I also found this interesting proposition in the docstring of `EventList` 😆 .
![Capture d’écran 2023-10-27 à 14 30 11](https://github.com/gammapy/gammapy/assets/108189156/a56ca1ef-4d19-46f3-8a2a-94e219a9e3f3)

Jokes asides, I think it should be something really simple, for instance `Overwrite existing file`, so that it is easy to adapt for more complex cases. 
Anyway, the keyword in itself is pretty clear (at least for me) on what it does, so we don't need to really explain it.

**Comment by Astro-Kirsty** [comment]
So many possibilities! 😆

Thanks for your comment @MRegeard . 
I agree with the simple wording, I am in the process of create a PR for this!
