### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4887]
This is a reminder issue to remove the features deprecated since 1.1 before the next release

**Comment by Astro-Kirsty** [comment]
I've made a list of all the deprecation's that need to be taken care of (and the tests associated):


- [gammapy.table.utils.table_from_row_data](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/utils/table.py#L96C33-L96C33)
- [gammapy.irf.io.load_cta_irfs](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/irf/io.py#L146)
- number of deprecation in [gammapy.data.observations](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/data/observations.py#L363C1-L386)
- [gammapy.astro.darkmatter.spectra.table_model](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/astro/darkmatter/spectra.py#L167)
- [gammapy.maps.core.apply_edisp](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/maps/core.py#L1407)
- [gammapy.estimators.points.sensitivity](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/estimators/points/sensitivity.py#L144)
- [gammapy.modeling.models.spatial.plot_iterative](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/models/spatial.py#L312)
- [gammapy.datasets.map.npred_signal](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/datasets/map.py#L489)
- [gammapy.modeling.fit.minuit](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/fit.py#L148)
- [gammapy.maps.axes attribute append](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/maps/axes.py#L109)
- [gammapy.maps.axes attribute append #2](https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/maps/axes.py#L2952)


Not sure about these deprecation's (since v1.2 so before v1.2?):

- https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/models/spectral.py#L1373-L1375
- https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/models/spectral.py#L1694-L1703

**Comment by Astro-Kirsty** [comment]
Not sure about these deprecation's (since v1.2 so before v1.2?):

- https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/models/spectral.py#L1373-L1375
- https://github.com/gammapy/gammapy/blob/e43ec2735e74886283d672d59d874da9d43bf060/gammapy/modeling/models/spectral.py#L1694-L1703

**Comment by AtreyeeS** [comment]
https://github.com/gammapy/gammapy/pull/4924 addressed the issue in gammapy/utils. The remaining tasks remain open. Reopening this PR

**Comment by Astro-Kirsty** [comment]
All of the deprecation should be taken care of (pending the merge of PR: #4927)
