### ISSUE TITLE
Make info string scheme consistent

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#492]
We agreed to use this
https://gammapy.readthedocs.org/en/latest/development/howto.html#object-summary-info-string
scheme for generating info string for gammapy classes.

This scheme needs to be applied in various places in gammapy, i.e.
- Create `__str__` method or convert existing methods
- Add `summary` method or modify existing methods for configurable info strings

**Comment by cdeil** [comment]
I think this is a way to find most (all?) classes / methods that need to be adapted:
https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=%22def+info%22

**Comment by cdeil** [comment]
In #1109 I did a small change to the `__str__` and `info` of the source / catalog classes and was reminded of this unresolved discussion here.

At the moment users can do this to print nicely:
```
>>> print(source)
>>> print(source.info(info='basic'))
```
This will not print nicely, because it just returns a Python string:
```
>>> source.info()
```

I'm not sure what the best pattern is for making and printing infos about objects in Gammapy.

One option that makes `thing.info()` print nicely and not just return a string could be this:
```
def __str__(self):
    return self._info_str()
def info(self, selection='all'):
    """This is the only one in the HTML docs, put docstring here."""
    print(self._info_str(selection)
def _info_str(self, selection):
    # build and return string here
```
Another slightly different option could be this:
```
def __str__(self):
    return self.info(action='return')

def info(self, selection='all', action='print'):
    """This is the only one in the HTML docs, put docstring here."""
    s = '...' # build string

    if action == 'print':
        print(s)
    elif action == 'return':
        return s
    else:
        raise ValueError('Invalid action')
```

Or, since changing `selection` is rare, we could just have an `info_str` method that returns a string, and teach users via docs that they always have to `print(thing)` or `print(thing.info(selection='')`, i.e. avoid some boilerplate code in Gammapy.

@joleroi @adonath @woodmd  - Thoughts?

This will just take an hour to make consistent throughout Gammapy and has an impact on user experience, so I'm putting this under the v0.7 milestone and plan to do it soon.

**Comment by cdeil** [comment]
I think this is almost completely done. Closing. Of course, PRs to improve or complaints that something isn't nice are always welcome.
