### ISSUE TITLE
astropy and scipy versions for gammapy 1.1

### ISSUE THREAD

**Issue by andriineronov** [gammapy/gammapy#5073]
I was using the latest version of gammapy (1.1), installed with pip install, which is recommended as one of the two ways to install gammapy at https://docs.gammapy.org/dev/getting-started/index.html.  As a matter of fact it enters in conflict with the latest versions of astropy, scipy, pydantic ..... etc (problems with evoking DataStore and other basic functions). I checked that astropy<6.0, scipy<1.12, pydantic<2 works. I am not sure if other packages will be conflicting with this way of installation.

**Comment by Astro-Kirsty** [comment]
This is the expected behaviour as there are specific versions of astropy, scipy and pydantic (along with other packages too) that should be used with the specific versions of gammapy. 
We typically recommend setting up a virtual environment to ensure all packages have the correct version. 
The package versions for v1.1 are listed in [this environment file](https://github.com/gammapy/gammapy-webpage/blob/gh-pages/download/install/gammapy-1.1-environment.yml).

I hope this helps

**Comment by registerrier** [comment]
This is now solved in the latest v1.2 release.  Closing now.
