### ISSUE TITLE
Remove or rename SkyMap empty and empty_like?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#513]
The Gammapy [SkyMap](http://docs.gammapy.org/en/latest/api/gammapy.image.SkyMap.html) and [SpectralCube](http://docs.gammapy.org/en/latest/api/gammapy.cube.SpectralCube.html) classes currently have `empty` and `empty_like` constructors.

I find this confusing, because in Numpy those names are used differently.
There `empty` creates uninitialised data array, and when filling a constant value (like we do here in Gammapy), the function is called `full` and `full_like`:
http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#ones-and-zeros

Now I'm not exactly sure what the best solution here is ... first thoughts:
- If we keep the methods, they should be renamed to `full` and `full_like` to be consistent with Numpy, or to some other name that is not used by Numpy (to avoid Numpy users like me being confused)
- We don't want to make wrappers for all the Numpy array creation functions (`zeros`, `zeros_like`, `ones`, `ones_like`), right?
- We could remove the `empty` and `empty_like` methods ... e.g. [xarray.DataArray](http://xarray.pydata.org/en/latest/api.html#dataarray) doesn't have them either. Instead they have [DataArray.copy](http://xarray.pydata.org/en/latest/generated/xarray.DataArray.copy.html) and much more complex `__init__` and `.data` property, so that (I think) a user could do `da2 = da1.copy(deep=True)` followed by `da2.data = fill_value`.

My proposal would be to change to `full` and `full_like` now (unless someone has a better name suggestion)(even if the names are a bit awkward) and to keep looking at `xarray` on how to do things well, but not attempt something fancy now.

**Comment by adonath** [comment]
I would suggest the following:

I would keep the methods `empty` and `empty_like` for now, but let them create empty arrays like numpy does using `np.empty()`. And then overload the `.fill()` method to accept floats, which would be consistent with numpy again. If a user wants to create an array with zeros, this would look as following:

```
skymap = SkyMap.empty()
skymap.fill(0)
```
Which is analog to the numpy syntax.

The whole point about the `.empty()` and `.empty_like()` methods is actually setting up the WCS transformation and not really to fill the data. I'm against renaming to `.full()` and `.full_like()`, because I think in our context it's a misnomer.

Adding a `.copy()` method to the `SkyMap` class  is a good idea!

**Comment by adonath** [comment]
Some other name suggestions, instead of `empty()`:

`from_scratch()`, `new()`, `create()`

**Comment by cdeil** [comment]
I'm :-1: on calling `np.empty` and having uninitialized memory ... too easy to screw up.

@adonath - How about adding a `fill=None` argument to `.copy` with this?
```
map = deepcopy(self)
if fill is not None:
    map.fill(fill)
return map
```

Smaller API, but still covers the common use case on one line:
```
map2 = map.copy(fill=0)
```

**Comment by adonath** [comment]
Yes, I agree. What's now called `.empty()` will be one of the standard ways to create sky maps and the data should well defined after initialization. What do you think about the other name suggestions? Or do you have any other suggestions yourself? 

I somehow prefer, when `.copy()` just returns a plain copy (because that's what the name suggests and strictly speaking it would conflict again with numpy's `.copy()` method on arrays, if we'd add arguments to it). But we can still have a `foobar_like()` (whatever name we choose...) method, which allows for any arguments we think users might want... 

So my suggestion would be to rename the existing functions, but still add the `.copy()` method and let `.fill()` take floats as well, because I think it will be generally useful.

**Comment by cdeil** [comment]
How about this?
```python
map2 = map.copy().fill(0)
```

**Comment by cdeil** [comment]
@adonath  - What about my last suggestion?

Let's try to get a consensus on this and make the change today, so that Gammapy 0.4 can ship tomorrow.

**Comment by adonath** [comment]
Your last suggestion is again not strictly compatible with numpy, because `ndarray.fill()` works in place and doesn't return anything, right?

My preference, as you suggested in your initial post, would be to just rename `.empty()` and `.empty_like()` to something else. This is the least work right now and doesn't have conflicts with numpy's API. `.empty()` could be something like `.from_wcs_spec()` 

I'd be fine as well with removing `.empty_like()` and just write:
```
skymap2 = skymap.copy()
skymap2.fill(0)
```
Of course this is one line more of code, but it's explicit, well readable and compatible with numpy syntax.

**Comment by cdeil** [comment]
> Your last suggestion is again not strictly compatible with numpy, because ndarray.fill() works in place and doesn't return anything, right?

You're right.

And for now I also think your suggestion is best.

But I'd like to meditate on this some more and not rush in a change, so I'm punting this to the 0.5 milestone now.

**Comment by adonath** [comment]
Just saw that in fermiPy the corresponding method is called `.create()` (see [here](https://github.com/gammapy/gammapy/pull/660/files#diff-13c542174693a745736137d81cdb5b79R148)). Maybe we rename `.empty()` and `empty_like()` to `.create()` and `.create_like()`?

**Comment by cdeil** [comment]
SkyImage and SkyCube is deprecated; would suggest to leave as-is.

But I'm keeping this issue open and moving to v0.9, because we should review and make sure the create / copy methods in the new gammapy.maps are nice and how we like them.

**Comment by cdeil** [comment]
The plan is to delete the old SkyImage / SkyCube in the next days, before the v0.8 release.

@adonath - I think we're both not 100% satisfied yet with the map create methods on the new classes, but I don't see any concrete action item here. So closing this old issue. Of course, a new issue with a proposal for change or addition in maps is welcome any time.
