### ISSUE TITLE
Expose `FitResults` in the documentation

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#5306]
In our documentation, we expose `datasets.models` , `dataset.models`, `models`, `model` to access the parameter values/errors. All of this should be replaced by consistently calling `FitResult.models`. 
It should also be mentioned that `datasets.write` does not write the complete covariance, but `FitResult.models.covariance` does.

**Comment by bkhelifi** [comment]
The read method of the FitResult should be added into a separated PR

**Comment by bkhelifi** [comment]
@registerrier, @adonath and @QRemy: in order to prevent using Datasets.models.covariance that is not correct after the fit, one should obviously update the tutorials by using FitResult.models.covariance. This should be done into a dedicated PR.
But, for users knowing Gammapy, they might not read the new tutorials or the release logs... So, I propose that:
- one renders all the 'models' parameters private members of the dataset classes,
- remove the setter 'models',
- add a function 'set_models()'.
This is a (easy) change of API that will prevent further confusions... 
Any thought?

**Comment by Astro-Kirsty** [comment]
I will add the read function and work on making sure we are calling `FitResult.models` rather than `dataset.models` in the docs

**Comment by Astro-Kirsty** [comment]
With the update in https://github.com/gammapy/gammapy/pull/5317 we do not need to change the above. 

See #5319 for the read function

**Comment by Astro-Kirsty** [comment]
With the new implementation by @QRemy, these issues should be fixed?

**Comment by QRemy** [comment]
Resolved by #5317
