### ISSUE TITLE
Question on SkyMapCollection attributes

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#578]
@adonath - Just now I looked at [SkyMapCollection](https://gammapy.readthedocs.io/en/latest/api/gammapy.image.SkyMapCollection.html) for the first time (I think) and saw that it has these class-level attributes

```
class SkyMapCollection(Bunch):
    _map_names = []
    name = None
    meta = None
    wcs = None
```

Naively I would have expected that:
- map names are stored in the skymaps (and if needed re-exposed by the collection as a property)
- wcs to to stored in the skymaps (and allowed to differ between different maps).

Would it be possible / make sense to make this change?

Map names and WCS aren't class-level data, but instance-level data, so should be set in `__init__`, no?

It would also be good to have some brief high-level description on what `SkyMapCollection` is and isn't good for. E.g. the idea is that it can only store `SkyMap`, no? And if I have extra things I can store them as extra attributes or in meta, right?

**Comment by adonath** [comment]
The class level attributes were introduced, because the `Bunch` object overrides the `__settattr__` operator. This means if you only set them in `SkyMapCollection.__init__`, they are not real class attributes, but stored in `self.keys`, i.e. they can't be hidden anymore. . I'm not sure if this had any other implications...

The `_map_names` attribute is needed, because the `Bunch` object inherits from `dict` and entries
don't have an order. If you want to keep track of the order the sky maps were added to the collection, you have to  do this yourself.

The `wcs` attribute was an idea to define a global common `WCS` for all the maps, which might be useful for Fermi data, where you have to reproject e.g. the diffuse model. But its not used right now.

I agree the scope of the `SkyMapCollection` class is not yet well defined. The main reason it was introduced was for FITS I/O and as a handy container for multiple sky maps

**Comment by cdeil** [comment]
@adonath - Thanks for the infos.
I'll think about this a bit.

I'm pretty sure the class-level attribute for `_map_names` isn't a good pattern. One could either implement `__new__` on the subclass, or just not sub-class `Bunch` and do something else.

It mostly depends on whether we want to keep this class at all and what it's use cases are how we should proceed here and improve or remove this class ... it's not clear to me yet.

**Comment by adonath** [comment]
@cdeil 

I agree,

**Comment by cdeil** [comment]
#707 has a new implementation of SkyImageCollection (and renames to SkyImageList) and adds tests.

It doesn't support dot access at the moment. That could be added back, but I'm not even sure if it's a good idea to do that on the top-level object, because that will cause a lot of complexity and problems in corner cases:
- What to do about a name like "COUNT MAP" that isn't a Python identifier. Others use such names and we have to support it.
- What about names like "count" that is a list method name. Should `images.count` give the list method of that name or the SkyImage?

The current `SkyImageList` code has a few TODOs left, and other additions / changes are possible. Let's use a separate issue  / PR for each suggested change though. I'm closing this issue now as the main problems have been fixed in the new class.
