### ISSUE TITLE
PSF containment correction and thresholds for spectral analysis

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#589]
PSF containment correction is applied with `psf_table.integral.` Because the PSF is not always well characterized, the integral fails at low energies resulting in a `nan` being stored in the arf. 

This is not taken into account at the moment for the low threshold estimate and can lead to failure in the spectral fit.

Note that this raises the question of having configurations with theta square cuts which would provide better low energy thresholds. Opinion? @cdeil @joleroi @JouvinLea

**Comment by cdeil** [comment]
> PSF containment correction is applied with psf_table.integral. Because the PSF is not always well characterized, the integral fails at low energies resulting in a nan being stored in the arf.
> This is not taken into account at the moment for the low threshold estimate and can lead to failure in the spectral fit.

Yes, this is a big issue.
The question is what to do about it.

If I understand correctly, what we currently do is to use the safe energy thresholds from the AEFF file?
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/effective_area/index.html
And you're saying you have a case where the PSF has NaN above that low energy threshold?
Can you please point out the file so that we have a concrete test case?

Do you already have a suggestion how to handle this in Gammapy?
- Extrapolate the last non-NaN value?
- Automatically restrict the energy range and emit a warning?
- Add extra energy threshold parameters to the PSF IRF file?

> Note that this raises the question of having configurations with theta square cuts which would provide better low energy thresholds.

Yes, would be nice to have as an extra option.
But I think the getting the full-enclosure IRFs nicely working and tested is higher priority and will keep us busy for a little longer.
There's this reminder issue for HESS that we should test consistency for full-enclosure vs. point-like IRFs:
https://github.com/gammasky/hess-host-analyses/issues/22

**Comment by cdeil** [comment]
No discussion since 2016 -- closing now.

@registerrier - Please re-open or file a new one if needed (pretty sure there' still energy-threshold related issues).
