### ISSUE TITLE
Don't hardcode return types 

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#695]
Sometime we have methods on some class in gammapy that hard code the return type to the class name they're attached to. This lead to unwanted side effects if the method is called by a subclass of this class.

Example:
`SkyImage.cutout` returns a `SkyImage`
`SkyMask.cutout` (daughter class) also returns as `SkyImage`, where is should return `SkyMask`

Independent of whether you not you like subclassing `SkyImage` this should not happen. We should systematically fix this according to this scheme

https://github.com/gammapy/gammapy/commit/82eac793d4dd5fe52ab0f1ba9be9ad74b8d8af18#commitcomment-18860217

**Comment by cdeil** [comment]
👍  to the idea because it's more often (always?) what users of sub-classes expect.
Also  and 👍  to the implementation you chose to use `self.__class__` instead of the class name.

I looked a bit and couldn't find an automatic way to find all cases where we should make the change.
It's probably possible with pylint, but I don't have time to investigate.

Here's another case in `SkyImage` where this change should be made:
https://landscape.io/github/gammapy/gammapy/565/modules/gammapy/image/core.py#L506
Apparently the default settings we use there don't find / flag this code smell.

**Comment by adonath** [comment]
@joleroi Good point! I also think changing to `self.__class__` is a good solution.

**Comment by cdeil** [comment]
I'm closing this old issue. The `SkyMask` class is gone since a long time. In Gammapy.maps we now mostly use `self.__class__` to make new objects as suggested above.

An IMO even better pattern is to use `clone`. For this we still have #1547 - please comment there.
