### ISSUE TITLE
test_command_line_gammapy_image_ts fails

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#711]
There's still fails for `test_command_line_gammapy_image_ts` in some builds on travis-ci:
https://travis-ci.org/gammapy/gammapy/jobs/161272547#L950

I did work on the example files in `gammapy-extra` (see script there), the test and the TS map implementation and command line script a bit in #707 and #710 in the last days.
And I don't see the fail locally.

One reason the test is hard to debug is that the printout is useless.
Maybe asserting on one or two pixel values or summary stats like `max` or `sum` would be better instead of `(200, 200)` pixels?

@adonath - Do you see the fail if you update to `gammapy-extra` and `gammapy` master? Do you have time to improve the test or should I?

**Comment by adonath** [comment]
#713 includes a fix for this.

I could reproduce the error locally with scipy 0.18 and numpy 1.11.1. I didn't check in detail, but I noticed that the number of iterations was different when the test failed. So it could be that the minimizer obtained different results. As a quick fix I removed the `assert_allclose` on the niter map, because we don't care about the number of iterations, as long as the fitted flux is consistent within ~1%. As as second fix I lowered the the absolute tolerance of `assert_allclose` checks to `1E-5`, which should be more then sufficient.

**Comment by cdeil** [comment]
Fixed by @adonath in 748a099dfdb12e808c6450db20e11f507dec6ed2 (in #713).

Looks like `niter` was a bit different depending on the machine.
Tests pass for me now locally in master.

@adonath - Thanks!
