### ISSUE TITLE
make test-notebooks installs gammapy

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#727]
As the title says, if you run

```
make test-notebooks
```

the command

```
python setup.py install --user
```

is executed, which leads to great confusion if you're used to work with 

```
python setup.py develop
```

(like me)

**Comment by cdeil** [comment]
How should we do?

- Run `python setup.py build_ext --inplace` instead and add to `PYTHONPATH` just when running `python test_notebooks.py`? This could be confusing as well for devs that don't use / don't know what `build_ext --inplace` does?

- I think removing the `make test-notebooks` target to avoid confusion and running the two commands on travis-ci isn't easy, because of the way our `.travis.yml` is structured.

- Maybe just not list `make test-notebooks` in the `make help` output, and instead encourage devs to run`python2 test_notebooks.py` and `python3 test_notebooks.py` locally instead?

@joleroi - Let me know what you think is best, and I'll make a commit here to implement it.

**Comment by joleroi** [comment]
Very naive question:
Replacing
```
 env: PYTHON_VERSION=2.7 MAIN_CMD='make' SETUP_CMD='test-notebooks'
        CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_NOTEBOOKS 
```
by
``` 
env: PYTHON_VERSION=2.7 MAIN_CMD='python' SETUP_CMD='test_notebooks.py'
        CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_NOTEBOOKS 
```
won't work?

**Comment by cdeil** [comment]
I don't think that it will work. There would never be a Gammapy build, so the import for the Cython TS code e.g. in the detect notebook would fail.

**Comment by joleroi** [comment]
of course ...

Then I would go for
> Maybe just not list make test-notebooks in the make help output, and instead encourage devs to runpython2 test_notebooks.py and python3 test_notebooks.py locally instead?

ok @adonath ?
