### ISSUE TITLE
Changing the `.table` attribute breaks `SourceCatalog` indexing

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#781]
Currently the `SourceCatalog` indexing by source name returns incorrect results, when the underlying `.table` attribute is changed in place, e.g. by sorting:

```
from gammapy.catalog import SourceCatalog2FHL
fermi_2fhl = SourceCatalog2FHL()

print(fermi_2fhl['2FHL J0033.6-1921'])

fermi_2fhl.table.sort('GLON')

print(fermi_2fhl['2FHL J0033.6-1921'])
```

Which yields:
```
Source: 2FHL J0033.6-1921

RA (J2000)  : 8.41149997711
Dec (J2000) : -19.3575000763
GLON        : 94.2800216675
GLAT        : -81.222366333


Source: 2FHL J1801.3-2326e

RA (J2000)  : 270.339996338
Dec (J2000) : -23.4400005341
GLON        : 6.52657604218
GLAT        : -0.25105163455
```

I think this behaviour should be fixed, because it is common use case e.g. to look for the 10 highest significant or largest sources in a catalog.

**Comment by adonath** [comment]
A possible fix could be to use `Table` advanced indexing. Here's a minimal example:

```
from astropy.table import Table
t = Table([('one', 'two', 'three', 'four'), (8, 7, 6, 5)], names=('a', 'b'))
t.add_index('a')

print(t.loc['two'])

t.sort('b')

print(t.loc['two'])
```

Which returns:
```
 a   b 
--- ---
two   7
 a   b 
--- ---
two   7

```

**Comment by cdeil** [comment]
There's many classes in Gammapy that are supposed to be read-only.
Every time we compute something in `__init__` or explicitly create a cache, things will break when the underlying data is changed.

So we should try to have as few such pitfalls as possible, and  where we need to keep the pre-computation or cache for performance reasons, add a sentence to the docstring explaining that this object is supposed to be used as read-only.

In this case, I think performance is not a big concern, right?
So maybe we should just create the dict that's used for the name lookup from `table` on the fly?

Yes, we could create and use aTable index if you want.
My preference would be to keep our "custom" implementation in this case, because it means we can  improve it, e.g. by string fuzzy-match or also searching other columns so that "Crab" will give a match.
I don't care much if it's implemented as slicing or a method.

@adonath - What's your preference / suggestion for change here?
