### ISSUE TITLE
Problem with example_plot_spiral_arms.py

### ISSUE THREAD

**Issue by rlopezcoto** [gammapy/gammapy#839]
Hi, 

if I try to run the example, I get the following error: 
```
 File "test.py", line 23, in <module>
    x, y = vallee_spiral.xy_position(radius=radius, spiralarm_index=spiralarm_index)
  File "/Users/rubenlopez/anaconda/lib/python2.7/site-packages/gammapy/astro/population/spatial.py", line 350, in xy_position
    theta = self.theta(radius, spiralarm_index=spiralarm_index)
  File "/Users/rubenlopez/anaconda/lib/python2.7/site-packages/gammapy/astro/population/spatial.py", line 402, in theta
    theta = k * log(radius / r_0) + theta_0
  File "/Users/rubenlopez/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 386, in __array_prepare__
    converters, result_unit = UFUNC_HELPERS[function](function, *units)
  File "/Users/rubenlopez/anaconda/lib/python2.7/site-packages/astropy/units/quantity_helper.py", line 108, in helper_dimensionless_to_dimensionless
    .format(f.__name__))
TypeError: Can only apply 'log' function to dimensionless quantities
```
I updated astropy and I still got the same error, which was solved by changing line 19 to:
```
radius = np.arange(2.1, 20, 0.1)
```
Furthermore, the naming of the spiral arms does not correspond to that of the vallee paper:
http://iopscience.iop.org/article/10.1088/0004-6256/135/4/1301/pdf

**Comment by cdeil** [comment]
This works for me:
```
python examples/example_plot_spiral_arms.py
```
with 
* Numpy 1.11.3
* Astropy 2.0.dev17685
* Gammapy 0.6.dev3945

@rlopezcoto - Is this the example you're running?

Which versions of Numpy, Astropy, Gammapy do you have?
You can print them with
```
python -c 'import numpy; print(numpy.__version__)'
python -c 'import astropy; print(astropy.__version__)'
python -c 'import gammapy; print(gammapy.__version__)'
```

---

> Furthermore, the naming of the spiral arms does not correspond to that of the vallee paper:
> http://iopscience.iop.org/article/10.1088/0004-6256/135/4/1301/pdf

@adonath - Can you please have a look?

I think this was discussed / fixed / checked when you made the plot for the ICRC proceeding last year?
http://docs.gammapy.org/en/latest/astro/population/index.html#getting-started
Maybe we're not using Vallee or it's still wrong?

Also -- could you please change all Gammapy code to use
http://docs.astropy.org/en/latest/api/astropy.coordinates.Galactocentric.html
instead of our own X / Y / Z, to make sure results are well-defined and e.g. not the X-Y axes are flipped.

At the moment we're starting to use `gammapy.astro.population` to simulate the faint Galactic source population, so it's important to get this right.

@adonath - If you don't have time for this, please assign this issue back to me.

Or @rlopezcoto - maybe fixing this (or improving the docs) could be your first pull request to Gammapy?

**Comment by adonath** [comment]
The example works for me as well.

Concerning the labelling of the spiral arms:

| Original plot | Gammapy plot |
|-----------------|--------------------|
|![vallee_spirals](https://cloud.githubusercontent.com/assets/3715928/21978126/788344ae-dbd9-11e6-948c-4d17138c1337.png)|![gp-vallee-spirals](http://docs.gammapy.org/en/latest/astro/population/plot_spiral_arms.png)|

I can only see one difference, which is that `Cygnus` part of the `Norma` arm isn't labelled. 
@rlopezcoto Can you explain in more detail what do you think is not correct?

**Comment by rlopezcoto** [comment]
The versions of numpy/gammapy/astropy I'm using are:

- python -c 'import numpy; print(numpy.__version__)'
1.11.3
-  python -c 'import astropy; print(astropy.__version__)'
1.3
-  python -c 'import gammapy; print(gammapy.__version__)'
0.4

I cannot update further gammapy/astropy using conda, shall I download the development version from git?

When I run the example, if I plot only the vallee spiral, I get the following plot:
<img width="698" alt="screen shot 2017-01-16 at 11 18 11" src="https://cloud.githubusercontent.com/assets/17042312/21979030/7aaeb322-dbdd-11e6-8435-883cd92a88a7.png">
whose arms are not the same as the ones you showed in the previous figure.

According to the astropy convention that @cdeil mentioned before:
http://docs.astropy.org/en/latest/api/astropy.coordinates.Galactocentric.html
the coordinates of the sun should be x=-8.3, y=0, right?

**Comment by cdeil** [comment]
Gammapy 0.4 is very old:
http://docs.gammapy.org/en/latest/changelog.html

You should get the development version of Gammapy, although in this case probably updating to Gammapy 0.5 would work as well.

---

At the moment apparently we're using the X/Y orientation that's also shown in the Vallee paper.
Updating to http://docs.astropy.org/en/latest/api/astropy.coordinates.Galactocentric.html is a suggestion, not implemented yet.

**Comment by cdeil** [comment]
This issue was mostly about an old, outdated version of Gammapy. Closing it now.

I've moved the spiral arm plotting script to the docs just now in #976, and filed a reminder issue for myself to change to Astropy Galactocentric coordinates (#977).
