### ISSUE TITLE
Replace "skimage" with "scikit-image"

### ISSUE THREAD

**Issue by nhrjr** [gammapy/gammapy#928]
When following the tutorial in the gammapy.org site, the novice user is advised to call:

$ python -c 'import gammapy; gammapy.test()'
and
$ gammapy-info --dependencies
which both print a list of installed packages. When trying to install the missing packages, one would try to use:
$ pip search skimage
or
$ pip install skimage
while one must use 'scikit-image'.
Renaming these outputs would make it easier.
Also getting a consistent case behaviour would be nice, as Pandas and Numpy are written in upper case.

**Comment by cdeil** [comment]
@nhrjr - Thanks for the suggestion!

Yes, I agree, this (and really all of our install instructions) should be improved.

At the moment we're very busy fixing important bugs and adding features people need.
So I'm putting this under the v0.7 milestone, and we'll get to it in the coming weeks.

**Comment by cdeil** [comment]
@nhrjr - Actually, we're only using scikit-image for one little utility function. So instead of documenting that better, I'll just remove the dependency on scikit-image completely next week before making the v0.8 release.

This is now tracked here:
https://github.com/gammapy/gammapy/issues/1494#issuecomment-405171810

Closing this issue.
