### ISSUE TITLE
Change SkyImage cutout x, y order?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#940]
One thing that tripped me up was that the cutout order is `size=(y, x)`. See:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/cta_data_analysis.ipynb

Suggest to change the example here to something with different width / height to make it clear:
http://docs.gammapy.org/en/latest/image/sky_image.html#image-cutpaste

I would also suggest that our end-user interface always used `(x, y)` order, and the numpy array index convention is rarely encountered. This is the idea behind the `PixCoord` class that I introduced in `regions` and that I propose we start using more.

The way to do it here would be to split out a separate method `cutout_pix` here:
http://docs.gammapy.org/en/latest/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.cutout
(which could use numpy indexing order, but I would suggest to also use x, y) and to have the existing `cutout` method be fore sky coordinate and angular `size=(x,y)`

I'm putting this under the 0.6 milestone for now, but we can defer if there isn't agreement and what to put exactly.

@adonath - First of all - do you agree to go x, y for end user interface?

**Comment by adonath** [comment]
It is the same order that is used in `astropy.nddata.Cutout2D` and it is documented in [SkyImage.cutout](http://docs.gammapy.org/en/latest/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.cutout), but actually I prefer the `(l, b)` or `(ra, dec)` order as well. So :+1: to change it.

I must say I strongly prefer to not introduce special (public) `_pix` methods, because we already have `SkyImage.wcs_pixel_to_skycoord()` and `SkyImage.wcs_skycoord_to_pixel()` as a helper function.
Otherwise, to achieve consistency, we have to expose every method that takes or returns sky coordinates twice,  which clutters the name space, without extending the functionality. And in fact the whole concept of the `SkyImage` class is based on the idea that user don't have to deal with pixel coordinates any more, otherwise one could work more or less directly with the numpy array. 

My suggestion is rather we should change `.wcs_pixel_to_skycoord()` and `.wcs_skycoord_to_pixel()`to use the `PixCoord` class. If for some reason users like to use pixel coordinates, they have to convert
them explicitly to `SkyCoord` before calling a `SkyImage` method. Internally, we can still have hidden `_xxx_pix` methods.

**Comment by cdeil** [comment]
I'm not sure. My experience is that the basic algorithms must be implement with pix.
Otherwise you're always unsure about float rounding effects and it's very hard to have simple and reproducible results / algorithms.

Then the problem is that algorithms from outside the class want to call these pixel-based methods.
So yes, you can make the pix methods private, but then you're calling private methods from outside the class, and it's not really an implementation detail any more, things break within your package or from user scripts if you change these private methods.

So that's been my experience, and thus I'd prefer public pix methods, even if it means a larger API exposed to end users also (with no good way except high-level docs to point of the most common methods).

@adonath - Should we let this issue sit for a few days and then talk and make a decision when I'm back?
Of course, if other devs or users come across this thread, extra opinions welcome.

**Comment by adonath** [comment]
Yes, let's wait and discuss later again.

**Comment by cdeil** [comment]
I'm closing this old issue with a proposal to change SkyImage cutout.

I think the conclusion above is already how the methods in the new gammapy.maps work, and it's probably best to keep SkyImage alone (is deprecated, will be removed at some point) to avoid breaking existing scripts.
