### ISSUE TITLE
How to compute an exposure image?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#948]
Yves was asking me how to compute an exposure image with Gammapy
(for HESS, for multiple runs, starting from DL3 files and a given energy band / assumed spectral index).

He just wants the exposure image, not a counts image or background estimate.

I am aware of Lea's image pipe class, and @adonath, now you added a second version where background modeling is more flexible.

@adonath - Is there a working example snippet how to do it that I should point out to Yves?

Maybe we've been organising the high-level code wrong, always trying to combine computation involving EVENTS and IRFs into a single pipeline class?
I mean, in Fermi and ctools, there's a separate tool to compute exposure, and this is not mixed with EVENTS and background estimation.
Shouldn't we add a function or class to just compute exposure cubes and images?
Does it exist already and just need to be pointed out or added an example in the docs?

**Comment by adonath** [comment]
The function to compute exposure cubes is already available: [exposure_cube](http://docs.gammapy.org/en/latest/api/gammapy.cube.exposure_cube.html#gammapy.cube.exposure_cube).

The function to compute exposure images (computing the weighted integral over the energy assuming some spectral  model) is only part of the `IACTBasicImageEstimator` and `StackedObsImageMaker`.
This should probably be separated from the pipeline classes into a separate function `compute_exposure_image`, so that it can be reused e.g. for computing Fermi exposure image as well.

Apart from that I don't see a major problem in just running the pipeline classes and throw away the images you don't need later The only reason would be, that background estimation might be slow.
The reason why the event and IRF computation is done simultaneously right now is, that it is done in the same Python loop over observations. My expectation was it yields better performance. But I've never checked and it might even not be true, as long as the computation in the Python loop is the bottleneck.

The longer term plan I had for the `IACTBasicImageEstimator`, was to make background estimation optional anyway, so that the pipelines can be build in a more modular way by chaining multiple `XXXImageEstimator` classes.

**Comment by adonath** [comment]
The example how to compute and exposure image would be the same as in the CTA data analysis notebook [here](https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_data_analysis.ipynb#Make-maps). Except that you load the HESS FITS data into the data store.

**Comment by cdeil** [comment]
@adonath - OK.

But the problems we have:
- docs build on RTD is broken, no link for `IACTBasicImageEstimator`.
- no example showing how to do *just* the exposure computation, and how to configure it, i.e. pass an assumed spectral index.

He doesn't need it super urgently. If we can resolve these two points and get back to him next week, that would be great! Let's just keep this open as a reminder issue until it's done.

**Comment by cdeil** [comment]
I'm moving this issue to v0.8.

Roberta and I started coding an example script that might lead to more code in Gammapy:
https://github.com/gammasky/cta-dc1-gps-analysis/blob/master/make_cube.py

The idea there is to do counts, background and exposure and PSF computation separately, and to in each case compute a cube with relatively fine energy binning first, and then to simply sum or average along the energy axis.

My suggestion how to proceed here would be to remove or at least deprecate the existing "ImageEstimator" and "StackedObsImageMaker" classes, because they basically implement cube computation, hidden away in image makers, plus I find the code too intertwined and in the case of the Fermi and IACT image estimator also that there's some redundancy and coupling that's not needed if background estimation and exposure computation are treated as separate steps.

But this needs to be discussed further with @adonath and there's significant more work needed to integrate this in Gammapy. Most likely it would also only make sense to build the new exposure and background computation on gammapy.maps directly, i.e. the change from old SkyImage / SkyCube / image estimators is done in one step, the new high-level code uses gammapy.maps. So https://github.com/gammasky/cta-dc1-gps-analysis/blob/master/make_cube.py is just a prototype where I'm still using SkyImage / SkyCube for now, mainly because the existing `make_exposure_cube` and `make_background_cube` functions still need to be changed over to use maps.

**Comment by cdeil** [comment]
I'm moving this issue to the v0.8 milestone.

The missing part is to add a little helper how to make an exposure image:
https://github.com/gammapy/gammapy/issues/1571#issuecomment-407894414

IMO the MapMaker should also be changed a bit to allow computing just an exposure cube / image, without e.g. having to compute a counts cube.

@registerrier - Let's discuss tomorrow in the call and then get this done for v0.8 in the next days.

**Comment by cdeil** [comment]
I'll make a PR for this today, to change MapMaker to make just exposure if the user wants.

**Comment by cdeil** [comment]
In #1681 @registerrier added a `MapMaker.make_images` which does produce a spectrum-weighted exposure image. Closing this old issue now.
