### ISSUE TITLE
Improve EVENTS peek plots

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#952]
I've produced "peek" plots for the ~ 100 runs from the HESS test data release:
https://hess-confluence.desy.de/confluence/display/HESS/HESS+FITS+data+-+HESS+high-level+public+test+data+release+1#HESSFITSdata-HESShigh-levelpublictestdatarelease1-Dataqualitybasics

The ones for AEFF, EDISP and PSF are useful (although they can be improved a lot also, concerning axis scales and adding safe energy range info).

But for EVENTS, it's not very useful because there are always a few misreconstructed events and the RA / DEC range is almost never chosen in a useful way by default. And for the event rate info, it's very hard to judge if it's constant or not.

So my suggestion here would be:
- For the RA / DEC image, change to a SkyImage in a local TAN projection centered on the pointing position and constant FOV size (not sure how to choose it, should be ~ 3 deg radius for HESS so that the full FOV is contained) (and the object position marked if it's given in the header)
- For the event rate, add a horizontal line with the mean rate, and try to put some error bars for the individual rates, so that it becomes clear if what one sees is Poisson rate fluctuations or real rate variations. Maybe call [excess_error](http://docs.gammapy.org/en/latest/api/gammapy.stats.excess_error.html)?

@facero @kosack - Thoughts on what to put as default debug plots for EVENTS exactly?

Unless someone volunteers to implement something here in the next days, I would make a PR in the coming days (because I need it to prepare the quality assurance plots for the HESS test data release).

**Comment by kosack** [comment]
Looks good.  Btw, I notice you were concerned about the trigger rate not being constant, but it is not normally constant due to the change in zenith angle, so the HESS cut is on a line-fit to the full data and the cut is on deviations from that line (the change is not really linear, but probably more like cos(z), but it's approximately linear in a ~30 min observation).  It could be useful to also just fit a line to the data and overplot it in the peek.

**Comment by kosack** [comment]
Also  +1 for error bars if possible. Would also be useful on the containment plots, since it is not clear that the crazy behavior is due to stats. Not sure the best way to calculate them there though.  We've started implementing things like error bar calculation on effective area in ctapipe (which I think just uses an `astropy.stats` function), so could be useful to translate some of that to `gammapy` once it's tested.

**Comment by cdeil** [comment]
I forgot about this old issue and didn't see it. Closing in favour of #1794 . Will do this now.
