### ISSUE TITLE
Use QTable in Gammapy?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#980]
In https://github.com/gammapy/gammapy/pull/978#issuecomment-295322592, @mhvk suggested we use `QTable` by default, instead of `Table`. As I mentioned in https://github.com/gammapy/gammapy/pull/978#issuecomment-295290263, I'm not so sure it's better.

At the moment we use QTable 7 times:
https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=qtable&type=
and Table over 100 times.

This is a reminder issue for myself to (first learn a bit about how QTable works / differs from Table) and then to try it out for Gammapy and see if things get better or worse.

Putting it under the 0.7 milestone for now.

**Comment by cdeil** [comment]
Let's use the following example data for playing around and discussing:
```python
import astropy.units as u
from astropy.table import Table, QTable
url = 'https://github.com/gammapy/gammapy-extra/raw/master/datasets/catalogs/fermi/gll_psc_v16.fit.gz'
t = Table.read(url)
q = QTable.read(url)
a = [1, 2, 3] * u.deg
```
will give this:
```python
>>> type(t)
astropy.table.table.Table
>>> type(q)
astropy.table.table.QTable
>>> type(a)
astropy.units.quantity.Quantity
```
This is an example column with a quantity:
```python
>>> type(t['GLON'])
astropy.table.column.Column
>>> type(t['GLON'].quantity)
astropy.units.quantity.Quantity
>>> type(q['GLON'])
astropy.units.quantity.Quantity
```
Now comes the interesting part, I just didn't know that Quantity has an `info` attribute that can store the same attributes as Column.info:
```python
>>> type(q['GLON'].info)
astropy.units.quantity.QuantityInfo
>>> type(t['GLON'].info)
astropy.table.column.ColumnInfo
```
The `repr` doesn't mention "description" or "format"
```python
>>> q['GLON'].info
name = GLON
dtype = float32
unit = deg
class = Quantity
n_bad = 0
length = 3034
```
but it's there:
```python
>>>  q['GLON'].info.__dict__
Out[50]: 
{'_attrs': {'description': None,
  'dtype': None,
  'format': None,
  'indices': [],
  'meta': OrderedDict(),
  'name': 'GLON',
  'parent_table': <weakref at 0x1118ce138; to 'QTable' at 0x11193b0b8>,
  'unit': None},
 '_parent': <Quantity [ 117.69387817, 345.41052246, 117.29309082,...,  112.00807953,
              12.70657349,  57.94722748] deg>}
>>>  q['GLON'].info.description = 'Galactic Longitude'
>>> q['GLON'].info
name = GLON
dtype = float32
unit = deg
description = Galactic Longitude
class = Quantity
n_bad = 0
length = 3034
```
It looks like these info objects have a pre-defined attribute set and are locked down:
```python
>>> q['GLON'].info.spam = 'spam'
AttributeError: attribute must be one of {'indices', 'unit', 'name', 'parent_table', 'format', 'description', 'meta', 'dtype'}
```

This makes me think that `QTable` might be a better choice, if the differences are:
- More things work out of the box without having to type `.quantity` on column objects
- We'lll have to type `.info` more when working with things like column format or description

I see that QTable really is just 10 lines of code, i.e. almost like Table:
http://astropy.readthedocs.io/en/latest/_modules/astropy/table/table.html#QTable
There's some useful high-level docs here:
http://docs.astropy.org/en/latest/table/mixin_columns.html

@mhvk - Partly the issue of people like us still using Table is probably with education. I didn't even know that a `QuantityInfo` exists. It's not listed in the public Astropy API docs:
* http://docs.astropy.org/en/latest/search.html?q=QuantityInfo
http://docs.astropy.org/en/latest/search.html?q=ColumnInfo
Those classed should be listed in the API docs, no?
And some info about the internal data structure in `Table` and `QTable` would be much appreciated. This doesn't even mention `info` objects: http://astropy.readthedocs.io/en/latest/table/implementation_details.html

Before you mentioned that masked tables don't work with QTable yet.
This is not a concern for us in Gammapy, we don't need them and (I think) don't use them anywhere currently.

My main remaining concern (in addition to needing to understand the differences better) before switching to QTable is about I/O (e.g. to FITS or JSON): does it work about the same for Table and QTable? Are there performance differences with QTable taking longer to instantiate on read?

cc @woodmd - Would you be open to trying out QTable in Fermipy instead of Table?

**Comment by mhvk** [comment]
@cdeil - you're right that we need better documentation on the use of `info`; throughout much of the table code, we have been switching to always include `info` before things like `name`, `description` etc. This generalizes not just to `Quantity`, but also to `Time` and `SkyCoord`, when used as mixin columns (cc @taldcroft for that reason). Do you want to open an astropy issue for this? (If not, I can do it).

As for your main concern: at present, this may well be the showstopper for you: the long-standing issue that `Quantity` could not be simply written to a fits file is only now being addressed (https://github.com/astropy/astropy/pull/5910) -- I think right now one would have to do `Table(qtable).write('...fits')`. Similarly, the table joining operations are only in the process of being implemented (https://github.com/astropy/astropy/pull/5841).

p.s.  For reading, I don't think there are performance issues.

**Comment by cdeil** [comment]
> Do you want to open an astropy issue for this? (If not, I can do it).

@mhvk - Can you please do it? (the description / proposed action items will be better than if I do it)

**Comment by mhvk** [comment]
@cdeil - see https://github.com/astropy/astropy/issues/5976

**Comment by taldcroft** [comment]
@cdeil, @mhvk - agreed that improvements in documentation are needed.  But in fairness http://astropy.readthedocs.io/en/latest/table/mixin_columns.html#mixin-attributes does explicitly mention `.info` with an example.

Your confusion with the `col.info` repr not showing the column attributes could be the result of overloading `info` to have two distinct functions:
- Container for the mixin column attributes like name or unit
- Property / callable function that gives info about the column
Whether or not this was a mistake, we need to be even more clear in the docs.

**Comment by cdeil** [comment]
As mentioned above, in Gammapy we currently use `Table` almost everywhere, except if very few cases where we use `QTable`. For now, I have made the decision to change to `Table` everywhere and have started that in #1032 . I'm pointing out issues and give my reasons in this issue and also https://github.com/astropy/astropy/issues/6098 .

We can revisit this decision later, and change to use QTable everywhere, or to a mix of Table / QTable, if there are good arguments to do so. This doesn't have to be the final decision for Gammapy.

Reminder for myself: these are the remaining mentions and uses of QTable in Gammapy that should be adapted:
```
$ ack QTable
gammapy/catalog/fermi.py
9:from astropy.table import QTable, Table
392:        table = QTable()

gammapy/spectrum/energy_group.py
63:    table : `~astropy.table.QTable`
248:        """Table with one energy bin per row (`~astropy.table.QTable`).
271:        """Table with one energy group per row (`~astropy.table.QTable`).

gammapy/time/lightcurve.py
7:from astropy.table import QTable
20:class LightCurve(QTable):

gammapy/utils/fits.py
9:from astropy.table import Table, QTable
241:    # Creating `QTable` from list of row data with `Quantity` objects
244:    # table = QTable(rows=rows)
249:        cls = QTable

gammapy/utils/table.py
21:    table : `~astropy.table.Table` or `~astropy.table.QTable`
30:    # for `Table`, but not for `QTable`.

gammapy/utils/tests/test_table.py
5:from astropy.table import Table, QTable, Column
9:@pytest.mark.parametrize('table_class', [Table, QTable])
```

**Comment by cdeil** [comment]
@mhvk - I'm responding to your comment at https://github.com/astropy/astropy/issues/6098#issuecomment-302541958 here, to avoid complicating the discussion there in the Astropy tracker.

What we do in Gammapy is to use Table data members for most things (event lists, instrument response functions) like this (using wrapper classes, i.e. composition):
```python
class EventList:
    def __init__(self, table):
        self.table = table

    @classmethod
    def read(cls, filename):
        return cls(table=Table.read(filename))
```
and then expose the Astropy / Gammapy objects (mainly Quantity, SkyCoord, Time) as property or lazyproperty:
```python
    @lazyproperty
    def radec(self):
        lon, lat = self.table['RA'], self.table['DEC']
        return SkyCoord(lon, lat, unit='deg', frame='icrs')
```
So on (usually FITS) I/O, only a simple Table gets created, and then more complex objects only get instantiated as needed in a given analysis. It's pretty simple and efficient and works nicely IMO.

But yes, it also has problems because the table data member is mutable and cached properties can get out of sync if users don't know that they're supposed to leave the table alone (and if we use property then some analysis code becomes inefficent because the same property is accessed many times, basically we have to decide everywhere when to use cached or not cached and at the moment it's a bit of a headache and currently inconsistent.

My main point is: Table and QTable both have (different) gotchas and (different) pros / cons. There's a real benefit in only using one or the other, in terms of complexity to deal with for developers and users. So for now I'm going to all Table because that's almost what we currently have. And then, if any Gammapy dev feels that QTable would really be better, and ideally has a few days to make a pull request and change to QTable in all (or at least some major) places, we will consider it.

For me, I prefer Table for now and won't prototype a larger change to QTable in Gammapy. I think my preference for Table is because it really has simpler and less magical behaviour with column getitem / setitem, but probably there's also a strong bias because I've been using Table for years now, and only tried QTable a few times and immediately ran into issues.

**Comment by mhvk** [comment]
OK, makes sense. I think that then it becomes a matter of possibly switching out the back-end, which is less important.

Still, your example is a little scary: what if the particular fits file did not have `RA`, `Dec` in degrees? Your `radec` would now be wrong; with `QTable`, you'd avoid that.

Separately: many astropy classes accept a `copy=False` argument, which should make things faster and less memory intensive.

**Comment by cdeil** [comment]
I would like to come back to this question of how to store data in Gammapy (for EVENTS, IRFs, maps) and continue the discussion with @woodmd @kosack @watsonjj or anyone else that might be interested (e.g. @thomasarmstrong, see #1157).

From my side, this interest was triggered recently when I noticed that processing 20 GB of event list data from CTA with Gammapy is currently slow (still for unknown reasons, see my comment [here](https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_1dc_introduction.ipynb#Next-steps-for-Gammapy)) and thus maybe not suitable for CTA IRF production yet. @watsonjj and I did a little experiment just using `Table.read` and `Table.write` with HDF5 for one of those small 5 MB event list files and it was three times faster. So to continue with that a bit, I've asked here what happens on `Table.read` with FITS BINTABLE [here](https://groups.google.com/forum/#!topic/astropy-dev/Upg65Edl8j8). And I was also just reading  http://wesmckinney.com/blog/apache-arrow-pandas-internals/ about http://arrow.apache.org/ and the future of the pandas DataFrame and possibly tabular data in Python.

So in Gammapy we currently use `astropy.table.Table` for FITS I/O and for in-memory data storage for `EventList`. For IRFs, we use `Table` for FITS I/O, but store the data in-memory as Numpy arrays or Quantity objects (not sure, would have to look at the various classes). In `gammapy.maps` @woodmd never imports `Table`, and instead uses `astropy.io.fits` directly for BINTABLE FITS I/O and stores data in-memory directly as Numpy arrays.

We don't have to do it, but it would be nice if we can first improve our understanding of how exactly `astropy.io.fits` and `Table` work, and then evolve the Gammapy codebase towards something that is efficient, simple and uniform. And maybe already think about whether we might want to have a solution that works for "big data" that doesn't fit into memory in some places, i.e. something like `pyarrow.Table` (see simple example [here](http://arrow.apache.org/docs/python/pandas.html)). We don't need it now, because we can always chunk our data into files / pieces that fit into memory, but I think prototyping with HDF5 and `pyarrow` could be a useful exercise.

This is a pretty fundamental and open discussion - everyone, please chime in!

Concrete questions I have:
* @kosack or anyone from ctapipe: what do you use / want to use for events and IRFs?
* @woodmd - do you see any "warts" in FITS I/O in `gammapy.maps` when just using `astropy.io.fits` directly that `Table` might make nicer? I guess using `Table` objects as data members of `Maps` doesn't make sense, you're perfectly happy with just the Numpy arrays as you have them now?

**Comment by kosack** [comment]
> @kosack or anyone from ctapipe: what do you use / want to use for events and IRFs?

so far we are using pytables (`tables`) to write out, read, and analyze our DL1 and DL2 event lists, but have not chosen any particular technology for DL3 yet (which should be in FITS).  Pytables is HDF5-only, but is quite fast (pandas can use it as a backend as well).   We use `astropy.table` only for small things like data needed for calibration or instrumental layout.  

As far as I can tell, `astropy.table` is not really intended for large datasets, but it's interface is quite nice. The slowness may come from the fact that `astropy.io.fits` is pure python. Perhaps adding a `fitsio` backend would be faster.  

For larger sets, `pandas` seems to be better suited, but since we want to store for example the telescope trigger mask as a boolean array in a column, we cannot use pandas directly, as it supports only scalar columns.  Perhaps for the final DL3 data this is not important - though it could be useful to be able to see what telescopes participate in each event, that info could perhaps be boiled down to a set of "effective multiplicity" columns (e.g. N_SST, N_MST, N_LST or something)

**Comment by taldcroft** [comment]
Would it be helpful to have a pytables backend for `Table`?  I have thought about this since I also use pytables in CXC work.  I don't think it would be all that difficult.  Though of course the basic `Table.read/write` interface misses some of the great features of pytables like indexing and out-of-memory filtering.

> As far as I can tell, astropy.table is not really intended for large datasets

Certainly `astropy.table` is no good for tables that exceed available physical memory.  Is that what you mean by "large"?  I'm definitely interested in any feedback related to memory use / performance for big (but in-memory) tables.  In other words if you can give specific feedback on performance limitations of astropy.table that would be very useful.  Here it is important to be clear on file I/O bottlenecks vs. in-memory table manipulations.

Definitely pandas is quite strong in performance but it is certainly a goal to bring astropy.table into the same league.  Pandas does have some fundamental limitations (as you noted) that were key in our decision to not use it for astropy.

At the recent astropy developers coordination meeting we identified performance as the highest priority for the 3.1 release.  So it is a good time to start putting in requests and issues.

**Comment by kosack** [comment]
Our main problem with using astropy.table for the *lower levels* (e.g reconstruction) of the pipelines is mostly that we want to write the data row-wise: we have a large stream of data being processed, and do not generally know when the stream ends (and it can easily exceed memory), and that so far seems to be inefficient, though I haven't done any tests myself. Probably having a pytables backend would help, as long as it works like the memory-mapped mode where it doesn't necessarily keep everything in ram.  Maybe it's not worth worrying about too much, since ram is less and less of a problem, however the Grid machines we use currently have a limit of 4GB of ram per process, and that is quickly used up by the raw data library's internal cache and various lookup-tables, so there's not much left for storing output. 

It should be noted however, that when we do the final analysis on the output event lists, we so far *do* load it all into memory using pytables (at that point, it's reduced to a manageable level and we don't need to load any external tables or raw data), so in that case, having an `astropy.tables` pytables backend could be very nice, since it would allow us to avoid having several ways to access tabular data, and easily support writing back out the final event list in FITS format.

**Comment by cdeil** [comment]
I'm closing this old issue. It was originally to discuss whether we should use `Table` or `QTable` in Gammapy, and  with #853 we now have a codebase that just uses `Table`, no more `QTable` in Gammapy. I gave my reasoning for this in comments above, the strongest one is that I want consistency and not a mix.

I learned a lot from the discussion and feedback here, so thank you @mhvk @taldcroft @kosack !
